// Generated by WebGPU-KTypes WGSL Backend

fn break_from_loop() {
    {
        var i: i32 = 0;
        loop {
            if ((i < 4)) {
                {
                    break;
                }
                i = 1;
            } else {
                break;
            }
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    break_from_loop();
}
