// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    @builtin(position) position: vec4<f32>,
    texcoord: vec2<f32>,
}

@fragment
fn fs() -> vec4<f32> {
    return vec4<f32>(1.0f, 0.0f, 0.0f, 1.0f);
}

@vertex
fn vs(@location(0) xy: vec2<f32>) -> Struct_3 {
    var vsOutput: Struct_3;
    vsOutput.position = vec4<f32>(xy, 0.0f, 1.0f);
    return vsOutput;
}
