// Generated by WebGPU-KTypes WGSL Backend

fn unpack4xI8(arg_0: u32) -> u32 {
}

fn unpack4xU8(arg_0: u32) -> u32 {
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var idx: i32 = 2;
    _ = unpack4xI8(12u)[idx];
    _ = unpack4xU8(12u)[1];
}
