// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    a: f32,
    b: vec3<f32>,
}

fn foobar(normals: array<vec3<f32>, 12>, count: u32) -> Struct_2 {
    {
        var i: u32 = 0u;
        loop {
            if ((i < count)) {
                {
                    var n0: vec3<f32> = normals[i];
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
    {
        var j: u32 = 0u;
        loop {
            if ((j < count)) {
                {
                    var n1: vec3<f32> = normals[j];
                }
                j = (j + 1u);
            } else {
                break;
            }
        }
    }
    return Struct_2(0.0f, vec3<f32>(0.0f));
}

@fragment
fn main() {
    var arr: array<vec3<f32>, 12>;
    foobar(arr, 1);
}
