// Generated by WebGPU-KTypes WGSL Backend

@fragment
fn fs_main() -> vec4<f32> {
    var my_array: array<vec2<f32>, 2> = array<vec2<f32>, 2>(vec2<f32>(0.0f, 0.0f), vec2<f32>(0.0f, 0.0f));
    var index_0: i32 = 0;
    var val_0: vec2<f32> = my_array[index_0];
    var val_1: vec2<f32> = my_array[index_0];
    return (val_0 * val_1).xxyy;
}
