// Generated by WebGPU-KTypes WGSL Backend

@compute
@workgroup_size(1, 1, 1)
fn f() {
    var b: array<vec3<f32>, 2> = array<vec3<f32>, 2>();
    var poly: vec4<f32> = vec4<f32>(0);
    var k: i32 = 0;
    var j: i32 = 0;
    poly[0] = (b[j][1] * b[k][2]);
}
