// Generated by WebGPU-KTypes WGSL Backend

@fragment
fn func(@location(0) input_location: f32, @builtin(position) arbitrary_position: vec4<f32>, @builtin(primitive_index) index: u32) -> vec4<f32> {
    return vec4<f32>(arbitrary_position.xy, input_location, f32(index));
}
