// Generated by WebGPU-KTypes WGSL Backend
const one: i32 = 1;

fn return_i32_ai() -> i32 {
    return 1;
}

fn return_u32_ai() -> u32 {
    return 1;
}

fn return_f32_ai() -> f32 {
    return 1;
}

fn return_f32_af() -> f32 {
    return 1.0f;
}

fn return_vec2f32_ai() -> vec2<f32> {
    return vec2<f32>(1);
}

fn return_arrf32_ai() -> array<f32, 4> {
    return array<f32, 4>(1, 1, 1, 1);
}

fn return_vec2f32_const_ai() -> vec2<f32> {
    var vec_one: vec2<f32> = vec2<f32>(1);
    return vec_one;
}

fn return_const_f32_const_ai() -> f32 {
    return one;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    return_i32_ai();
    return_u32_ai();
    return_f32_ai();
    return_f32_af();
    return_vec2f32_ai();
    return_arrf32_ai();
    return_const_f32_const_ai();
    return_vec2f32_const_ai();
}
