// Generated by WebGPU-KTypes WGSL Backend
struct Struct_6 {
    old_value: i32,
    exchanged: bool,
}
struct Struct_8 {
    old_value: u32,
    exchanged: bool,
}
@group(0) @binding(0)
var<storage, read_write> atomic_i32: atomic<i32>;
@group(0) @binding(1)
var<storage, read_write> atomic_u32: atomic<u32>;

fn test_atomic_i32() {
    atomicStore(&atomic_i32, 1);
    atomicCompareExchangeWeak(&atomic_i32, 1, 1);
    atomicCompareExchangeWeak(&atomic_i32, 1, 1);
    atomicAdd(&atomic_i32, 1);
    atomicSub(&atomic_i32, 1);
    atomicAnd(&atomic_i32, 1);
    atomicXor(&atomic_i32, 1);
    atomicOr(&atomic_i32, 1);
    atomicMin(&atomic_i32, 1);
    atomicMax(&atomic_i32, 1);
    atomicExchange(&atomic_i32, 1);
}

fn test_atomic_u32() {
    atomicStore(&atomic_u32, 1);
    atomicCompareExchangeWeak(&atomic_u32, 1, 1u);
    atomicCompareExchangeWeak(&atomic_u32, 1u, 1);
    atomicAdd(&atomic_u32, 1);
    atomicSub(&atomic_u32, 1);
    atomicAnd(&atomic_u32, 1);
    atomicXor(&atomic_u32, 1);
    atomicOr(&atomic_u32, 1);
    atomicMin(&atomic_u32, 1);
    atomicMax(&atomic_u32, 1);
    atomicExchange(&atomic_u32, 1);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    test_atomic_i32();
    test_atomic_u32();
}
