// Generated by WebGPU-KTypes WGSL Backend

@compute
@workgroup_size(1, 1, 1)
fn f() {
    var clamp_aiaiai: i32 = clamp(1, 1, 1);
    var clamp_aiaiaf: f32 = clamp(1, 1, 1.0f);
    var clamp_aiaii: i32 = clamp(1, 1, 1);
    var clamp_aiaif: f32 = clamp(1, 1, 1.0f);
    var clamp_aiafai: f32 = clamp(1, 1.0f, 1);
    var clamp_aiafaf: f32 = clamp(1, 1.0f, 1.0f);
    var clamp_aiaff: f32 = clamp(1, 1.0f, 1.0f);
    var clamp_aiiai: i32 = clamp(1, 1, 1);
    var clamp_aiii: i32 = clamp(1, 1, 1);
    var clamp_aifai: f32 = clamp(1, 1.0f, 1);
    var clamp_aifaf: f32 = clamp(1, 1.0f, 1.0f);
    var clamp_aiff: f32 = clamp(1, 1.0f, 1.0f);
    var clamp_afaiai: f32 = clamp(1.0f, 1, 1);
    var clamp_afaiaf: f32 = clamp(1.0f, 1, 1.0f);
    var clamp_afaif: f32 = clamp(1.0f, 1, 1.0f);
    var clamp_afafai: f32 = clamp(1.0f, 1.0f, 1);
    var clamp_afafaf: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_afaff: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_affai: f32 = clamp(1.0f, 1.0f, 1);
    var clamp_affaf: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_afff: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_iaiai: i32 = clamp(1, 1, 1);
    var clamp_iaii: i32 = clamp(1, 1, 1);
    var clamp_iiai: i32 = clamp(1, 1, 1);
    var clamp_iii: i32 = clamp(1, 1, 1);
    var clamp_faiai: f32 = clamp(1.0f, 1, 1);
    var clamp_faiaf: f32 = clamp(1.0f, 1, 1.0f);
    var clamp_faif: f32 = clamp(1.0f, 1, 1.0f);
    var clamp_fafai: f32 = clamp(1.0f, 1.0f, 1);
    var clamp_fafaf: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_faff: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_ffai: f32 = clamp(1.0f, 1.0f, 1);
    var clamp_ffaf: f32 = clamp(1.0f, 1.0f, 1.0f);
    var clamp_fff: f32 = clamp(1.0f, 1.0f, 1.0f);
    var min_aiai: i32 = min(1, 1);
    var min_aiaf: f32 = min(1, 1.0f);
    var min_aii: i32 = min(1, 1);
    var min_aif: f32 = min(1, 1.0f);
    var min_afai: f32 = min(1.0f, 1);
    var min_afaf: f32 = min(1.0f, 1.0f);
    var min_aff: f32 = min(1.0f, 1.0f);
    var min_iai: i32 = min(1, 1);
    var min_ii: i32 = min(1, 1);
    var min_fai: f32 = min(1.0f, 1);
    var min_faf: f32 = min(1.0f, 1.0f);
    var min_ff: f32 = min(1.0f, 1.0f);
    var pow_aiai: i32 = pow(1, 1);
    var pow_aiaf: i32 = pow(1, 1.0f);
    var pow_aif: i32 = pow(1, 1.0f);
    var pow_afai: f32 = pow(1.0f, 1);
    var pow_afaf: f32 = pow(1.0f, 1.0f);
    var pow_aff: f32 = pow(1.0f, 1.0f);
    var pow_fai: f32 = pow(1.0f, 1);
    var pow_faf: f32 = pow(1.0f, 1.0f);
    var pow_ff: f32 = pow(1.0f, 1.0f);
}
