// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var t: texture_2d<f32>;
@group(0) @binding(1)
var s: sampler;
@group(0) @binding(2)
var d: texture_depth_2d;
@group(0) @binding(3)
var c: sampler_comparison;
@group(0) @binding(4)
var st: texture_storage_2d<rgba8unorm, read_write>;

fn color() {
    textureSample(t, s, vec2<f32>(1, 2));
    textureSample(t, s, vec2<f32>(1, 2), vec2<f32>(3, 4));
    textureSampleLevel(t, s, vec2<f32>(1, 2), 0);
    textureSampleLevel(t, s, vec2<f32>(1, 2), 0.0f);
    textureSampleGrad(t, s, vec2<f32>(1, 2), vec2<f32>(3, 4), vec2<f32>(5, 6));
    textureSampleBias(t, s, vec2<f32>(1, 2), 1);
}

fn depth() {
    textureSampleLevel(d, s, vec2<f32>(1, 2), 1);
    textureSampleCompare(d, c, vec2<f32>(1, 2), 0);
    textureGatherCompare(d, c, vec2<f32>(1, 2), 0);
}

fn storage() {
    textureStore(st, vec2<f32>(0, 1), vec4<f32>(2, 3, 4, 5));
}

@fragment
fn main() {
    color();
    depth();
    storage();
}
