// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: u32,
    b: vec3<u32>,
    c: i32,
}
struct Struct_4 {
    value: i32,
}
struct Struct_7 {
    m: mat3x2<f32>,
}
struct Struct_10 {
    am: array<mat4x2<f32>, 2>,
}
struct Struct_11 {
    x: u32,
}
struct Struct_12 {
    m: i32,
}
struct Struct_13 {
    delicious: i32,
}
struct Struct_22 {
    _matrix: mat4x3<f32>,
    matrix_array: array<mat2x2<f32>, 2>,
    atom: atomic<i32>,
    atom_arr: array<atomic<i32>, 10>,
    arr: array<vec2<u32>, 2>,
    data: array<Struct_4>,
}
struct Struct_23 {
    om_nom_nom: Struct_13,
    thing: u32,
}
@group(0) @binding(2)
var<storage, read_write> qux: vec2<i32>;
var<private> msl_padding_global_const: Struct_3 = Struct_3(0u, vec3<u32>(0u, 0u, 0u), 0);
@group(0) @binding(1)
var<uniform> baz: Struct_7;
@group(0) @binding(3)
var<uniform> nested_mat_cx2: Struct_10;
@group(0) @binding(0)
var<storage, read_write> bar: Struct_22;

fn read_from_private(foo: ptr<function, f32>) -> f32 {
    return foo;
}

fn test_arr_as_arg(a: array<array<f32, 10>, 5>) -> f32 {
    return a[4][9];
}

fn assign_through_ptr_fn(p: ptr<function, u32>) {
    p = 42u;
}

fn assign_array_through_ptr_fn(foo: ptr<function, array<vec4<f32>, 2>>) {
    foo = array<vec4<f32>, 2>(vec4<f32>(1.0f), vec4<f32>(2.0f));
}

fn fetch_arg_ptr_array_element(p: ptr<function, array<u32, 4>>) -> u32 {
    return p[1];
}

fn assign_to_arg_ptr_array_element(p: ptr<function, array<u32, 4>>) {
    p[1] = 10u;
}

fn index_ptr(value: bool) -> bool {
    var a: array<bool, 1> = array<bool, 1>(value);
    var p: ptr<function, array<bool, 1>> = &a;
    return p[0];
}

fn assign_through_ptr() {
    var val: u32 = 33u;
    assign_through_ptr_fn(&val);
    var arr: array<vec4<f32>, 2> = array<vec4<f32>, 2>(vec4<f32>(6.0f), vec4<f32>(7.0f));
    assign_array_through_ptr_fn(&arr);
}

fn fetch_arg_ptr_member(p: ptr<function, Struct_11>) -> u32 {
    return p.x;
}

fn assign_to_arg_ptr_member(p: ptr<function, Struct_11>) {
    p.x = 10u;
}

fn member_ptr() -> i32 {
    var s: Struct_12 = Struct_12(42);
    var p: ptr<function, Struct_12> = &s;
    return p[0];
}

fn test_matrix_within_struct_accesses() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l0: mat3x2<f32> = baz.m;
    var l1: vec2<f32> = baz.m[0];
    var l2: vec2<f32> = baz.m[idx];
    var l3: f32 = baz.m[0][1];
    var l4: f32 = baz.m[0][idx];
    var l5: f32 = baz.m[idx][1];
    var l6: f32 = baz.m[idx][idx];
    var t: Struct_7 = Struct_7(mat3x2<f32>(vec2<f32>(1.0f), vec2<f32>(2.0f), vec2<f32>(3.0f)));
    idx = (idx + 1);
    t.m = mat3x2<f32>(vec2<f32>(6.0f), vec2<f32>(5.0f), vec2<f32>(4.0f));
    t.m[0] = vec2<f32>(9.0f);
    t.m[idx] = vec2<f32>(90.0f);
    t.m[0][1] = 10.0f;
    t.m[0][idx] = 20.0f;
    t.m[idx][1] = 30.0f;
    t.m[idx][idx] = 40.0f;
}

fn test_matrix_within_array_within_struct_accesses() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l0: array<mat4x2<f32>, 2> = nested_mat_cx2.am;
    var l1: mat4x2<f32> = nested_mat_cx2.am[0];
    var l2: vec2<f32> = nested_mat_cx2.am[0][0];
    var l3: vec2<f32> = nested_mat_cx2.am[0][idx];
    var l4: f32 = nested_mat_cx2.am[0][0][1];
    var l5: f32 = nested_mat_cx2.am[0][0][idx];
    var l6: f32 = nested_mat_cx2.am[0][idx][1];
    var l7: f32 = nested_mat_cx2.am[0][idx][idx];
    var t: Struct_10 = Struct_10(array<mat4x2<f32>, 2>());
    idx = (idx + 1);
    t.am = array<mat4x2<f32>, 2>();
    t.am[0] = mat4x2<f32>(vec2<f32>(8.0f), vec2<f32>(7.0f), vec2<f32>(6.0f), vec2<f32>(5.0f));
    t.am[0][0] = vec2<f32>(9.0f);
    t.am[0][idx] = vec2<f32>(90.0f);
    t.am[0][0][1] = 10.0f;
    t.am[0][0][idx] = 20.0f;
    t.am[0][idx][1] = 30.0f;
    t.am[0][idx][idx] = 40.0f;
}

fn assign_to_ptr_components() {
    var s1: Struct_11;
    assign_to_arg_ptr_member(&s1);
    fetch_arg_ptr_member(&s1);
    var a1: array<u32, 4>;
    assign_to_arg_ptr_array_element(&a1);
    fetch_arg_ptr_array_element(&a1);
}

fn let_members_of_members() -> i32 {
    var thing: Struct_23 = Struct_23();
    var inner: Struct_13 = thing.om_nom_nom;
    var delishus: i32 = inner.delicious;
    if ((thing.thing != u32(delishus))) {
    }
    return thing.om_nom_nom.delicious;
}

fn var_members_of_members() -> i32 {
    var thing: Struct_23 = Struct_23();
    var inner: Struct_13 = thing.om_nom_nom;
    var delishus: i32 = inner.delicious;
    if ((thing.thing != u32(delishus))) {
    }
    return thing.om_nom_nom.delicious;
}

@fragment
fn foo_frag() -> vec4<f32> {
    bar._matrix[1][2] = 1.0f;
    bar._matrix = mat4x3<f32>(vec3<f32>(0.0f), vec3<f32>(1.0f), vec3<f32>(2.0f), vec3<f32>(3.0f));
    bar.arr = array<vec2<u32>, 2>(vec2<u32>(0u), vec2<u32>(1u));
    bar.data[1].value = 1;
    qux = vec2<i32>();
    return vec4<f32>(0.0f);
}

@vertex
fn foo_vert(@builtin(vertex_index) vi: u32) -> vec4<f32> {
    var foo: f32 = 0.0f;
    var baz: f32 = foo;
    foo = 1.0f;
    _ = msl_padding_global_const;
    test_matrix_within_struct_accesses();
    test_matrix_within_array_within_struct_accesses();
    var _matrix: mat4x3<f32> = bar._matrix;
    var arr: array<vec2<u32>, 2> = bar.arr;
    var index: u32 = 3u;
    var b: f32 = bar._matrix[index][0];
    var a: i32 = bar.data[(arrayLength(&bar.data) - 2u)].value;
    var c: vec2<i32> = qux;
    var data_pointer: ptr<storage, i32, read_write> = &bar.data[0].value;
    var foo_value: f32 = read_from_private(&foo);
    var c2: array<i32, 5> = array<i32, 5>(a, i32(b), 3, 4, 5);
    c2[(vi + 1u)] = 42;
    var value: i32 = c2[vi];
    test_arr_as_arg(array<array<f32, 10>, 5>());
    return vec4<f32>((_matrix * vec4<f32>(vec4<i32>(value))), 2.0f);
}

@compute
@workgroup_size(1, 1, 1)
fn foo_compute() {
    assign_through_ptr();
    assign_to_ptr_components();
    index_ptr(true);
    member_ptr();
    let_members_of_members();
    var_members_of_members();
}
