// Generated by WebGPU-KTypes WGSL Backend
struct Struct_10 {
    kind: u32,
    t: f32,
    instance_custom_data: u32,
    instance_index: u32,
    sbt_record_offset: u32,
    geometry_index: u32,
    primitive_index: u32,
    barycentrics: vec2<f32>,
    front_face: bool,
    object_to_world: mat4x3<f32>,
    world_to_object: mat4x3<f32>,
}
@group(0) @binding(0)
var<private> acc_struct: acceleration_structure;

fn RayDesc(arg_0: u32, arg_1: i32, arg_2: f32, arg_3: f32, arg_4: vec3<f32>, arg_5: vec3<f32>) -> u32 {
}

fn rayQueryInitialize(arg_0: ptr<function, ray_query>, arg_1: acceleration_structure, arg_2: u32) -> ptr<function, ray_query> {
}

fn rayQueryGetCandidateIntersection(arg_0: ptr<function, ray_query>) -> Struct_10 {
}

fn rayQueryGenerateIntersection(arg_0: ptr<function, ray_query>, arg_1: f32) {
}

fn rayQueryConfirmIntersection(arg_0: ptr<function, ray_query>) {
}

fn rayQueryTerminate(arg_0: ptr<function, ray_query>) {
}

@compute
@workgroup_size(1, 1, 1)
fn main_candidate() {
    var pos: vec3<f32> = vec3<f32>(0.0f);
    var dir: vec3<f32> = vec3<f32>(0.0f, 1.0f, 0.0f);
    var rq: ray_query;
    rayQueryInitialize(&rq, acc_struct, RayDesc(4u, 0, 0.1f, 100.0f, pos, dir));
    var intersection: Struct_10 = rayQueryGetCandidateIntersection(&rq);
    if ((intersection.kind == 3u)) {
        rayQueryGenerateIntersection(&rq, 10.0f);
    } else {
        if ((intersection.kind == 1u)) {
            rayQueryConfirmIntersection(&rq);
        } else {
            rayQueryTerminate(&rq);
        }
    }
}
