// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    inner: array<f32, 2>,
}
@group(0) @binding(0)
var<storage> ah: Struct_2;

@compute
@workgroup_size(1, 1, 1)
fn cs_main() {
    var ah: Struct_2 = ah;
}
