// Generated by WebGPU-KTypes WGSL Backend

fn ret_array() -> array<f32, 2> {
    return array<f32, 2>(1.0f, 2.0f);
}

fn ret_array_array() -> array<array<f32, 2>, 3> {
    return array<array<f32, 2>, 3>(ret_array(), ret_array(), ret_array());
}

@fragment
fn main() -> vec4<f32> {
    var a: array<array<f32, 2>, 3> = ret_array_array();
    return vec4<f32>(a[0][0], a[0][1], 0.0f, 1.0f);
}
