// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var image_u: texture_storage_2d<r32uint, atomic>;
@group(0) @binding(1)
var image_s: texture_storage_2d<r32sint, atomic>;

@compute
@workgroup_size(2, 1, 1)
fn cs_main(@builtin(local_invocation_id) id: vec3<u32>) {
    textureAtomicMax(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicMin(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicAdd(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicAnd(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicOr(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicXor(image_u, vec2<i32>(0, 0), 1u);
    textureAtomicMax(image_s, vec2<i32>(0, 0), 1);
    textureAtomicMin(image_s, vec2<i32>(0, 0), 1);
    textureAtomicAdd(image_s, vec2<i32>(0, 0), 1);
    textureAtomicAnd(image_s, vec2<i32>(0, 0), 1);
    textureAtomicOr(image_s, vec2<i32>(0, 0), 1);
    textureAtomicXor(image_s, vec2<i32>(0, 0), 1);
}
