// Generated by WebGPU-KTypes WGSL Backend
struct Struct_9 {
    old_value: i32,
    exchanged: bool,
}
struct Struct_11 {
    old_value: u32,
    exchanged: bool,
}
const SIZE: u32 = 128u;
@group(0) @binding(0)
var<storage, read_write> arr_i32: array<atomic<i32>, 128>;
@group(0) @binding(1)
var<storage, read_write> arr_u32: array<atomic<u32>, 128>;

@compute
@workgroup_size(1, 1, 1)
fn test_atomic_compare_exchange_i32() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: i32 = atomicLoad(&arr_i32[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: i32 = bitcast<i32>((bitcast<f32>(old) + 1.0f));
                            var result: Struct_9 = atomicCompareExchangeWeak(&arr_i32[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn test_atomic_compare_exchange_u32() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: u32 = atomicLoad(&arr_u32[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: u32 = bitcast<u32>((bitcast<f32>(old) + 1.0f));
                            var result: Struct_11 = atomicCompareExchangeWeak(&arr_u32[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}
