// Generated by WebGPU-KTypes WGSL Backend
struct Struct_5 {
    atomic_scalar: atomic<u32>,
    atomic_arr: array<atomic<i32>, 2>,
}
struct Struct_12 {
    old_value: u32,
    exchanged: bool,
}
struct Struct_13 {
    old_value: i32,
    exchanged: bool,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: atomic<u32>;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<atomic<i32>, 2>;
var<workgroup> workgroup_atomic_scalar: atomic<u32>;
var<workgroup> workgroup_atomic_arr: array<atomic<i32>, 2>;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_5;
var<workgroup> workgroup_struct: Struct_5;

@compute
@workgroup_size(2, 1, 1)
fn cs_main(@builtin(local_invocation_id) id: vec3<u32>) {
    atomicStore(&storage_atomic_scalar, 1u);
    atomicStore(&storage_atomic_arr[1], 1);
    atomicStore(&storage_struct.atomic_scalar, 1u);
    atomicStore(&storage_struct.atomic_arr[1], 1);
    atomicStore(&workgroup_atomic_scalar, 1u);
    atomicStore(&workgroup_atomic_arr[1], 1);
    atomicStore(&workgroup_struct.atomic_scalar, 1u);
    atomicStore(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    var l0: u32 = atomicLoad(&storage_atomic_scalar);
    var l1: i32 = atomicLoad(&storage_atomic_arr[1]);
    var l2: u32 = atomicLoad(&storage_struct.atomic_scalar);
    var l3: i32 = atomicLoad(&storage_struct.atomic_arr[1]);
    var l4: u32 = atomicLoad(&workgroup_atomic_scalar);
    var l5: i32 = atomicLoad(&workgroup_atomic_arr[1]);
    var l6: u32 = atomicLoad(&workgroup_struct.atomic_scalar);
    var l7: i32 = atomicLoad(&workgroup_struct.atomic_arr[1]);
    workgroupBarrier();
    atomicAdd(&storage_atomic_scalar, 1u);
    atomicAdd(&storage_atomic_arr[1], 1);
    atomicAdd(&storage_struct.atomic_scalar, 1u);
    atomicAdd(&storage_struct.atomic_arr[1], 1);
    atomicAdd(&workgroup_atomic_scalar, 1u);
    atomicAdd(&workgroup_atomic_arr[1], 1);
    atomicAdd(&workgroup_struct.atomic_scalar, 1u);
    atomicAdd(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicSub(&storage_atomic_scalar, 1u);
    atomicSub(&storage_atomic_arr[1], 1);
    atomicSub(&storage_struct.atomic_scalar, 1u);
    atomicSub(&storage_struct.atomic_arr[1], 1);
    atomicSub(&workgroup_atomic_scalar, 1u);
    atomicSub(&workgroup_atomic_arr[1], 1);
    atomicSub(&workgroup_struct.atomic_scalar, 1u);
    atomicSub(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicMax(&storage_atomic_scalar, 1u);
    atomicMax(&storage_atomic_arr[1], 1);
    atomicMax(&storage_struct.atomic_scalar, 1u);
    atomicMax(&storage_struct.atomic_arr[1], 1);
    atomicMax(&workgroup_atomic_scalar, 1u);
    atomicMax(&workgroup_atomic_arr[1], 1);
    atomicMax(&workgroup_struct.atomic_scalar, 1u);
    atomicMax(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicMin(&storage_atomic_scalar, 1u);
    atomicMin(&storage_atomic_arr[1], 1);
    atomicMin(&storage_struct.atomic_scalar, 1u);
    atomicMin(&storage_struct.atomic_arr[1], 1);
    atomicMin(&workgroup_atomic_scalar, 1u);
    atomicMin(&workgroup_atomic_arr[1], 1);
    atomicMin(&workgroup_struct.atomic_scalar, 1u);
    atomicMin(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicAnd(&storage_atomic_scalar, 1u);
    atomicAnd(&storage_atomic_arr[1], 1);
    atomicAnd(&storage_struct.atomic_scalar, 1u);
    atomicAnd(&storage_struct.atomic_arr[1], 1);
    atomicAnd(&workgroup_atomic_scalar, 1u);
    atomicAnd(&workgroup_atomic_arr[1], 1);
    atomicAnd(&workgroup_struct.atomic_scalar, 1u);
    atomicAnd(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicOr(&storage_atomic_scalar, 1u);
    atomicOr(&storage_atomic_arr[1], 1);
    atomicOr(&storage_struct.atomic_scalar, 1u);
    atomicOr(&storage_struct.atomic_arr[1], 1);
    atomicOr(&workgroup_atomic_scalar, 1u);
    atomicOr(&workgroup_atomic_arr[1], 1);
    atomicOr(&workgroup_struct.atomic_scalar, 1u);
    atomicOr(&workgroup_struct.atomic_arr[1], 1);
    workgroupBarrier();
    atomicXor(&storage_atomic_scalar, 1u);
    atomicXor(&storage_atomic_arr[1], 1);
    atomicXor(&storage_struct.atomic_scalar, 1u);
    atomicXor(&storage_struct.atomic_arr[1], 1);
    atomicXor(&workgroup_atomic_scalar, 1u);
    atomicXor(&workgroup_atomic_arr[1], 1);
    atomicXor(&workgroup_struct.atomic_scalar, 1u);
    atomicXor(&workgroup_struct.atomic_arr[1], 1);
    atomicExchange(&storage_atomic_scalar, 1u);
    atomicExchange(&storage_atomic_arr[1], 1);
    atomicExchange(&storage_struct.atomic_scalar, 1u);
    atomicExchange(&storage_struct.atomic_arr[1], 1);
    atomicExchange(&workgroup_atomic_scalar, 1u);
    atomicExchange(&workgroup_atomic_arr[1], 1);
    atomicExchange(&workgroup_struct.atomic_scalar, 1u);
    atomicExchange(&workgroup_struct.atomic_arr[1], 1);
    var cas_res_0: Struct_12 = atomicCompareExchangeWeak(&storage_atomic_scalar, 1u, 2u);
    var cas_res_1: Struct_13 = atomicCompareExchangeWeak(&storage_atomic_arr[1], 1, 2);
    var cas_res_2: Struct_12 = atomicCompareExchangeWeak(&storage_struct.atomic_scalar, 1u, 2u);
    var cas_res_3: Struct_13 = atomicCompareExchangeWeak(&storage_struct.atomic_arr[1], 1, 2);
    var cas_res_4: Struct_12 = atomicCompareExchangeWeak(&workgroup_atomic_scalar, 1u, 2u);
    var cas_res_5: Struct_13 = atomicCompareExchangeWeak(&workgroup_atomic_arr[1], 1, 2);
    var cas_res_6: Struct_12 = atomicCompareExchangeWeak(&workgroup_struct.atomic_scalar, 1u, 2u);
    var cas_res_7: Struct_13 = atomicCompareExchangeWeak(&workgroup_struct.atomic_arr[1], 1, 2);
}
