// Generated by WebGPU-KTypes WGSL Backend
struct Struct_5 {
    atomic_scalar: atomic<u64>,
    atomic_arr: array<atomic<i64>, 2>,
}
struct Struct_13 {
    old_value: u64,
    exchanged: bool,
}
struct Struct_14 {
    old_value: i64,
    exchanged: bool,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: atomic<u64>;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<atomic<i64>, 2>;
var<workgroup> workgroup_atomic_scalar: atomic<u64>;
var<workgroup> workgroup_atomic_arr: array<atomic<i64>, 2>;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_5;
var<workgroup> workgroup_struct: Struct_5;

@compute
@workgroup_size(2, 1, 1)
fn cs_main(@builtin(local_invocation_id) id: vec3<u32>) {
    atomicStore(&storage_atomic_scalar, 1lu);
    atomicStore(&storage_atomic_arr[1], 1li);
    atomicStore(&storage_struct.atomic_scalar, 1lu);
    atomicStore(&storage_struct.atomic_arr[1], 1li);
    atomicStore(&workgroup_atomic_scalar, 1lu);
    atomicStore(&workgroup_atomic_arr[1], 1li);
    atomicStore(&workgroup_struct.atomic_scalar, 1lu);
    atomicStore(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    var l0: u64 = atomicLoad(&storage_atomic_scalar);
    var l1: i64 = atomicLoad(&storage_atomic_arr[1]);
    var l2: u64 = atomicLoad(&storage_struct.atomic_scalar);
    var l3: i64 = atomicLoad(&storage_struct.atomic_arr[1]);
    var l4: u64 = atomicLoad(&workgroup_atomic_scalar);
    var l5: i64 = atomicLoad(&workgroup_atomic_arr[1]);
    var l6: u64 = atomicLoad(&workgroup_struct.atomic_scalar);
    var l7: i64 = atomicLoad(&workgroup_struct.atomic_arr[1]);
    workgroupBarrier();
    atomicAdd(&storage_atomic_scalar, 1lu);
    atomicAdd(&storage_atomic_arr[1], 1li);
    atomicAdd(&storage_struct.atomic_scalar, 1lu);
    atomicAdd(&storage_struct.atomic_arr[1], 1li);
    atomicAdd(&workgroup_atomic_scalar, 1lu);
    atomicAdd(&workgroup_atomic_arr[1], 1li);
    atomicAdd(&workgroup_struct.atomic_scalar, 1lu);
    atomicAdd(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicSub(&storage_atomic_scalar, 1lu);
    atomicSub(&storage_atomic_arr[1], 1li);
    atomicSub(&storage_struct.atomic_scalar, 1lu);
    atomicSub(&storage_struct.atomic_arr[1], 1li);
    atomicSub(&workgroup_atomic_scalar, 1lu);
    atomicSub(&workgroup_atomic_arr[1], 1li);
    atomicSub(&workgroup_struct.atomic_scalar, 1lu);
    atomicSub(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicMax(&storage_atomic_scalar, 1lu);
    atomicMax(&storage_atomic_arr[1], 1li);
    atomicMax(&storage_struct.atomic_scalar, 1lu);
    atomicMax(&storage_struct.atomic_arr[1], 1li);
    atomicMax(&workgroup_atomic_scalar, 1lu);
    atomicMax(&workgroup_atomic_arr[1], 1li);
    atomicMax(&workgroup_struct.atomic_scalar, 1lu);
    atomicMax(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicMin(&storage_atomic_scalar, 1lu);
    atomicMin(&storage_atomic_arr[1], 1li);
    atomicMin(&storage_struct.atomic_scalar, 1lu);
    atomicMin(&storage_struct.atomic_arr[1], 1li);
    atomicMin(&workgroup_atomic_scalar, 1lu);
    atomicMin(&workgroup_atomic_arr[1], 1li);
    atomicMin(&workgroup_struct.atomic_scalar, 1lu);
    atomicMin(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicAnd(&storage_atomic_scalar, 1lu);
    atomicAnd(&storage_atomic_arr[1], 1li);
    atomicAnd(&storage_struct.atomic_scalar, 1lu);
    atomicAnd(&storage_struct.atomic_arr[1], 1li);
    atomicAnd(&workgroup_atomic_scalar, 1lu);
    atomicAnd(&workgroup_atomic_arr[1], 1li);
    atomicAnd(&workgroup_struct.atomic_scalar, 1lu);
    atomicAnd(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicOr(&storage_atomic_scalar, 1lu);
    atomicOr(&storage_atomic_arr[1], 1li);
    atomicOr(&storage_struct.atomic_scalar, 1lu);
    atomicOr(&storage_struct.atomic_arr[1], 1li);
    atomicOr(&workgroup_atomic_scalar, 1lu);
    atomicOr(&workgroup_atomic_arr[1], 1li);
    atomicOr(&workgroup_struct.atomic_scalar, 1lu);
    atomicOr(&workgroup_struct.atomic_arr[1], 1li);
    workgroupBarrier();
    atomicXor(&storage_atomic_scalar, 1lu);
    atomicXor(&storage_atomic_arr[1], 1li);
    atomicXor(&storage_struct.atomic_scalar, 1lu);
    atomicXor(&storage_struct.atomic_arr[1], 1li);
    atomicXor(&workgroup_atomic_scalar, 1lu);
    atomicXor(&workgroup_atomic_arr[1], 1li);
    atomicXor(&workgroup_struct.atomic_scalar, 1lu);
    atomicXor(&workgroup_struct.atomic_arr[1], 1li);
    atomicExchange(&storage_atomic_scalar, 1lu);
    atomicExchange(&storage_atomic_arr[1], 1li);
    atomicExchange(&storage_struct.atomic_scalar, 1lu);
    atomicExchange(&storage_struct.atomic_arr[1], 1li);
    atomicExchange(&workgroup_atomic_scalar, 1lu);
    atomicExchange(&workgroup_atomic_arr[1], 1li);
    atomicExchange(&workgroup_struct.atomic_scalar, 1lu);
    atomicExchange(&workgroup_struct.atomic_arr[1], 1li);
    var cas_res_0: Struct_13 = atomicCompareExchangeWeak(&storage_atomic_scalar, 1lu, 2lu);
    var cas_res_1: Struct_14 = atomicCompareExchangeWeak(&storage_atomic_arr[1], 1li, 2li);
    var cas_res_2: Struct_13 = atomicCompareExchangeWeak(&storage_struct.atomic_scalar, 1lu, 2lu);
    var cas_res_3: Struct_14 = atomicCompareExchangeWeak(&storage_struct.atomic_arr[1], 1li, 2li);
    var cas_res_4: Struct_13 = atomicCompareExchangeWeak(&workgroup_atomic_scalar, 1lu, 2lu);
    var cas_res_5: Struct_14 = atomicCompareExchangeWeak(&workgroup_atomic_arr[1], 1li, 2li);
    var cas_res_6: Struct_13 = atomicCompareExchangeWeak(&workgroup_struct.atomic_scalar, 1lu, 2lu);
    var cas_res_7: Struct_14 = atomicCompareExchangeWeak(&workgroup_struct.atomic_arr[1], 1li, 2li);
}
