// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    atomic_scalar: atomic<f32>,
    atomic_arr: array<atomic<f32>, 2>,
}
@group(0) @binding(0)
var<storage, read_write> storage_atomic_scalar: atomic<f32>;
@group(0) @binding(1)
var<storage, read_write> storage_atomic_arr: array<atomic<f32>, 2>;
@group(0) @binding(2)
var<storage, read_write> storage_struct: Struct_3;

@compute
@workgroup_size(2, 1, 1)
fn cs_main(@builtin(local_invocation_id) id: vec3<u32>) {
    atomicStore(&storage_atomic_scalar, 1.5f);
    atomicStore(&storage_atomic_arr[1], 1.5f);
    atomicStore(&storage_struct.atomic_scalar, 1.5f);
    atomicStore(&storage_struct.atomic_arr[1], 1.5f);
    workgroupBarrier();
    var l0: f32 = atomicLoad(&storage_atomic_scalar);
    var l1: f32 = atomicLoad(&storage_atomic_arr[1]);
    var l2: f32 = atomicLoad(&storage_struct.atomic_scalar);
    var l3: f32 = atomicLoad(&storage_struct.atomic_arr[1]);
    workgroupBarrier();
    atomicAdd(&storage_atomic_scalar, 1.5f);
    atomicAdd(&storage_atomic_arr[1], 1.5f);
    atomicAdd(&storage_struct.atomic_scalar, 1.5f);
    atomicAdd(&storage_struct.atomic_arr[1], 1.5f);
    workgroupBarrier();
    atomicExchange(&storage_atomic_scalar, 1.5f);
    atomicExchange(&storage_atomic_arr[1], 1.5f);
    atomicExchange(&storage_struct.atomic_scalar, 1.5f);
    atomicExchange(&storage_struct.atomic_arr[1], 1.5f);
}
