// Generated by WebGPU-KTypes WGSL Backend
struct Struct_9 {
    old_value: i64,
    exchanged: bool,
}
struct Struct_11 {
    old_value: u64,
    exchanged: bool,
}
const SIZE: u32 = 128u;
@group(0) @binding(0)
var<storage, read_write> arr_i64: array<atomic<i64>, 128>;
@group(0) @binding(1)
var<storage, read_write> arr_u64: array<atomic<u64>, 128>;

@compute
@workgroup_size(1, 1, 1)
fn test_atomic_compare_exchange_i64() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: i64 = atomicLoad(&arr_i64[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: i64 = bitcast<i64>((old + 10li));
                            var result: Struct_9 = atomicCompareExchangeWeak(&arr_i64[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn test_atomic_compare_exchange_u64() {
    {
        var i: u32 = 0u;
        loop {
            if ((i < SIZE)) {
                {
                    var old: u64 = atomicLoad(&arr_u64[i]);
                    var exchanged: bool = false;
                    loop {
                        if (!(exchanged)) {
                            var new_: u64 = bitcast<u64>((old + 10lu));
                            var result: Struct_11 = atomicCompareExchangeWeak(&arr_u64[i], old, new_);
                            old = result.old_value;
                            exchanged = result.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
}
