// Generated by WebGPU-KTypes WGSL Backend

@fragment
fn fs_main(bary: vec3<f32>) -> vec4<f32> {
    return vec4<f32>(bary, 1.0f);
}

@fragment
fn fs_main_no_perspective(bary: vec3<f32>) -> vec4<f32> {
    return vec4<f32>(bary, 1.0f);
}
