// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    index: u32,
}
struct Struct_2 {
    index: u32,
}
@group(0) @binding(0)
var<private> texture_array_unbounded: array<texture_2d<f32>>;
@group(0) @binding(1)
var<private> texture_array_bounded: array<texture_2d<f32>, 5>;
@group(0) @binding(2)
var<private> texture_array_2darray: array<texture_2d_array<f32>, 5>;
@group(0) @binding(3)
var<private> texture_array_multisampled: array<texture_multisampled_2d<f32>, 5>;
@group(0) @binding(4)
var<private> texture_array_depth: array<texture_depth_2d, 5>;
@group(0) @binding(5)
var<private> texture_array_storage: array<texture_storage_2d<rgba32float, write>, 5>;
@group(0) @binding(6)
var<private> samp: array<sampler, 5>;
@group(0) @binding(7)
var<private> samp_comp: array<sampler_comparison, 5>;
@group(0) @binding(8)
var<uniform> uni: Struct_1;

@fragment
fn main(fragment_in: Struct_2) -> vec4<f32> {
    var uniform_index: u32 = uni.index;
    var non_uniform_index: u32 = fragment_in.index;
    var u1: u32 = 0u;
    var u2: vec2<u32> = vec2<u32>(0u);
    var v1: f32 = 0.0f;
    var v4: vec4<f32> = vec4<f32>(0.0f);
    var uv: vec2<f32> = vec2<f32>(0.0f);
    var pix: vec2<i32> = vec2<i32>(0);
    u2 = textureDimensions(texture_array_unbounded[0]);
    u2 = textureDimensions(texture_array_unbounded[uniform_index]);
    u2 = textureDimensions(texture_array_unbounded[non_uniform_index]);
    v4 = textureGather(0, texture_array_bounded[0], samp[0], uv);
    v4 = textureGather(0, texture_array_bounded[uniform_index], samp[uniform_index], uv);
    v4 = textureGather(0, texture_array_bounded[non_uniform_index], samp[non_uniform_index], uv);
    v4 = textureGatherCompare(texture_array_depth[0], samp_comp[0], uv, 0.0f);
    v4 = textureGatherCompare(texture_array_depth[uniform_index], samp_comp[uniform_index], uv, 0.0f);
    v4 = textureGatherCompare(texture_array_depth[non_uniform_index], samp_comp[non_uniform_index], uv, 0.0f);
    v4 = textureLoad(texture_array_unbounded[0], pix, 0);
    v4 = textureLoad(texture_array_unbounded[uniform_index], pix, 0);
    v4 = textureLoad(texture_array_unbounded[non_uniform_index], pix, 0);
    u1 = textureNumLayers(texture_array_2darray[0]);
    u1 = textureNumLayers(texture_array_2darray[uniform_index]);
    u1 = textureNumLayers(texture_array_2darray[non_uniform_index]);
    u1 = textureNumLevels(texture_array_bounded[0]);
    u1 = textureNumLevels(texture_array_bounded[uniform_index]);
    u1 = textureNumLevels(texture_array_bounded[non_uniform_index]);
    u1 = textureNumSamples(texture_array_multisampled[0]);
    u1 = textureNumSamples(texture_array_multisampled[uniform_index]);
    u1 = textureNumSamples(texture_array_multisampled[non_uniform_index]);
    v4 = textureSample(texture_array_bounded[0], samp[0], uv);
    v4 = textureSample(texture_array_bounded[uniform_index], samp[uniform_index], uv);
    v4 = textureSample(texture_array_bounded[non_uniform_index], samp[non_uniform_index], uv);
    v4 = textureSampleBias(texture_array_bounded[0], samp[0], uv, 0.0f);
    v4 = textureSampleBias(texture_array_bounded[uniform_index], samp[uniform_index], uv, 0.0f);
    v4 = textureSampleBias(texture_array_bounded[non_uniform_index], samp[non_uniform_index], uv, 0.0f);
    v1 = textureSampleCompare(texture_array_depth[0], samp_comp[0], uv, 0.0f);
    v1 = textureSampleCompare(texture_array_depth[uniform_index], samp_comp[uniform_index], uv, 0.0f);
    v1 = textureSampleCompare(texture_array_depth[non_uniform_index], samp_comp[non_uniform_index], uv, 0.0f);
    v1 = textureSampleCompareLevel(texture_array_depth[0], samp_comp[0], uv, 0.0f);
    v1 = textureSampleCompareLevel(texture_array_depth[uniform_index], samp_comp[uniform_index], uv, 0.0f);
    v1 = textureSampleCompareLevel(texture_array_depth[non_uniform_index], samp_comp[non_uniform_index], uv, 0.0f);
    v4 = textureSampleGrad(texture_array_bounded[0], samp[0], uv, uv, uv);
    v4 = textureSampleGrad(texture_array_bounded[uniform_index], samp[uniform_index], uv, uv, uv);
    v4 = textureSampleGrad(texture_array_bounded[non_uniform_index], samp[non_uniform_index], uv, uv, uv);
    v4 = textureSampleLevel(texture_array_bounded[0], samp[0], uv, 0.0f);
    v4 = textureSampleLevel(texture_array_bounded[uniform_index], samp[uniform_index], uv, 0.0f);
    v4 = textureSampleLevel(texture_array_bounded[non_uniform_index], samp[non_uniform_index], uv, 0.0f);
    textureStore(texture_array_storage[0], pix, v4);
    textureStore(texture_array_storage[uniform_index], pix, v4);
    textureStore(texture_array_storage[non_uniform_index], pix, v4);
    var v2: vec2<f32> = vec2<f32>((u2 + vec2<u32>(u1)));
    return ((v4 + vec4<f32>(v2[0], v2[1], v2[0], v2[1])) + v1);
}
