// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    index: u32,
}
struct Struct_4 {
    x: u32,
    far: array<i32>,
}
struct Struct_5 {
    index: u32,
}
@group(0) @binding(10)
var<uniform> uni: Struct_1;
@group(0) @binding(0)
var<storage, read> storage_array: array<Struct_4, 1>;

@fragment
fn main(fragment_in: Struct_5) -> u32 {
    var uniform_index: u32 = uni.index;
    var non_uniform_index: u32 = fragment_in.index;
    var u1: u32 = 0u;
    u1 = storage_array[0].x;
    u1 = storage_array[uniform_index].x;
    u1 = storage_array[non_uniform_index].x;
    u1 = arrayLength(&storage_array[0].far);
    u1 = arrayLength(&storage_array[uniform_index].far);
    u1 = arrayLength(&storage_array[non_uniform_index].far);
    return u1;
}
