// Generated by WebGPU-KTypes WGSL Backend

fn pack4xI8(arg_0: vec4<i32>) -> vec4<i32> {
}

fn pack4xU8(arg_0: vec4<u32>) -> vec4<u32> {
}

@fragment
fn main() {
    var i: i32 = 0;
    var i2: vec2<i32> = vec2<i32>(0);
    var i3: vec3<i32> = vec3<i32>(0);
    var i4: vec4<i32> = vec4<i32>(0);
    var u: u32 = 0u;
    var u2: vec2<u32> = vec2<u32>(0u);
    var u3: vec3<u32> = vec3<u32>(0u);
    var u4: vec4<u32> = vec4<u32>(0u);
    var f2: vec2<f32> = vec2<f32>(0.0f);
    var f4: vec4<f32> = vec4<f32>(0.0f);
    u = pack4xI8(i4);
    u = pack4xU8(u4);
    f4 = unpack4x8snorm(u);
    f4 = unpack4x8unorm(u);
    f2 = unpack2x16snorm(u);
    f2 = unpack2x16unorm(u);
}
