// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    pos: vec2<f32>,
    vel: vec2<f32>,
}
struct Struct_3 {
    deltaT: f32,
    rule1Distance: f32,
    rule2Distance: f32,
    rule3Distance: f32,
    rule1Scale: f32,
    rule2Scale: f32,
    rule3Scale: f32,
}
struct Struct_5 {
    particles: array<Struct_2>,
}
const NUM_PARTICLES: u32 = 1500u;
@group(0) @binding(0)
var<uniform> params: Struct_3;
@group(0) @binding(1)
var<storage> particlesSrc: Struct_5;
@group(0) @binding(2)
var<storage, read_write> particlesDst: Struct_5;

@compute
@workgroup_size(64, 1, 1)
fn main(@builtin(global_invocation_id) global_invocation_id: vec3<u32>) {
    var index: u32 = global_invocation_id[0];
    if ((index >= NUM_PARTICLES)) {
        return;
    }
    var vPos: vec2<f32> = particlesSrc.particles[index].pos;
    var vVel: vec2<f32> = particlesSrc.particles[index].vel;
    var cMass: vec2<f32> = vec2<f32>(0.0f, 0.0f);
    var cVel: vec2<f32> = vec2<f32>(0.0f, 0.0f);
    var colVel: vec2<f32> = vec2<f32>(0.0f, 0.0f);
    var cMassCount: i32 = 0;
    var cVelCount: i32 = 0;
    var pos: vec2<f32>;
    var vel: vec2<f32>;
    var i: u32 = 0u;
    loop {
        if ((i >= NUM_PARTICLES)) {
            break;
        }
        if ((i == index)) {
            continue;
        }
        pos = particlesSrc.particles[i].pos;
        vel = particlesSrc.particles[i].vel;
        if ((distance(pos, vPos) < params.rule1Distance)) {
            cMass = (cMass + pos);
            cMassCount = (cMassCount + 1);
        }
        if ((distance(pos, vPos) < params.rule2Distance)) {
            colVel = (colVel - (pos - vPos));
        }
        if ((distance(pos, vPos) < params.rule3Distance)) {
            cVel = (cVel + vel);
            cVelCount = (cVelCount + 1);
        }
        continuing {
            i = (i + 1u);
        }
    }
    if ((cMassCount > 0)) {
        cMass = ((cMass / f32(cMassCount)) - vPos);
    }
    if ((cVelCount > 0)) {
        cVel = (cVel / f32(cVelCount));
    }
    vVel = (((vVel + (cMass * params.rule1Scale)) + (colVel * params.rule2Scale)) + (cVel * params.rule3Scale));
    vVel = (normalize(vVel) * clamp(length(vVel), 0.0f, 0.1f));
    vPos = (vPos + (vVel * params.deltaT));
    if ((vPos[0] < -(1.0f))) {
        vPos[0] = 1.0f;
    }
    if ((vPos[0] > 1.0f)) {
        vPos[0] = -(1.0f);
    }
    if ((vPos[1] < -(1.0f))) {
        vPos[1] = 1.0f;
    }
    if ((vPos[1] > 1.0f)) {
        vPos[1] = -(1.0f);
    }
    particlesDst.particles[index].pos = vPos;
    particlesDst.particles[index].vel = vVel;
}
