// Generated by WebGPU-KTypes WGSL Backend
struct Struct_4 {
    a: atomic<u32>,
    b: array<atomic<u32>, 10>,
    c: array<atomic<u32>>,
}
@group(0) @binding(0)
var<storage, read_write> globals: Struct_4;

fn fetch_add_atomic() -> u32 {
    return atomicAdd(&globals.a, 1u);
}

fn fetch_add_atomic_static_sized_array(i: i32) -> u32 {
    return atomicAdd(&globals.b[i], 1u);
}

fn fetch_add_atomic_dynamic_sized_array(i: i32) -> u32 {
    return atomicAdd(&globals.c[i], 1u);
}

fn exchange_atomic() -> u32 {
    return atomicExchange(&globals.a, 1u);
}

fn exchange_atomic_static_sized_array(i: i32) -> u32 {
    return atomicExchange(&globals.b[i], 1u);
}

fn exchange_atomic_dynamic_sized_array(i: i32) -> u32 {
    return atomicExchange(&globals.c[i], 1u);
}

fn fetch_add_atomic_dynamic_sized_array_static_index() -> u32 {
    return atomicAdd(&globals.c[1000], 1u);
}

fn exchange_atomic_dynamic_sized_array_static_index() -> u32 {
    return atomicExchange(&globals.c[1000], 1u);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    fetch_add_atomic();
    fetch_add_atomic_static_sized_array(1);
    fetch_add_atomic_dynamic_sized_array(1);
    exchange_atomic();
    exchange_atomic_static_sized_array(1);
    exchange_atomic_dynamic_sized_array(1);
    fetch_add_atomic_dynamic_sized_array_static_index();
    exchange_atomic_dynamic_sized_array_static_index();
}
