// Generated by WebGPU-KTypes WGSL Backend

fn breakIfEmpty() {
    loop {
        continuing {
            if (true) {
                break;
            }
        }
    }
}

fn breakIfEmptyBody(a: bool) {
    loop {
        continuing {
            var b: bool = a;
            var c: bool = (a != b);
            if ((a == c)) {
                break;
            }
        }
    }
}

fn breakIf(a: bool) {
    loop {
        var d: bool = a;
        var e: bool = (a != d);
        continuing {
            if ((a == e)) {
                break;
            }
        }
    }
}

fn breakIfSeparateVariable() {
    var counter: u32 = 0u;
    loop {
        counter = 1u;
        continuing {
            if ((counter == 5u)) {
                break;
            }
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    breakIfEmpty();
    breakIfEmptyBody(false);
    breakIf(false);
    breakIfSeparateVariable();
}
