// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    @builtin(position) position: vec4<f32>,
    clip_distances: array<f32, 1>,
}

@vertex
fn main() -> Struct_3 {
    var out: Struct_3;
    out.clip_distances[0] = 0.5f;
    return out;
}
