// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    data: array<u32>,
}
@group(0) @binding(0)
var<storage, read_write> v_indices: Struct_2;

fn collatz_iterations(n_base: u32) -> u32 {
    var n: u32 = n_base;
    var i: u32 = 0u;
    loop {
        if ((n > 1u)) {
            if (((n % 2u) == 0u)) {
                n = (n / 2u);
            } else {
                n = ((3u * n) + 1u);
            }
            i = (i + 1u);
        } else {
            break;
        }
    }
    return i;
}

@compute
@workgroup_size(1, 1, 1)
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
    v_indices.data[global_id[0]] = collatz_iterations(v_indices.data[global_id[0]]);
}
