// Generated by WebGPU-KTypes WGSL Backend
const x: i32 = 1;
const y: i32 = 2;
const g_false: bool = false;

@compute
@workgroup_size(1, 1, 1)
fn foo() {
    var z: i32 = ((x + y) - 2);
    var l_false: bool = false;
}
