// Generated by WebGPU-KTypes WGSL Backend
const TWO: u32 = 2u;
const THREE: i32 = 3;
const TRUE: bool = true;
const FALSE: bool = false;
const FOUR: i32 = 4;
const PI: f32 = 3.141f;
const DIV: vec4<f32> = vec4<f32>((4.0f / 9.0f), 0.0f, 0.0f, 0.0f);
const TEXTURE_KIND_REGULAR: i32 = 0;
const TEXTURE_KIND_WARP: i32 = 1;
const TEXTURE_KIND_SKY: i32 = 2;
const add_vec: vec2<f32> = (vec2<f32>(1.0f) + vec2<f32>(3.0f, 4.0f));
const compare_vec: vec2<bool> = (vec2<f32>(3.0f) == vec2<f32>(3.0f, 4.0f));
const ABSTRACT_ARRAY: array<i32, 9> = array<i32, 9>(1, 2, 3, 4, 5, 6, 7, 8, 9);
const ABSTRACT_VECTOR: vec4<f32> = vec4<f32>(1, 2, 3, 4);
const FOUR_ALIAS: i32 = FOUR;
const TEST_CONSTANT_ADDITION: i32 = (FOUR + FOUR);
const phi_sun: f32 = (PI * 2.0f);
const TEST_CONSTANT_ALIAS_ADDITION: i32 = (FOUR_ALIAS + FOUR_ALIAS);

fn swizzle_of_compose() {
    var out: vec4<f32> = vec4<f32>(vec2<f32>(1, 2), vec2<f32>(3, 4)).wzyx;
}

fn index_of_compose() {
    var out: f32 = vec4<f32>(vec2<f32>(1, 2), vec2<f32>(3, 4))[1];
}

fn compose_three_deep() {
    var out: f32 = vec4<f32>(vec3<f32>(vec2<f32>(6, 7), 8), 9)[0];
}

fn non_constant_initializers() {
    var w: i32 = (10 + 20);
    var x: i32 = w;
    var y: i32 = x;
    var z: i32 = (30 + 40);
    var out: vec4<f32> = vec4<f32>(w, x, y, z);
}

fn compose_of_splat() {
    var x: vec4<f32> = vec4<f32>(vec3<f32>(1.0f), 2.0f).wzyx;
}

fn compose_vector_zero_val_binop() {
    var a: vec3<f32> = (vec3<f32>(vec2<i32>(), 0) + vec3<f32>(1));
    var b: vec3<f32> = (vec3<f32>(vec2<i32>(), 0) + vec3<f32>(0, 1, 2));
    var c: vec3<f32> = (vec3<f32>(vec2<i32>(), 2) + vec3<f32>(1, vec2<i32>()));
}

fn test_local_const() {
    var local_const: i32 = 2;
    var arr: array<f32>;
}

fn packed_dot_product() {
    var signed_four: i32 = dot4I8Packed(TWO, TWO);
    var unsigned_four: u32 = dot4U8Packed(TWO, TWO);
    var signed_twelve: i32 = dot4I8Packed((TWO + 1u), (TWO + 2u));
    var unsigned_twelve: u32 = dot4U8Packed((TWO + 1u), (TWO + 2u));
    var signed_seventy: i32 = dot4I8Packed(16909060u, 84281096u);
    var unsigned_seventy: u32 = dot4U8Packed(16909060u, 84281096u);
    var minus_four: i32 = dot4I8Packed(4278385924u, 84343288u);
}

fn relational() {
    var scalar_any_false: bool = any(false);
    var scalar_any_true: bool = any(true);
    var scalar_all_false: bool = all(false);
    var scalar_all_true: bool = all(true);
    var vec_any_false: vec4<bool> = any(vec4<bool>());
    var vec_any_true: vec4<f32> = any(vec4<f32>(bool(), true, vec2<f32>(FALSE)));
    var vec_all_false: vec4<f32> = all(vec4<f32>(vec3<f32>(vec2<bool>(), TRUE), false));
    var vec_all_true: vec4<f32> = all(vec4<f32>(true));
}

fn splat_of_constant() {
    var out: vec4<f32> = -(vec4<f32>(FOUR));
}

fn compose_of_constant() {
    var out: vec4<f32> = -(vec4<f32>(FOUR, FOUR, FOUR, FOUR));
}

fn map_texture_kind(texture_kind: i32) -> u32 {
    switch (texture_kind) {
        case 0: {
            return 10u;
            break;
        }
        case 1: {
            return 20u;
            break;
        }
        case 2: {
            return 30u;
            break;
        }
        default: {
            return 0u;
            break;
        }
    }
}

fn abstract_access(i: u32) {
    var a: f32 = ABSTRACT_ARRAY[0];
    var b: u32 = ABSTRACT_VECTOR[0];
    var c: i32 = ABSTRACT_ARRAY[i];
    var d: i32 = ABSTRACT_VECTOR[i];
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    swizzle_of_compose();
    index_of_compose();
    compose_three_deep();
    non_constant_initializers();
    splat_of_constant();
    compose_of_constant();
    map_texture_kind(1);
    compose_of_splat();
    test_local_const();
    compose_vector_zero_val_binop();
    relational();
    packed_dot_product();
    test_local_const();
    abstract_access(1);
}
