// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: vec4<f32>,
    b: i32,
}
const const1: vec3<f32> = vec3<f32>(0.0f);
const const2: vec3<f32> = vec3<f32>(0.0f, 1.0f, 2.0f);
const const3: mat2x2<f32> = mat2x2<f32>(0.0f, 1.0f, 2.0f, 3.0f);
const const4: array<mat2x2<f32>, 1> = array<mat2x2<f32>, 1>(mat2x2<f32>(0.0f, 1.0f, 2.0f, 3.0f));
const cz0: bool = bool();
const cz1: i32 = i32();
const cz2: u32 = u32();
const cz3: f32 = f32();
const cz4: vec2<u32> = vec2<u32>();
const cz5: mat2x2<f32> = mat2x2<f32>();
const cp1: vec2<f32> = vec2<f32>(0u);
const cp2: mat2x2<f32> = mat2x2<f32>(vec2<f32>(0.0f), vec2<f32>(0.0f));
const cp3: array<i32, 4> = array<i32, 4>(0, 1, 2, 3);
const cz6: array<Struct_3, 3> = array<Struct_3, 3>();
const cz7: Struct_3 = Struct_3();

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var foo: Struct_3;
    foo = Struct_3(vec4<f32>(1.0f), 1);
    var m0: mat2x2<f32> = mat2x2<f32>(1.0f, 0.0f, 0.0f, 1.0f);
    var m1: mat4x4<f32> = mat4x4<f32>(1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f);
    var zvc0: bool = bool();
    var zvc1: i32 = i32();
    var zvc2: u32 = u32();
    var zvc3: f32 = f32();
    var zvc4: vec2<u32> = vec2<u32>();
    var zvc5: mat2x2<f32> = mat2x2<f32>();
    var zvc6: array<Struct_3, 3> = array<Struct_3, 3>();
    var zvc7: Struct_3 = Struct_3();
    var zvc8: vec2<u32> = vec2<f32>();
    var zvc9: vec2<f32> = vec2<f32>();
    var cit0: vec2<f32> = vec2<f32>(0u);
    var cit1: mat2x2<f32> = mat2x2<f32>(vec2<f32>(0.0f), vec2<f32>(0.0f));
    var cit2: array<i32, 4> = array<i32, 4>(0, 1, 2, 3);
    var ic0: bool = bool(bool());
    var ic1: i32 = i32(i32());
    var ic2: u32 = u32(u32());
    var ic3: f32 = f32(f32());
    var ic4: vec2<u32> = vec2<u32>(vec2<u32>());
    var ic5: mat2x3<f32> = mat2x3<f32>(mat2x3<f32>());
    var ic6: vec2<f32> = vec2<f32>(vec2<u32>());
    var ic7: mat2x3<f32> = mat2x3<f32>(mat2x3<f32>());
    var cc00: i32 = i32(1u);
    var cc01: i32 = i32(1.0f);
    var cc02: i32 = i32(1);
    var cc03: i32 = i32(1.0f);
    var cc04: i32 = i32(true);
    var cc05: u32 = u32(1);
    var cc06: u32 = u32(1.0f);
    var cc07: u32 = u32(1);
    var cc08: u32 = u32(1.0f);
    var cc09: u32 = u32(true);
    var cc10: f32 = f32(1);
    var cc11: f32 = f32(1u);
    var cc12: f32 = f32(1);
    var cc13: f32 = f32(1.0f);
    var cc14: f32 = f32(true);
    var cc15: bool = bool(1);
    var cc16: bool = bool(1u);
    var cc17: bool = bool(1.0f);
    var cc18: bool = bool(1);
    var cc19: bool = bool(1.0f);
}
