// Generated by WebGPU-KTypes WGSL Backend
const ONE: i32 = 1;

fn control_flow() {
    storageBarrier();
    workgroupBarrier();
    textureBarrier();
    var pos: i32;
    switch (1) {
        default: {
            pos = 1;
            break;
        }
    }
    switch (pos) {
        case 1: {
            pos = 0;
            break;
            break;
        }
        case 2: {
            pos = 1;
            break;
        }
        case 3: {
            pos = 2;
            break;
        }
        case 4: {
            pos = 2;
            break;
        }
        case 5: {
            pos = 3;
            break;
        }
        case 6: {
            pos = 4;
            break;
        }
    }
    switch (0u) {
        case 0u: {
            break;
        }
        default: {
            break;
        }
    }
    switch (pos) {
        case 1: {
            pos = 0;
            break;
            break;
        }
        case 2: {
            pos = 1;
            break;
        }
        case 3: {
            pos = 2;
            break;
        }
        case 4: {
            break;
        }
        default: {
            pos = 3;
            break;
        }
    }
    switch (pos) {
        case 1: {
            pos = 0;
            break;
        }
        case 2: {
            pos = 1;
            break;
        }
        case 3: {
            pos = 2;
            break;
        }
        case 4: {
            pos = 2;
            break;
        }
        case 5: {
            pos = 3;
            break;
        }
        case 6: {
            pos = 3;
            break;
        }
        default: {
            pos = 4;
            break;
        }
    }
}

fn switch_default_break(i: i32) {
    switch (i) {
        default: {
            break;
            break;
        }
    }
}

fn switch_case_break() {
    switch (0) {
        case 0: {
            break;
            break;
        }
        default: {
            break;
        }
    }
    return;
}

fn switch_selector_type_conversion() {
    switch (0u) {
        case 0: {
            break;
        }
        default: {
            break;
        }
    }
    switch (0) {
        case 0u: {
            break;
        }
        default: {
            break;
        }
    }
}

fn loop_switch_continue(x: i32) {
    loop {
        switch (x) {
            case 1: {
                continue;
                break;
            }
            default: {
                break;
            }
        }
    }
}

fn loop_switch_continue_nesting(x: i32, y: i32, z: i32) {
    loop {
        switch (x) {
            case 1: {
                continue;
                break;
            }
            case 2: {
                switch (y) {
                    case 1: {
                        continue;
                        break;
                    }
                    default: {
                        loop {
                            switch (z) {
                                case 1: {
                                    continue;
                                    break;
                                }
                                default: {
                                    break;
                                }
                            }
                        }
                        break;
                    }
                }
                break;
            }
            default: {
                break;
            }
        }
        switch (y) {
            default: {
                continue;
                break;
            }
        }
    }
    loop {
        switch (y) {
            case 1: {
                switch (z) {
                    default: {
                        continue;
                        break;
                    }
                }
                break;
            }
        }
    }
}

fn loop_switch_omit_continue_variable_checks(x: i32, y: i32, z: i32, w: i32) {
    var pos: i32 = 0;
    loop {
        switch (x) {
            case 1: {
                pos = 1;
                break;
            }
            default: {
                break;
            }
        }
    }
    loop {
        switch (x) {
            case 1: {
                break;
            }
            case 2: {
                switch (y) {
                    case 1: {
                        continue;
                        break;
                    }
                    default: {
                        switch (z) {
                            case 1: {
                                pos = 2;
                                break;
                            }
                            default: {
                                break;
                            }
                        }
                        break;
                    }
                }
                break;
            }
            default: {
                break;
            }
        }
    }
}

fn switch_const_expr_case_selectors() {
    var TWO: i32 = 2;
    switch (0) {
        case 0: {
            break;
        }
        case 1: {
            break;
        }
        case 2: {
            break;
        }
        case 3: {
            break;
        }
        case 4: {
            break;
        }
        default: {
            break;
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    control_flow();
    switch_default_break(1);
    switch_case_break();
    switch_selector_type_conversion();
    switch_const_expr_case_selectors();
    loop_switch_continue(1);
    loop_switch_continue_nesting(1, 2, 3);
    loop_switch_omit_continue_variable_checks(1, 2, 3, 4);
}
