// Generated by WebGPU-KTypes WGSL Backend
const ic0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var ic0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
    var lc0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
    var vc0: vec2<f32> = (vec2<f32>(1, 1) + vec2<f32>(1.0f, 1.0f));
}
