// Generated by WebGPU-KTypes WGSL Backend
var<private> a: coop_mat8x8<f32, A>;
var<private> b: coop_mat8x8<f32, B>;
@group(0) @binding(0)
var<storage, read_write> ext: array<f32>;

fn coopLoad(arg_0: ptr<function, f32>) -> coop_mat8x8<f32, C> {
}

fn coopMultiplyAdd(arg_0: coop_mat8x8<f32, A>, arg_1: coop_mat8x8<f32, B>, arg_2: coop_mat8x8<f32, C>) -> coop_mat8x8<f32, C> {
}

fn coopStore(arg_0: coop_mat8x8<f32, C>, arg_1: ptr<function, f32>) {
}

@compute
@workgroup_size(8, 8, 1)
fn main() {
    var c: coop_mat8x8<f32, C> = coopLoad(&ext[4]);
    var d: coop_mat8x8<f32, C> = coopMultiplyAdd(a, b, c);
    coopStore(d, &ext[0]);
    c = d;
}
