// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(4)
var point_shadow_textures: texture_depth_cube_array;
@group(0) @binding(5)
var point_shadow_textures_sampler: sampler_comparison;

@fragment
fn fragment() -> vec4<f32> {
    var frag_ls: vec3<f32> = vec4<f32>(1.0f, 1.0f, 2.0f, 1.0f).xyz;
    var a: f32 = textureSampleCompare(point_shadow_textures, point_shadow_textures_sampler, frag_ls, i32(1), 1.0f);
    return vec4<f32>(a, 1.0f, 1.0f, 1.0f);
}
