// Generated by WebGPU-KTypes WGSL Backend
struct Struct_6 {
    chunk_size: vec2<u32>,
    chunk_corner: vec2<i32>,
    min_max_height: vec2<f32>,
}
struct Struct_8 {
    position: vec3<f32>,
    normal: vec3<f32>,
}
struct Struct_10 {
    data: array<u32>,
}
struct Struct_11 {
    chunk_size: vec2<u32>,
    chunk_corner: vec2<i32>,
    min_max_height: vec2<f32>,
    texture_size: u32,
    start_index: u32,
}
struct Struct_13 {
    index: u32,
    @builtin(position) position: vec4<f32>,
    uv: vec2<f32>,
}
struct Struct_14 {
    vert_component: u32,
    index: u32,
}
struct Struct_16 {
    view_pos: vec4<f32>,
    view_proj: mat4x4<f32>,
}
struct Struct_17 {
    position: vec3<f32>,
    color: vec3<f32>,
}
struct Struct_18 {
    @builtin(position) clip_position: vec4<f32>,
    normal: vec3<f32>,
    world_pos: vec3<f32>,
}
struct Struct_20 {
    data: array<Struct_8>,
}
@group(2) @binding(0)
var t_diffuse: texture_2d<f32>;
@group(2) @binding(1)
var s_diffuse: sampler;
@group(2) @binding(2)
var t_normal: texture_2d<f32>;
@group(2) @binding(3)
var s_normal: sampler;
@group(0) @binding(0)
var<uniform> chunk_data: Struct_6;
@group(0) @binding(2)
var<storage, read_write> indices: Struct_10;
@group(0) @binding(0)
var<uniform> gen_data: Struct_11;
@group(0) @binding(0)
var<uniform> camera: Struct_16;
@group(1) @binding(0)
var<uniform> light: Struct_17;
@group(0) @binding(1)
var<storage, read_write> vertices: Struct_20;

fn permute3(x: vec3<f32>) -> vec3<f32> {
    return ((((x * 34.0f) + 1.0f) * x) % vec3<f32>(289.0f));
}

fn index_to_p(vert_index: u32, chunk_size: vec2<u32>, chunk_corner: vec2<i32>) -> vec2<f32> {
    return (vec2<f32>((f32(vert_index) % f32((chunk_size[0] + 1u))), f32((vert_index / (chunk_size[0] + 1u)))) + vec2<f32>(chunk_corner));
}

fn snoise2(v: vec2<f32>) -> f32 {
    var C: vec4<f32> = vec4<f32>(0.21132487f, 0.36602542f, -(0.57735026f), 0.024390243f);
    var i: vec2<f32> = floor((v + dot(v, C.yy)));
    var x0: vec2<f32> = ((v - i) + dot(i, C.xx));
    var i1: vec2<f32> = select(vec2<f32>(1.0f, 0.0f), vec2<f32>(0.0f, 1.0f), (x0[0] < x0[1]));
    var x12: vec4<f32> = ((x0.xyxy + C.xxzz) - vec4<f32>(i1, 0.0f, 0.0f));
    i = (i % vec2<f32>(289.0f));
    var p: vec3<f32> = permute3(((permute3((i[1] + vec3<f32>(0.0f, i1[1], 1.0f))) + i[0]) + vec3<f32>(0.0f, i1[0], 1.0f)));
    var m: vec3<f32> = max((0.5f - vec3<f32>(dot(x0, x0), dot(x12.xy, x12.xy), dot(x12.zw, x12.zw))), vec3<f32>(0.0f));
    m = (m * m);
    m = (m * m);
    var x: vec3<f32> = ((2.0f * fract((p * C.www))) - 1.0f);
    var h: vec3<f32> = (abs(x) - 0.5f);
    var ox: vec3<f32> = floor((x + 0.5f));
    var a0: vec3<f32> = (x - ox);
    m = (m * (1.7928429f - (0.85373473f * ((a0 * a0) + (h * h)))));
    var g: vec3<f32> = vec3<f32>(((a0[0] * x0[0]) + (h[0] * x0[1])), ((a0.yz * x12.xz) + (h.yz * x12.yw)));
    return (130.0f * dot(m, g));
}

fn fbm(p: vec2<f32>) -> f32 {
    var NUM_OCTAVES: u32 = 5u;
    var x: vec2<f32> = (p * 0.01f);
    var v: f32 = 0.0f;
    var a: f32 = 0.5f;
    var shift: vec2<f32> = vec2<f32>(100.0f);
    var cs: vec2<f32> = vec2<f32>(cos(0.5f), sin(0.5f));
    var rot: mat2x2<f32> = mat2x2<f32>(cs[0], cs[1], -(cs[1]), cs[0]);
    {
        var i: u32 = 0u;
        loop {
            if ((i < NUM_OCTAVES)) {
                {
                    v = (v + (a * snoise2(x)));
                    x = (((rot * x) * 2.0f) + shift);
                    a = (a * 0.5f);
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
    return v;
}

fn color23(p: vec2<f32>) -> vec3<f32> {
    return vec3<f32>(((snoise2(p) * 0.5f) + 0.5f), ((snoise2((p + vec2<f32>(23.0f, 32.0f))) * 0.5f) + 0.5f), ((snoise2((p + vec2<f32>(-(43.0f), 3.0f))) * 0.5f) + 0.5f));
}

fn terrain_point(p: vec2<f32>, min_max_height: vec2<f32>) -> vec3<f32> {
    return vec3<f32>(p[0], mix(min_max_height[0], min_max_height[1], fbm(p)), p[1]);
}

fn terrain_vertex(p: vec2<f32>, min_max_height: vec2<f32>) -> Struct_8 {
    var v: vec3<f32> = terrain_point(p, min_max_height);
    var tpx: vec3<f32> = (terrain_point((p + vec2<f32>(0.1f, 0.0f)), min_max_height) - v);
    var tpz: vec3<f32> = (terrain_point((p + vec2<f32>(0.0f, 0.1f)), min_max_height) - v);
    var tnx: vec3<f32> = (terrain_point((p + vec2<f32>(-(0.1f), 0.0f)), min_max_height) - v);
    var tnz: vec3<f32> = (terrain_point((p + vec2<f32>(0.0f, -(0.1f))), min_max_height) - v);
    var pn: vec3<f32> = normalize(cross(tpz, tpx));
    var nn: vec3<f32> = normalize(cross(tnz, tnx));
    var n: vec3<f32> = ((pn + nn) * 0.5f);
    return Struct_8(v, n);
}

@vertex
fn gen_terrain_vertex(@builtin(vertex_index) vindex: u32) -> Struct_13 {
    var u: f32 = f32((((vindex + 2u) / 3u) % 2u));
    var v: f32 = f32((((vindex + 1u) / 3u) % 2u));
    var uv: vec2<f32> = vec2<f32>(u, v);
    var position: vec4<f32> = vec4<f32>((-(1.0f) + (uv * 2.0f)), 0.0f, 1.0f);
    var index: u32 = (u32(((uv[0] * f32(gen_data.texture_size)) + (uv[1] * f32(gen_data.texture_size)))) + gen_data.start_index);
    return Struct_13(index, position, uv);
}

@vertex
fn vs_main(vertex: Struct_8) -> Struct_18 {
    var clip_position: vec4<f32> = (camera.view_proj * vec4<f32>(vertex.position, 1.0f));
    var normal: vec3<f32> = vertex.normal;
    return Struct_18(clip_position, normal, vertex.position);
}

@fragment
fn fs_main(in: Struct_18) -> vec4<f32> {
    _ = t_diffuse;
    _ = s_diffuse;
    _ = t_normal;
    _ = s_normal;
    color23(vec2<f32>(1, 2));
    var color: vec3<f32> = smoothstep(vec3<f32>(0.0f), vec3<f32>(0.1f), fract(in.world_pos));
    color = mix(vec3<f32>(0.5f, 0.1f, 0.7f), vec3<f32>(0.2f, 0.2f, 0.2f), vec3<f32>(((color[0] * color[1]) * color[2])));
    var ambient_strength: f32 = 0.1f;
    var ambient_color: vec3<f32> = (light.color * ambient_strength);
    var light_dir: vec3<f32> = normalize((light.position - in.world_pos));
    var view_dir: vec3<f32> = normalize((camera.view_pos.xyz - in.world_pos));
    var half_dir: vec3<f32> = normalize((view_dir + light_dir));
    var diffuse_strength: vec3<f32> = max(dot(in.normal, light_dir), 0.0f);
    var diffuse_color: vec3<f32> = (diffuse_strength * light.color);
    var specular_strength: vec3<f32> = pow(max(dot(in.normal, half_dir), 0.0f), 32.0f);
    var specular_color: vec3<f32> = (specular_strength * light.color);
    var result: vec3<f32> = (((ambient_color + diffuse_color) + specular_color) * color);
    return vec4<f32>(result, 1.0f);
}

@compute
@workgroup_size(64, 1, 1)
fn gen_terrain_compute(@builtin(global_invocation_id) gid: vec3<u32>) {
    var vert_index: u32 = gid[0];
    var p: vec2<f32> = index_to_p(vert_index, chunk_data.chunk_size, chunk_data.chunk_corner);
    vertices.data[vert_index] = terrain_vertex(p, chunk_data.min_max_height);
    var start_index: u32 = (gid[0] * 6u);
    if ((start_index >= ((chunk_data.chunk_size[0] * chunk_data.chunk_size[1]) * 6u))) {
        return;
    }
    var v00: u32 = (vert_index + (gid[0] / chunk_data.chunk_size[0]));
    var v10: u32 = (v00 + 1u);
    var v01: u32 = ((v00 + chunk_data.chunk_size[0]) + 1u);
    var v11: u32 = (v01 + 1u);
    indices.data[start_index] = v00;
    indices.data[(start_index + 1u)] = v01;
    indices.data[(start_index + 2u)] = v11;
    indices.data[(start_index + 3u)] = v00;
    indices.data[(start_index + 4u)] = v11;
    indices.data[(start_index + 5u)] = v10;
}

@fragment
fn gen_terrain_fragment(in: Struct_13) -> Struct_14 {
    var i: u32 = (u32(((in.uv[0] * f32(gen_data.texture_size)) + (in.uv[1] * f32((gen_data.texture_size * gen_data.texture_size))))) + gen_data.start_index);
    var vert_index: u32 = u32(floor((f32(i) / 6.0f)));
    var comp_index: u32 = (i % 6u);
    var p: vec2<f32> = index_to_p(vert_index, gen_data.chunk_size, gen_data.chunk_corner);
    var v: Struct_8 = terrain_vertex(p, gen_data.min_max_height);
    var vert_component: f32 = 0.0f;
    switch (comp_index) {
        case 0u: {
            vert_component = v.position[0];
            break;
        }
        case 1u: {
            vert_component = v.position[1];
            break;
        }
        case 2u: {
            vert_component = v.position[2];
            break;
        }
        case 3u: {
            vert_component = v.normal[0];
            break;
        }
        case 4u: {
            vert_component = v.normal[1];
            break;
        }
        case 5u: {
            vert_component = v.normal[2];
            break;
        }
        default: {
            break;
        }
    }
    var v00: u32 = (vert_index + (vert_index / gen_data.chunk_size[0]));
    var v10: u32 = (v00 + 1u);
    var v01: u32 = ((v00 + gen_data.chunk_size[0]) + 1u);
    var v11: u32 = (v01 + 1u);
    var index: u32 = 0u;
    switch (comp_index) {
        case 0u: {
            index = v00;
            break;
        }
        case 3u: {
            index = v00;
            break;
        }
        case 2u: {
            index = v11;
            break;
        }
        case 4u: {
            index = v11;
            break;
        }
        case 1u: {
            index = v01;
            break;
        }
        case 5u: {
            index = v10;
            break;
        }
        default: {
            break;
        }
    }
    index = in.index;
    var ivert_component: u32 = bitcast<u32>(vert_component);
    return Struct_14(ivert_component, index);
}
