// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    position: vec3<f32>,
    color: vec3<f32>,
}
struct Struct_4 {
    @builtin(position) clip_position: vec4<f32>,
    color: vec3<f32>,
}

@vertex
fn vs_main(model: Struct_2) -> Struct_4 {
    var out: Struct_4;
    out.color = model.color;
    out.clip_position = vec4<f32>(model.position, 1.0f);
    return out;
}

@fragment
fn fs_main(in: Struct_4) -> vec4<f32> {
    var color: vec3<f32> = in.color;
    {
        var i: i32 = 0;
        loop {
            if ((i < 10)) {
                {
                    var ii: f32 = f32(i);
                    color[0] = (ii * 0.001f);
                    color[1] = (ii * 0.002f);
                }
                i = 1;
            } else {
                break;
            }
        }
    }
    return vec4<f32>(color, 1.0f);
}
