// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    output0: vec4<f32>,
    output1: vec4<f32>,
}

@fragment
fn main() -> Struct_2 {
    return Struct_2(vec4<f32>(0.4f, 0.3f, 0.2f, 0.1f), vec4<f32>(0.9f, 0.8f, 0.7f, 0.6f));
}
