// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    index: u32,
    double: vec2<f32>,
}
struct Struct_5 {
    color: vec4<f32>,
    @builtin(primitive_index) primitive_index: u32,
}
var<private> im: Struct_3;

@fragment
fn main(in: Struct_5) -> vec4<f32> {
    if ((in.primitive_index == im.index)) {
        return in.color;
    } else {
        return vec4<f32>((vec3<f32>(1.0f) - in.color.xyz), in.color[3]);
    }
}
