// Generated by WebGPU-KTypes WGSL Backend
struct Struct_16 {
    val_u32: u32,
    val_i32: i32,
    val_f32: f32,
    val_f16: f16,
    val_f16_2: vec2<f16>,
    val_f16_3: vec3<f16>,
    val_f16_4: vec4<f16>,
    final_value: f16,
    val_mat2x2: mat2x2<f16>,
    val_mat2x3: mat2x3<f16>,
    val_mat2x4: mat2x4<f16>,
    val_mat3x2: mat3x2<f16>,
    val_mat3x3: mat3x3<f16>,
    val_mat3x4: mat3x4<f16>,
    val_mat4x2: mat4x2<f16>,
    val_mat4x3: mat4x3<f16>,
    val_mat4x4: mat4x4<f16>,
}
struct Struct_18 {
    val_f16_array_2: array<f16, 2>,
}
struct Struct_19 {
    scalar1: f16,
    scalar2: f16,
    v3: vec3<f16>,
    tuck_in: f16,
    scalar4: f16,
    larger: u32,
}
var<private> private_variable: f16 = 1.0h;
const constant_variable: f16 = f16(15.2f);
@group(0) @binding(0)
var<uniform> input_uniform: Struct_16;
@group(0) @binding(1)
var<storage> input_storage: Struct_16;
@group(0) @binding(3)
var<storage, read_write> output: Struct_16;
@group(0) @binding(2)
var<storage> input_arrays: Struct_18;
@group(0) @binding(4)
var<storage, read_write> output_arrays: Struct_18;

fn f16_function(x: f16) -> f16 {
    _ = private_variable;
    var l: Struct_19;
    var val: f16 = f16(constant_variable);
    val = (1.0h - 33333.0h);
    val = (val + f16(5.0f));
    val = f16((input_uniform.val_f32 + f32(val)));
    val = vec3<f16>(input_uniform.val_f16)[2];
    output.val_i32 = i32(65504.0h);
    output.val_i32 = i32(-(65504.0h));
    output.val_u32 = u32(65504.0h);
    output.val_u32 = u32(-(65504.0h));
    output.val_f32 = f32(65504.0h);
    output.val_f32 = f32(-(65504.0h));
    output.val_f16 = (input_uniform.val_f16 + input_storage.val_f16);
    output.val_f16_2 = (input_uniform.val_f16_2 + input_storage.val_f16_2);
    output.val_f16_3 = (input_uniform.val_f16_3 + input_storage.val_f16_3);
    output.val_f16_4 = (input_uniform.val_f16_4 + input_storage.val_f16_4);
    output.val_mat2x2 = (input_uniform.val_mat2x2 + input_storage.val_mat2x2);
    output.val_mat2x3 = (input_uniform.val_mat2x3 + input_storage.val_mat2x3);
    output.val_mat2x4 = (input_uniform.val_mat2x4 + input_storage.val_mat2x4);
    output.val_mat3x2 = (input_uniform.val_mat3x2 + input_storage.val_mat3x2);
    output.val_mat3x3 = (input_uniform.val_mat3x3 + input_storage.val_mat3x3);
    output.val_mat3x4 = (input_uniform.val_mat3x4 + input_storage.val_mat3x4);
    output.val_mat4x2 = (input_uniform.val_mat4x2 + input_storage.val_mat4x2);
    output.val_mat4x3 = (input_uniform.val_mat4x3 + input_storage.val_mat4x3);
    output.val_mat4x4 = (input_uniform.val_mat4x4 + input_storage.val_mat4x4);
    output_arrays.val_f16_array_2 = input_arrays.val_f16_array_2;
    val = abs(val);
    val = clamp(val, val, val);
    val = dot(vec2<f32>(val), vec2<f32>(val));
    val = max(val, val);
    val = min(val, val);
    val = sign(val);
    val = f16(1.0f);
    var float_vec2: vec2<f32> = vec2<f32>(input_uniform.val_f16_2);
    output.val_f16_2 = vec2<f16>(float_vec2);
    var float_vec3: vec3<f32> = vec3<f32>(input_uniform.val_f16_3);
    output.val_f16_3 = vec3<f16>(float_vec3);
    var float_vec4: vec4<f32> = vec4<f32>(input_uniform.val_f16_4);
    output.val_f16_4 = vec4<f16>(float_vec4);
    output.val_mat2x2 = mat2x2<f16>(mat2x2<f32>(input_uniform.val_mat2x2));
    output.val_mat2x3 = mat2x3<f16>(mat2x3<f32>(input_uniform.val_mat2x3));
    output.val_mat2x4 = mat2x4<f16>(mat2x4<f32>(input_uniform.val_mat2x4));
    output.val_mat3x2 = mat3x2<f16>(mat3x2<f32>(input_uniform.val_mat3x2));
    output.val_mat3x3 = mat3x3<f16>(mat3x3<f32>(input_uniform.val_mat3x3));
    output.val_mat3x4 = mat3x4<f16>(mat3x4<f32>(input_uniform.val_mat3x4));
    output.val_mat4x2 = mat4x2<f16>(mat4x2<f32>(input_uniform.val_mat4x2));
    output.val_mat4x3 = mat4x3<f16>(mat4x3<f32>(input_uniform.val_mat4x3));
    output.val_mat4x4 = mat4x4<f16>(mat4x4<f32>(input_uniform.val_mat4x4));
    return val;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    output.final_value = f16_function(2.0h);
}
