// Generated by WebGPU-KTypes WGSL Backend
var<private> v: f64 = 1.0;
const k: f64 = 2.0;

fn f(x: f64) -> f64 {
    _ = v;
    var y: f64 = (30.0 + 400.0);
    var z: f64 = (y + f64(5));
    var w: f64 = -(1.0);
    return (((x + y) + k) + 5.0);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    f(6.0);
}
