// Generated by WebGPU-KTypes WGSL Backend

@vertex
fn vs_main(@builtin(vertex_index) in_vertex_index: u32) -> vec4<f32> {
    var x: f32 = f32((i32(in_vertex_index) - 1));
    var y: f32 = f32(((i32((in_vertex_index & 1u)) * 2) - 1));
    return vec4<f32>(x, y, 0.0f, 1.0f);
}

@fragment
fn fs_main() -> vec4<f32> {
    return vec4<f32>(1.0f, 0.0f, 0.0f, 1.0f);
}
