// Generated by WebGPU-KTypes WGSL Backend
struct Struct_9 {
    vec4f: vec4<f32>,
    vec4i: vec4<i32>,
    vec4u: vec4<u32>,
    vec3f: vec3<f32>,
    vec3i: vec3<i32>,
    vec3u: vec3<u32>,
}
struct Struct_13 {
    vec2f: vec2<f32>,
    vec2i: vec2<i32>,
    vec2u: vec2<u32>,
    scalarf: f32,
    scalari: i32,
    scalaru: u32,
}

@fragment
fn main_vec4vec3() -> Struct_9 {
    var output: Struct_9;
    output.vec4f = vec4<f32>(0.0f);
    output.vec4i = vec4<i32>(0);
    output.vec4u = vec4<u32>(0u);
    output.vec3f = vec3<f32>(0.0f);
    output.vec3i = vec3<i32>(0);
    output.vec3u = vec3<u32>(0u);
    return output;
}

@fragment
fn main_vec2scalar() -> Struct_13 {
    var output: Struct_13;
    output.vec2f = vec2<f32>(0.0f);
    output.vec2i = vec2<i32>(0);
    output.vec2u = vec2<u32>(0u);
    output.scalarf = 0.0f;
    output.scalari = 0;
    output.scalaru = 0u;
    return output;
}
