// Generated by WebGPU-KTypes WGSL Backend

fn test_fma() -> vec2<f32> {
    var a: vec2<f32> = vec2<f32>(2.0f, 2.0f);
    var b: vec2<f32> = vec2<f32>(0.5f, 0.5f);
    var c: vec2<f32> = vec2<f32>(0.5f, 0.5f);
    return fma(a, b, c);
}

@fragment
fn main() {
    var a: vec2<f32> = test_fma();
}
