// Generated by WebGPU-KTypes WGSL Backend

fn test_packed_integer_dot_product() -> u32 {
    var a_5: u32 = 1u;
    var b_5: u32 = 2u;
    var c_5: i32 = dot4I8Packed(a_5, b_5);
    var a_6: u32 = 3u;
    var b_6: u32 = 4u;
    var c_6: u32 = dot4U8Packed(a_6, b_6);
    var c_7: i32 = dot4I8Packed((5u + c_6), (6u + c_6));
    var c_8: u32 = dot4U8Packed((7u + c_6), (8u + c_6));
    return c_8;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var c: u32 = test_packed_integer_dot_product();
}
