// Generated by WebGPU-KTypes WGSL Backend

fn test_fma() -> vec2<f32> {
    var a: vec2<f32> = vec2<f32>(2.0f, 2.0f);
    var b: vec2<f32> = vec2<f32>(0.5f, 0.5f);
    var c: vec2<f32> = vec2<f32>(0.5f, 0.5f);
    return fma(a, b, c);
}

fn test_integer_dot_product() -> i32 {
    var a_2: vec2<i32> = vec2<i32>(1);
    var b_2: vec2<i32> = vec2<i32>(1);
    var c_2: i32 = dot(a_2, b_2);
    var a_3: vec3<u32> = vec3<u32>(1u);
    var b_3: vec3<u32> = vec3<u32>(1u);
    var c_3: u32 = dot(a_3, b_3);
    var c_4: i32 = dot(vec4<i32>(4), vec4<i32>(2));
    return c_4;
}

fn test_packed_integer_dot_product() -> u32 {
    var a_5: u32 = 1u;
    var b_5: u32 = 2u;
    var c_5: i32 = dot4I8Packed(a_5, b_5);
    var a_6: u32 = 3u;
    var b_6: u32 = 4u;
    var c_6: u32 = dot4U8Packed(a_6, b_6);
    var c_7: i32 = dot4I8Packed((5u + c_6), (6u + c_6));
    var c_8: u32 = dot4U8Packed((7u + c_6), (8u + c_6));
    return c_8;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var a: vec2<f32> = test_fma();
    var b: i32 = test_integer_dot_product();
    var c: u32 = test_packed_integer_dot_product();
}
