// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    v3: vec3<f32>,
    v1: f32,
}
const Foo: bool = true;
var<workgroup> wg: array<f32, 10>;
var<workgroup> at: atomic<u32>;
@group(0) @binding(2)
var<storage> dummy: array<vec2<f32>>;
@group(0) @binding(3)
var<uniform> float_vecs: array<vec4<f32>, 20>;
@group(0) @binding(4)
var<uniform> global_vec: vec3<f32>;
@group(0) @binding(5)
var<uniform> global_mat: mat3x2<f32>;
@group(0) @binding(6)
var<uniform> global_nested_arrays_of_matrices_2x4: array<array<mat2x4<f32>, 2>, 2>;
@group(0) @binding(7)
var<uniform> global_nested_arrays_of_matrices_4x2: array<array<mat4x2<f32>, 2>, 2>;
@group(0) @binding(1)
var<storage, read_write> alignment: Struct_2;

fn test_msl_packed_vec3_as_arg(arg: vec3<f32>) {
}

fn test_msl_packed_vec3() {
    alignment.v3 = vec3<f32>(1.0f);
    var idx: i32 = 1;
    alignment.v3[0] = 1.0f;
    alignment.v3[0] = 2.0f;
    alignment.v3[idx] = 3.0f;
    var data: Struct_2 = alignment;
    var l0: vec3<f32> = data.v3;
    var l1: vec2<f32> = data.v3.zx;
    test_msl_packed_vec3_as_arg(data.v3);
    var mvm0: vec3<f32> = (data.v3 * mat3x3<f32>());
    var mvm1: vec3<f32> = (mat3x3<f32>() * data.v3);
    var svm0: vec3<f32> = (data.v3 * 2.0f);
    var svm1: vec3<f32> = (2.0f * data.v3);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    test_msl_packed_vec3();
    wg[7] = (global_nested_arrays_of_matrices_4x2[0][0] * global_nested_arrays_of_matrices_2x4[0][0][0])[0];
    wg[6] = (global_mat * global_vec)[0];
    wg[5] = dummy[1][1];
    wg[4] = float_vecs[0][3];
    wg[3] = alignment.v1;
    wg[2] = alignment.v3[0];
    alignment.v1 = 4.0f;
    wg[1] = f32(arrayLength(&dummy));
    atomicStore(&at, 2u);
    var Foo: f32 = 1.0f;
    var at: bool = true;
}
