// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var image_mipmapped_src: texture_2d<u32>;
@group(0) @binding(3)
var image_multisampled_src: texture_multisampled_2d<u32>;
@group(0) @binding(4)
var image_depth_multisampled_src: texture_depth_multisampled_2d;
@group(0) @binding(1)
var image_storage_src: texture_storage_2d<rgba8uint, read>;
@group(0) @binding(5)
var image_array_src: texture_2d_array<u32>;
@group(0) @binding(6)
var image_dup_src: texture_storage_1d<r32uint, read>;
@group(0) @binding(7)
var image_1d_src: texture_1d<u32>;
@group(0) @binding(2)
var image_dst: texture_storage_1d<r32uint, write>;
@group(0) @binding(0)
var image_1d: texture_1d<f32>;
@group(0) @binding(1)
var image_2d: texture_2d<f32>;
@group(0) @binding(2)
var image_2d_u32: texture_2d<u32>;
@group(0) @binding(3)
var image_2d_i32: texture_2d<i32>;
@group(0) @binding(4)
var image_2d_array: texture_2d_array<f32>;
@group(0) @binding(5)
var image_cube: texture_cube<f32>;
@group(0) @binding(6)
var image_cube_array: texture_cube_array<f32>;
@group(0) @binding(7)
var image_3d: texture_3d<f32>;
@group(0) @binding(8)
var image_aa: texture_multisampled_2d<f32>;
@group(1) @binding(0)
var sampler_reg: sampler;
@group(1) @binding(1)
var sampler_cmp: sampler_comparison;
@group(1) @binding(2)
var image_2d_depth: texture_depth_2d;
@group(1) @binding(3)
var image_2d_array_depth: texture_depth_2d_array;
@group(1) @binding(4)
var image_cube_depth: texture_depth_cube;

@compute
@workgroup_size(16, 1, 1)
fn main(@builtin(local_invocation_id) local_id: vec3<u32>) {
    var dim: vec2<u32> = textureDimensions(image_storage_src);
    var itc: vec2<i32> = (vec2<i32>((dim * local_id.xy)) % vec2<i32>(10, 20));
    var value1: texture_2d<u32> = textureLoad(image_mipmapped_src, itc, i32(local_id[2]));
    var value1_2: texture_2d<u32> = textureLoad(image_mipmapped_src, itc, u32(local_id[2]));
    var value2: texture_multisampled_2d<u32> = textureLoad(image_multisampled_src, itc, i32(local_id[2]));
    var value3: texture_multisampled_2d<u32> = textureLoad(image_multisampled_src, itc, u32(local_id[2]));
    var value4: texture_storage_2d<rgba8uint, read> = textureLoad(image_storage_src, itc);
    var value5: texture_2d_array<u32> = textureLoad(image_array_src, itc, local_id[2], (i32(local_id[2]) + 1));
    var value6: texture_2d_array<u32> = textureLoad(image_array_src, itc, i32(local_id[2]), (i32(local_id[2]) + 1));
    var value7: texture_1d<u32> = textureLoad(image_1d_src, i32(local_id[0]), i32(local_id[2]));
    var value8: texture_storage_1d<r32uint, read> = textureLoad(image_dup_src, i32(local_id[0]));
    var value1u: texture_2d<u32> = textureLoad(image_mipmapped_src, vec2<u32>(itc), i32(local_id[2]));
    var value2u: texture_multisampled_2d<u32> = textureLoad(image_multisampled_src, vec2<u32>(itc), i32(local_id[2]));
    var value3u: texture_multisampled_2d<u32> = textureLoad(image_multisampled_src, vec2<u32>(itc), u32(local_id[2]));
    var value4u: texture_storage_2d<rgba8uint, read> = textureLoad(image_storage_src, vec2<u32>(itc));
    var value5u: texture_2d_array<u32> = textureLoad(image_array_src, vec2<u32>(itc), local_id[2], (i32(local_id[2]) + 1));
    var value6u: texture_2d_array<u32> = textureLoad(image_array_src, vec2<u32>(itc), i32(local_id[2]), (i32(local_id[2]) + 1));
    var value7u: texture_1d<u32> = textureLoad(image_1d_src, u32(local_id[0]), i32(local_id[2]));
    textureStore(image_dst, itc[0], ((((value1 + value2) + value4) + value5) + value6));
    textureStore(image_dst, u32(itc[0]), ((((value1u + value2u) + value4u) + value5u) + value6u));
}

@compute
@workgroup_size(16, 1, 1)
fn depth_load(@builtin(local_invocation_id) local_id: vec3<u32>) {
    var dim: vec2<u32> = textureDimensions(image_storage_src);
    var itc: vec2<i32> = (vec2<i32>((dim * local_id.xy)) % vec2<i32>(10, 20));
    var val: f32 = textureLoad(image_depth_multisampled_src, itc, i32(local_id[2]));
    textureStore(image_dst, itc[0], vec4<u32>(u32(val)));
    return;
}

@vertex
fn queries() -> vec4<f32> {
    var dim_1d: u32 = textureDimensions(image_1d);
    var dim_1d_lod: u32 = textureDimensions(image_1d, i32(dim_1d));
    var dim_2d: vec2<u32> = textureDimensions(image_2d);
    var dim_2d_lod: vec2<u32> = textureDimensions(image_2d, 1);
    var dim_2d_array: vec2<u32> = textureDimensions(image_2d_array);
    var dim_2d_array_lod: vec2<u32> = textureDimensions(image_2d_array, 1);
    var dim_cube: vec2<u32> = textureDimensions(image_cube);
    var dim_cube_lod: vec2<u32> = textureDimensions(image_cube, 1);
    var dim_cube_array: vec2<u32> = textureDimensions(image_cube_array);
    var dim_cube_array_lod: vec2<u32> = textureDimensions(image_cube_array, 1);
    var dim_3d: vec3<u32> = textureDimensions(image_3d);
    var dim_3d_lod: vec3<u32> = textureDimensions(image_3d, 1);
    var dim_2s_ms: vec2<u32> = textureDimensions(image_aa);
    var sum: u32 = ((((((((((dim_1d + dim_2d[1]) + dim_2d_lod[1]) + dim_2d_array[1]) + dim_2d_array_lod[1]) + dim_cube[1]) + dim_cube_lod[1]) + dim_cube_array[1]) + dim_cube_array_lod[1]) + dim_3d[2]) + dim_3d_lod[2]);
    return vec4<f32>(f32(sum));
}

@vertex
fn levels_queries() -> vec4<f32> {
    var num_levels_2d: u32 = textureNumLevels(image_2d);
    var num_layers_2d: u32 = textureNumLayers(image_2d_array);
    var num_levels_2d_array: u32 = textureNumLevels(image_2d_array);
    var num_layers_2d_array: u32 = textureNumLayers(image_2d_array);
    var num_levels_cube: u32 = textureNumLevels(image_cube);
    var num_levels_cube_array: u32 = textureNumLevels(image_cube_array);
    var num_layers_cube: u32 = textureNumLayers(image_cube_array);
    var num_levels_3d: u32 = textureNumLevels(image_3d);
    var num_samples_aa: u32 = textureNumSamples(image_aa);
    var sum: u32 = (((((((num_layers_2d + num_layers_cube) + num_samples_aa) + num_levels_2d) + num_levels_2d_array) + num_levels_3d) + num_levels_cube) + num_levels_cube_array);
    return vec4<f32>(f32(sum));
}

@fragment
fn texture_sample() -> vec4<f32> {
    var tc: vec2<f32> = vec2<f32>(0.5f);
    var tc3: vec3<f32> = vec3<f32>(0.5f);
    var offset: vec2<i32> = vec2<i32>(3, 1);
    var level: f32 = 2.3f;
    var a: vec4<f32>;
    a = textureSample(image_1d, sampler_reg, tc[0]);
    a = textureSample(image_2d, sampler_reg, tc);
    a = textureSample(image_2d, sampler_reg, tc, vec2<i32>(3, 1));
    a = textureSampleLevel(image_2d, sampler_reg, tc, level);
    a = textureSampleLevel(image_2d, sampler_reg, tc, level, offset);
    a = textureSampleBias(image_2d, sampler_reg, tc, 2.0f, offset);
    a = textureSampleBaseClampToEdge(image_2d, sampler_reg, tc);
    a = textureSample(image_2d_array, sampler_reg, tc, 0u);
    a = textureSample(image_2d_array, sampler_reg, tc, 0u, offset);
    a = textureSampleLevel(image_2d_array, sampler_reg, tc, 0u, level);
    a = textureSampleLevel(image_2d_array, sampler_reg, tc, 0u, level, offset);
    a = textureSampleBias(image_2d_array, sampler_reg, tc, 0u, 2.0f, offset);
    a = textureSample(image_2d_array, sampler_reg, tc, 0);
    a = textureSample(image_2d_array, sampler_reg, tc, 0, offset);
    a = textureSampleLevel(image_2d_array, sampler_reg, tc, 0, level);
    a = textureSampleLevel(image_2d_array, sampler_reg, tc, 0, level, offset);
    a = textureSampleBias(image_2d_array, sampler_reg, tc, 0, 2.0f, offset);
    a = textureSample(image_cube_array, sampler_reg, tc3, 0u);
    a = textureSampleLevel(image_cube_array, sampler_reg, tc3, 0u, level);
    a = textureSampleBias(image_cube_array, sampler_reg, tc3, 0u, 2.0f);
    a = textureSample(image_cube_array, sampler_reg, tc3, 0);
    a = textureSampleLevel(image_cube_array, sampler_reg, tc3, 0, level);
    a = textureSampleBias(image_cube_array, sampler_reg, tc3, 0, 2.0f);
    return a;
}

@fragment
fn gather() -> vec4<f32> {
    var tc: vec2<f32> = vec2<f32>(0.5f);
    var dref: f32 = 0.5f;
    var s2d: i32 = textureGather(1, image_2d, sampler_reg, tc);
    var s2d_offset: i32 = textureGather(3, image_2d, sampler_reg, tc, vec2<i32>(3, 1));
    var s2d_depth: texture_depth_2d = textureGatherCompare(image_2d_depth, sampler_cmp, tc, dref);
    var s2d_depth_offset: texture_depth_2d = textureGatherCompare(image_2d_depth, sampler_cmp, tc, dref, vec2<i32>(3, 1));
    var u: i32 = textureGather(0, image_2d_u32, sampler_reg, tc);
    var i: i32 = textureGather(0, image_2d_i32, sampler_reg, tc);
    var f: vec4<f32> = (vec4<f32>(u) + vec4<f32>(i));
    return ((((s2d + s2d_offset) + s2d_depth) + s2d_depth_offset) + f);
}

@fragment
fn depth_no_comparison() -> vec4<f32> {
    var tc: vec2<f32> = vec2<f32>(0.5f);
    var level: i32 = 1;
    var s2d: vec4<f32> = textureSample(image_2d_depth, sampler_reg, tc);
    var s2d_gather: texture_depth_2d = textureGather(image_2d_depth, sampler_reg, tc);
    var s2d_level: vec4<f32> = textureSampleLevel(image_2d_depth, sampler_reg, tc, level);
    return ((s2d + s2d_gather) + s2d_level);
}

@fragment
fn texture_sample_comparison() -> f32 {
    var tc: vec2<f32> = vec2<f32>(0.5f);
    var tc3: vec3<f32> = vec3<f32>(0.5f);
    var dref: f32 = 0.5f;
    var a: f32;
    a = textureSampleCompare(image_2d_depth, sampler_cmp, tc, dref);
    a = textureSampleCompare(image_2d_array_depth, sampler_cmp, tc, 0u, dref);
    a = textureSampleCompare(image_2d_array_depth, sampler_cmp, tc, 0, dref);
    a = textureSampleCompare(image_cube_depth, sampler_cmp, tc3, dref);
    a = textureSampleCompareLevel(image_2d_depth, sampler_cmp, tc, dref);
    a = textureSampleCompareLevel(image_2d_array_depth, sampler_cmp, tc, 0u, dref);
    a = textureSampleCompareLevel(image_2d_array_depth, sampler_cmp, tc, 0, dref);
    a = textureSampleCompareLevel(image_cube_depth, sampler_cmp, tc3, dref);
    return a;
}
