// Generated by WebGPU-KTypes WGSL Backend

fn index_arg_array(a: array<i32, 5>, i: i32) -> i32 {
    return a[i];
}

fn index_let_array(i: i32, j: i32) -> i32 {
    var a: array<array<i32, 2>, 2> = array<array<i32, 2>, 2>(array<i32, 2>(1, 2), array<i32, 2>(3, 4));
    return a[i][j];
}

fn index_let_matrix(i: i32, j: i32) -> f32 {
    var a: mat2x2<f32> = mat2x2<f32>(1, 2, 3, 4);
    return a[i][j];
}

fn index_let_array_1d(vi: u32) -> vec4<f32> {
    var arr: array<i32, 5> = array<i32, 5>(1, 2, 3, 4, 5);
    var value: i32 = arr[vi];
    return vec4<f32>(vec4<i32>(value));
}

@vertex
fn main(@builtin(vertex_index) vi: u32) -> vec4<f32> {
    index_arg_array(array<i32, 5>(1, 2, 3, 4, 5), 6);
    index_let_array(1, 2);
    index_let_matrix(1, 2);
    return index_let_array_1d(vi);
}
