// Generated by WebGPU-KTypes WGSL Backend
struct Struct_5 {
    @builtin(position) position: vec4<f32>,
    _flat: u32,
    flat_either: u32,
    _linear: f32,
    linear_centroid: vec2<f32>,
    linear_sample: vec3<f32>,
    linear_center: vec3<f32>,
    perspective: vec4<f32>,
    perspective_centroid: f32,
    perspective_sample: f32,
    perspective_center: f32,
}

@vertex
fn vert_main() -> Struct_5 {
    var out: Struct_5;
    out.position = vec4<f32>(2.0f, 4.0f, 5.0f, 6.0f);
    out._flat = 8u;
    out.flat_either = 10u;
    out._linear = 27.0f;
    out.linear_centroid = vec2<f32>(64.0f, 125.0f);
    out.linear_sample = vec3<f32>(216.0f, 343.0f, 512.0f);
    out.linear_center = vec3<f32>(255.0f, 511.0f, 1024.0f);
    out.perspective = vec4<f32>(729.0f, 1000.0f, 1331.0f, 1728.0f);
    out.perspective_centroid = 2197.0f;
    out.perspective_sample = 2744.0f;
    out.perspective_center = 2812.0f;
    return out;
}

@fragment
fn frag_main(val: Struct_5) {
}
