// Generated by WebGPU-KTypes WGSL Backend

fn blockLexicalScope(a: bool) {
    {
        var a: i32 = 2;
        {
            var a: f32 = 2.0f;
        }
        var test: i32 = a;
    }
    var test: bool = a;
}

fn ifLexicalScope(a: bool) {
    if (a) {
        var a: f32 = 2.0f;
    }
    var test: bool = a;
}

fn loopLexicalScope(a: bool) {
    loop {
        var a: f32 = 2.0f;
    }
    var test: bool = a;
}

fn forLexicalScope(a: f32) {
    {
        var a: i32 = 0;
        loop {
            if ((a < 1)) {
                {
                    var a: bool = true;
                }
                a = (a + 1);
            } else {
                break;
            }
        }
    }
    var test: f32 = a;
}

fn whileLexicalScope(a: i32) {
    loop {
        if ((a > 2)) {
            var a: bool = false;
        } else {
            break;
        }
    }
    var test: i32 = a;
}

fn switchLexicalScope(a: i32) {
    switch (a) {
        case 0: {
            var a: bool = false;
            break;
        }
        case 1: {
            var a: f32 = 2.0f;
            break;
        }
        default: {
            var a: bool = true;
            break;
        }
    }
    var test: bool = (a == 2);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    blockLexicalScope(false);
    ifLexicalScope(true);
    loopLexicalScope(false);
    forLexicalScope(1.0f);
    whileLexicalScope(1);
    switchLexicalScope(1);
}
