// Generated by WebGPU-KTypes WGSL Backend
const ga: i32 = 4;
const gb: i32 = 4;
const gc: u32 = 4;
const gd: f32 = 4;
const gf: f32 = 2.0f;
const ge: vec3<f32> = vec3<f32>(ga, ga, ga);

fn const_in_fn() {
    var a: i32 = 4;
    var b: i32 = 4;
    var c: u32 = 4;
    var d: f32 = 4;
    var e: vec3<f32> = vec3<f32>(a, a, a);
    var f: f32 = 2.0f;
    var ag: i32 = ga;
    var bg: i32 = gb;
    var cg: u32 = gc;
    var dg: f32 = gd;
    var eg: vec3<f32> = ge;
    var fg: f32 = gf;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    const_in_fn();
}
