// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: i32,
    b: mat2x2<f32>,
}
@group(0) @binding(0)
var<uniform> u: Struct_3;

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var v: Struct_3 = u;
}
