// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    m: mat2x2<f32>,
}
struct Struct_4 {
    a: array<Struct_2, 4>,
}
@group(0) @binding(0)
var<storage, read_write> s_m: mat2x2<f32>;
@group(0) @binding(1)
var<uniform> u_m: mat2x2<f32>;
@group(2) @binding(0)
var<storage, read_write> s_am: array<mat2x2<f32>, 4>;
@group(2) @binding(1)
var<uniform> u_am: array<mat2x2<f32>, 4>;
@group(1) @binding(0)
var<storage, read_write> s_sm: Struct_2;
@group(1) @binding(1)
var<uniform> u_sm: Struct_2;
@group(3) @binding(0)
var<storage, read_write> s_sasm: Struct_4;
@group(3) @binding(1)
var<uniform> u_sasm: Struct_4;

fn access_m() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l_s_m: mat2x2<f32> = s_m;
    var l_s_c_c: vec2<f32> = s_m[0];
    var l_s_c_v: vec2<f32> = s_m[idx];
    var l_s_e_cc: f32 = s_m[0][0];
    var l_s_e_cv: f32 = s_m[0][idx];
    var l_s_e_vc: f32 = s_m[idx][0];
    var l_s_e_vv: f32 = s_m[idx][idx];
    var l_u_m: mat2x2<f32> = u_m;
    var l_u_c_c: vec2<f32> = u_m[0];
    var l_u_c_v: vec2<f32> = u_m[idx];
    var l_u_e_cc: f32 = u_m[0][0];
    var l_u_e_cv: f32 = u_m[0][idx];
    var l_u_e_vc: f32 = u_m[idx][0];
    var l_u_e_vv: f32 = u_m[idx][idx];
    s_m = l_u_m;
    s_m[0] = l_u_c_c;
    s_m[idx] = l_u_c_v;
    s_m[0][0] = l_u_e_cc;
    s_m[0][idx] = l_u_e_cv;
    s_m[idx][0] = l_u_e_vc;
    s_m[idx][idx] = l_u_e_vv;
}

fn access_am() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l_s_a: array<mat2x2<f32>, 4> = s_am;
    var l_s_m_c: mat2x2<f32> = s_am[0];
    var l_s_m_v: mat2x2<f32> = s_am[idx];
    var l_s_c_cc: vec2<f32> = s_am[0][0];
    var l_s_c_cv: vec2<f32> = s_am[0][idx];
    var l_s_c_vc: vec2<f32> = s_am[idx][0];
    var l_s_c_vv: vec2<f32> = s_am[idx][idx];
    var l_s_e_ccc: f32 = s_am[0][0][0];
    var l_s_e_ccv: f32 = s_am[0][0][idx];
    var l_s_e_cvc: f32 = s_am[0][idx][0];
    var l_s_e_cvv: f32 = s_am[0][idx][idx];
    var l_s_e_vcc: f32 = s_am[idx][0][0];
    var l_s_e_vcv: f32 = s_am[idx][0][idx];
    var l_s_e_vvc: f32 = s_am[idx][idx][0];
    var l_s_e_vvv: f32 = s_am[idx][idx][idx];
    var l_u_a: array<mat2x2<f32>, 4> = u_am;
    var l_u_m_c: mat2x2<f32> = u_am[0];
    var l_u_m_v: mat2x2<f32> = u_am[idx];
    var l_u_c_cc: vec2<f32> = u_am[0][0];
    var l_u_c_cv: vec2<f32> = u_am[0][idx];
    var l_u_c_vc: vec2<f32> = u_am[idx][0];
    var l_u_c_vv: vec2<f32> = u_am[idx][idx];
    var l_u_e_ccc: f32 = u_am[0][0][0];
    var l_u_e_ccv: f32 = u_am[0][0][idx];
    var l_u_e_cvc: f32 = u_am[0][idx][0];
    var l_u_e_cvv: f32 = u_am[0][idx][idx];
    var l_u_e_vcc: f32 = u_am[idx][0][0];
    var l_u_e_vcv: f32 = u_am[idx][0][idx];
    var l_u_e_vvc: f32 = u_am[idx][idx][0];
    var l_u_e_vvv: f32 = u_am[idx][idx][idx];
    s_am = l_u_a;
    s_am[0] = l_u_m_c;
    s_am[idx] = l_u_m_v;
    s_am[0][0] = l_u_c_cc;
    s_am[0][idx] = l_u_c_cv;
    s_am[idx][0] = l_u_c_vc;
    s_am[idx][idx] = l_u_c_vv;
    s_am[0][0][0] = l_u_e_ccc;
    s_am[0][0][idx] = l_u_e_ccv;
    s_am[0][idx][0] = l_u_e_cvc;
    s_am[0][idx][idx] = l_u_e_cvv;
    s_am[idx][0][0] = l_u_e_vcc;
    s_am[idx][0][idx] = l_u_e_vcv;
    s_am[idx][idx][0] = l_u_e_vvc;
    s_am[idx][idx][idx] = l_u_e_vvv;
}

fn access_sm() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l_s_s: Struct_2 = s_sm;
    var l_s_m: mat2x2<f32> = s_sm.m;
    var l_s_c_c: vec2<f32> = s_sm.m[0];
    var l_s_c_v: vec2<f32> = s_sm.m[idx];
    var l_s_e_cc: f32 = s_sm.m[0][0];
    var l_s_e_cv: f32 = s_sm.m[0][idx];
    var l_s_e_vc: f32 = s_sm.m[idx][0];
    var l_s_e_vv: f32 = s_sm.m[idx][idx];
    var l_u_s: Struct_2 = u_sm;
    var l_u_m: mat2x2<f32> = u_sm.m;
    var l_u_c_c: vec2<f32> = u_sm.m[0];
    var l_u_c_v: vec2<f32> = u_sm.m[idx];
    var l_u_e_cc: f32 = u_sm.m[0][0];
    var l_u_e_cv: f32 = u_sm.m[0][idx];
    var l_u_e_vc: f32 = u_sm.m[idx][0];
    var l_u_e_vv: f32 = u_sm.m[idx][idx];
    s_sm = l_u_s;
    s_sm.m = l_u_m;
    s_sm.m[0] = l_u_c_c;
    s_sm.m[idx] = l_u_c_v;
    s_sm.m[0][0] = l_u_e_cc;
    s_sm.m[0][idx] = l_u_e_cv;
    s_sm.m[idx][0] = l_u_e_vc;
    s_sm.m[idx][idx] = l_u_e_vv;
}

fn access_sasm() {
    var idx: i32 = 1;
    idx = (idx - 1);
    var l_s_s: Struct_4 = s_sasm;
    var l_s_a: array<Struct_2, 4> = s_sasm.a;
    var l_s_m_c: mat2x2<f32> = s_sasm.a[0].m;
    var l_s_m_v: mat2x2<f32> = s_sasm.a[idx].m;
    var l_s_c_cc: vec2<f32> = s_sasm.a[0].m[0];
    var l_s_c_cv: vec2<f32> = s_sasm.a[0].m[idx];
    var l_s_c_vc: vec2<f32> = s_sasm.a[idx].m[0];
    var l_s_c_vv: vec2<f32> = s_sasm.a[idx].m[idx];
    var l_s_e_ccc: f32 = s_sasm.a[0].m[0][0];
    var l_s_e_ccv: f32 = s_sasm.a[0].m[0][idx];
    var l_s_e_cvc: f32 = s_sasm.a[0].m[idx][0];
    var l_s_e_cvv: f32 = s_sasm.a[0].m[idx][idx];
    var l_s_e_vcc: f32 = s_sasm.a[idx].m[0][0];
    var l_s_e_vcv: f32 = s_sasm.a[idx].m[0][idx];
    var l_s_e_vvc: f32 = s_sasm.a[idx].m[idx][0];
    var l_s_e_vvv: f32 = s_sasm.a[idx].m[idx][idx];
    var l_u_s: Struct_4 = u_sasm;
    var l_u_a: array<Struct_2, 4> = u_sasm.a;
    var l_u_m_c: mat2x2<f32> = u_sasm.a[0].m;
    var l_u_m_v: mat2x2<f32> = u_sasm.a[idx].m;
    var l_u_c_cc: vec2<f32> = u_sasm.a[0].m[0];
    var l_u_c_cv: vec2<f32> = u_sasm.a[0].m[idx];
    var l_u_c_vc: vec2<f32> = u_sasm.a[idx].m[0];
    var l_u_c_vv: vec2<f32> = u_sasm.a[idx].m[idx];
    var l_u_e_ccc: f32 = u_sasm.a[0].m[0][0];
    var l_u_e_ccv: f32 = u_sasm.a[0].m[0][idx];
    var l_u_e_cvc: f32 = u_sasm.a[0].m[idx][0];
    var l_u_e_cvv: f32 = u_sasm.a[0].m[idx][idx];
    var l_u_e_vcc: f32 = u_sasm.a[idx].m[0][0];
    var l_u_e_vcv: f32 = u_sasm.a[idx].m[0][idx];
    var l_u_e_vvc: f32 = u_sasm.a[idx].m[idx][0];
    var l_u_e_vvv: f32 = u_sasm.a[idx].m[idx][idx];
    s_sasm = l_u_s;
    s_sasm.a = l_u_a;
    s_sasm.a[0].m = l_u_m_c;
    s_sasm.a[idx].m = l_u_m_v;
    s_sasm.a[0].m[0] = l_u_c_cc;
    s_sasm.a[0].m[idx] = l_u_c_cv;
    s_sasm.a[idx].m[0] = l_u_c_vc;
    s_sasm.a[idx].m[idx] = l_u_c_vv;
    s_sasm.a[0].m[0][0] = l_u_e_ccc;
    s_sasm.a[0].m[0][idx] = l_u_e_ccv;
    s_sasm.a[0].m[idx][0] = l_u_e_cvc;
    s_sasm.a[0].m[idx][idx] = l_u_e_cvv;
    s_sasm.a[idx].m[0][0] = l_u_e_vcc;
    s_sasm.a[idx].m[0][idx] = l_u_e_vcv;
    s_sasm.a[idx].m[idx][0] = l_u_e_vvc;
    s_sasm.a[idx].m[idx][idx] = l_u_e_vvv;
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    access_m();
    access_sm();
    access_am();
    access_sasm();
}
