// Generated by WebGPU-KTypes WGSL Backend
struct Struct_6 {
    fract: f32,
    whole: f32,
}
struct Struct_7 {
    fract: vec2<f32>,
    whole: vec2<f32>,
}
struct Struct_8 {
    fract: vec4<f32>,
    whole: vec4<f32>,
}
struct Struct_9 {
    fract: f32,
    exp: i32,
}
struct Struct_11 {
    fract: vec4<f32>,
    exp: vec4<i32>,
}

@fragment
fn main() {
    var f: f32 = 1.0f;
    var v: vec4<f32> = vec4<f32>(0.0f);
    var a: f32 = degrees(f);
    var b: f32 = radians(f);
    var c: vec4<f32> = degrees(v);
    var d: vec4<f32> = radians(v);
    var e: vec4<f32> = saturate(v);
    var g: vec4<f32> = refract(v, v, f);
    var sign_a: i32 = sign(-(1));
    var sign_b: vec4<f32> = sign(vec4<f32>(-(1)));
    var sign_c: f32 = sign(-(1.0f));
    var sign_d: vec4<f32> = sign(vec4<f32>(-(1.0f)));
    var sign_e: vec4<f32> = sign(vec4<f32>(0.0f));
    var const_dot: vec2<i32> = dot(vec2<i32>(), vec2<i32>());
    var first_leading_bit_abs: u32 = firstLeadingBit(abs(0u));
    var flb_a: i32 = firstLeadingBit(-(1));
    var flb_b: vec2<f32> = firstLeadingBit(vec2<f32>(-(1)));
    var flb_c: vec2<f32> = firstLeadingBit(vec2<f32>(1u));
    var ftb_a: i32 = firstTrailingBit(-(1));
    var ftb_b: u32 = firstTrailingBit(1u);
    var ftb_c: vec2<f32> = firstTrailingBit(vec2<f32>(-(1)));
    var ftb_d: vec2<f32> = firstTrailingBit(vec2<f32>(1u));
    var ctz_a: u32 = countTrailingZeros(0u);
    var ctz_b: i32 = countTrailingZeros(0);
    var ctz_c: i32 = countTrailingZeros(0);
    var ctz_d: i32 = countTrailingZeros(-(1));
    var ctz_e: vec2<f32> = countTrailingZeros(vec2<f32>(0u));
    var ctz_f: vec2<f32> = countTrailingZeros(vec2<f32>(0));
    var ctz_g: vec2<f32> = countTrailingZeros(vec2<f32>(1u));
    var ctz_h: vec2<f32> = countTrailingZeros(vec2<f32>(1));
    var clz_a: i32 = countLeadingZeros(-(1));
    var clz_b: u32 = countLeadingZeros(1u);
    var clz_c: vec2<f32> = countLeadingZeros(vec2<f32>(-(1)));
    var clz_d: vec2<f32> = countLeadingZeros(vec2<f32>(1u));
    var lde_a: f32 = ldexp(1.0f, 2);
    var lde_b: vec2<f32> = ldexp(vec2<f32>(1.0f, 2.0f), vec2<f32>(3, 4));
    var modf_a: Struct_6 = modf(1.5f);
    var modf_b: f32 = modf(1.5f)[0];
    var modf_c: f32 = modf(1.5f)[1];
    var modf_d: Struct_7 = modf(vec2<f32>(1.5f, 1.5f));
    var modf_e: f32 = modf(vec4<f32>(1.5f, 1.5f, 1.5f, 1.5f))[1][0];
    var modf_f: f32 = modf(vec2<f32>(1.5f, 1.5f))[0][1];
    var frexp_a: Struct_9 = frexp(1.5f);
    var frexp_b: f32 = frexp(1.5f)[0];
    var frexp_c: i32 = frexp(1.5f)[1];
    var frexp_d: i32 = frexp(vec4<f32>(1.5f, 1.5f, 1.5f, 1.5f))[1][0];
    var quantizeToF16_a: f32 = quantizeToF16(1.0f);
    var quantizeToF16_b: vec2<f32> = quantizeToF16(vec2<f32>(1.0f, 1.0f));
    var quantizeToF16_c: vec3<f32> = quantizeToF16(vec3<f32>(1.0f, 1.0f, 1.0f));
    var quantizeToF16_d: vec4<f32> = quantizeToF16(vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f));
}
