// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    values: array<u32>,
}
@group(0) @binding(0)
var<storage, read_write> coherent_buf: Struct_2;
@group(0) @binding(1)
var<storage, read_write> volatile_buf: Struct_2;
@group(0) @binding(2)
var<storage, read_write> both_buf: Struct_2;
@group(0) @binding(3)
var<storage, read_write> plain_buf: Struct_2;

@compute
@workgroup_size(1, 1, 1)
fn main() {
    coherent_buf.values[0] = volatile_buf.values[0];
    both_buf.values[0] = plain_buf.values[0];
}
