// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    colorMask: vec4<f32>,
    visible: bool,
}
struct Struct_4 {
    @builtin(position) position: vec4<f32>,
    color: vec4<f32>,
}
struct Struct_7 {
    indices: vec3<u32>,
    cull: bool,
    colorMask: vec4<f32>,
}
struct Struct_8 {
    colorMask: vec4<f32>,
}
struct Struct_11 {
    vertices: array<Struct_4, 3>,
    primitives: array<Struct_7, 1>,
    vertex_count: u32,
    primitive_count: u32,
}
const positions: array<vec4<f32>, 3> = array<vec4<f32>, 3>(vec4<f32>(0.0f, 1.0f, 0.0f, 1.0f), vec4<f32>(-(1.0f), -(1.0f), 0.0f, 1.0f), vec4<f32>(1.0f, -(1.0f), 0.0f, 1.0f));
const colors: array<vec4<f32>, 3> = array<vec4<f32>, 3>(vec4<f32>(0.0f, 1.0f, 0.0f, 1.0f), vec4<f32>(0.0f, 0.0f, 1.0f, 1.0f), vec4<f32>(1.0f, 0.0f, 0.0f, 1.0f));
var<workgroup> workgroupData: f32;
var<private> taskPayload: Struct_3;
var<workgroup> mesh_output: Struct_11;

fn helper_reader() -> bool {
    return taskPayload.visible;
}

fn helper_writer(value: bool) {
    taskPayload.visible = value;
}

fn ts_divergent(thread_id: vec3<u32>) -> vec3<u32> {
    if ((thread_id[0] == 0)) {
        taskPayload.colorMask = vec4<f32>(1.0f, 1.0f, 0.0f, 1.0f);
        taskPayload.visible = true;
        return vec3<f32>(1, 1, 1);
    }
    return vec3<f32>(2, 2, 2);
}

fn ts_main() -> vec3<u32> {
    workgroupData = 1.0f;
    taskPayload.colorMask = vec4<f32>(1.0f, 1.0f, 0.0f, 1.0f);
    helper_writer(true);
    taskPayload.visible = helper_reader();
    return vec3<f32>(1, 1, 1);
}

fn ms_main() {
    mesh_output.vertex_count = 3;
    mesh_output.primitive_count = 1;
    workgroupData = 2.0f;
    mesh_output.vertices[0].position = positions[0];
    mesh_output.vertices[0].color = (colors[0] * taskPayload.colorMask);
    mesh_output.vertices[1].position = positions[1];
    mesh_output.vertices[1].color = (colors[1] * taskPayload.colorMask);
    mesh_output.vertices[2].position = positions[2];
    mesh_output.vertices[2].color = (colors[2] * taskPayload.colorMask);
    mesh_output.primitives[0].indices = vec3<u32>(0, 1, 2);
    mesh_output.primitives[0].cull = !(helper_reader());
    mesh_output.primitives[0].colorMask = vec4<f32>(1.0f, 0.0f, 1.0f, 1.0f);
}

fn ms_no_ts() {
    mesh_output.vertex_count = 3;
    mesh_output.primitive_count = 1;
    workgroupData = 2.0f;
    mesh_output.vertices[0].position = positions[0];
    mesh_output.vertices[0].color = colors[0];
    mesh_output.vertices[1].position = positions[1];
    mesh_output.vertices[1].color = colors[1];
    mesh_output.vertices[2].position = positions[2];
    mesh_output.vertices[2].color = colors[2];
    mesh_output.primitives[0].indices = vec3<u32>(0, 1, 2);
    mesh_output.primitives[0].cull = false;
    mesh_output.primitives[0].colorMask = vec4<f32>(1.0f, 0.0f, 1.0f, 1.0f);
}

fn ms_divergent(thread_id: vec3<u32>) {
    if ((thread_id[0] == 0)) {
        mesh_output.vertex_count = 3;
        mesh_output.primitive_count = 1;
        workgroupData = 2.0f;
        mesh_output.vertices[0].position = positions[0];
        mesh_output.vertices[0].color = colors[0];
        mesh_output.vertices[1].position = positions[1];
        mesh_output.vertices[1].color = colors[1];
        mesh_output.vertices[2].position = positions[2];
        mesh_output.vertices[2].color = colors[2];
        mesh_output.primitives[0].indices = vec3<u32>(0, 1, 2);
        mesh_output.primitives[0].cull = false;
        mesh_output.primitives[0].colorMask = vec4<f32>(1.0f, 0.0f, 1.0f, 1.0f);
        return;
    }
}

@fragment
fn fs_main(vertex: Struct_4, primitive: Struct_8) -> vec4<f32> {
    return (vertex.color * primitive.colorMask);
}
