// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    dummy: u32,
}
struct Struct_4 {
    @builtin(position) position: vec4<f32>,
}
struct Struct_6 {
    indices: vec2<u32>,
}
struct Struct_9 {
    vertices: array<Struct_4, 2>,
    primitives: array<Struct_6, 1>,
    vertex_count: u32,
    primitive_count: u32,
}
var<private> taskPayload: Struct_1;
var<workgroup> mesh_output: Struct_9;

fn ts_main() -> vec3<u32> {
    return vec3<f32>(1, 1, 1);
}

fn ms_main() {
}
