// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    x: i32,
}
const Value: i32 = 1;
@group(0) @binding(0)
var Texture: texture_2d<f32>;
@group(0) @binding(1)
var Sampler: sampler;

fn statement() {
}

fn returns() -> Struct_1 {
    return Struct_1(Value);
}

fn call() {
    statement();
    var x: Struct_1 = returns();
    var vf: f32 = f32(Value);
    var s: vec4<f32> = textureSample(Texture, Sampler, vec2<f32>(vf));
}

@fragment
fn main() {
    call();
    statement();
    returns();
}
