// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    position: vec2<f32>,
}
struct Struct_3 {
    position: vec2<f32>,
}
struct Struct_5 {
    @builtin(position) position: vec4<f32>,
}

@vertex
fn vs_main(vertex: Struct_2, note: Struct_3) -> Struct_5 {
    var out: Struct_5;
    return out;
}

@fragment
fn fs_main(in: Struct_5, note: Struct_3) -> vec4<f32> {
    var position: vec3<f32> = vec3<f32>(1.0f);
    return in.position;
}
