// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    @builtin(position) position: vec4<f32>,
    color: vec4<f32>,
    texcoord: vec2<f32>,
}
struct Struct_5 {
    position: vec4<f32>,
    normal: vec3<f32>,
    texcoord: vec2<f32>,
}
@group(0) @binding(0)
var<uniform> mvp_matrix: mat4x4<f32>;

fn do_lighting(position: vec4<f32>, normal: vec3<f32>) -> vec4<f32> {
    return vec4<f32>(0);
}

@vertex
fn render_vertex(v_in: Struct_5, @builtin(vertex_index) v_existing_id: u32) -> Struct_3 {
    var v_out: Struct_3;
    v_out.position = (v_in.position * mvp_matrix);
    v_out.color = do_lighting(v_in.position, v_in.normal);
    v_out.texcoord = v_in.texcoord;
    return v_out;
}
