// Generated by WebGPU-KTypes WGSL Backend

fn use_me() -> i32 {
    return 10;
}

fn use_return() -> i32 {
    return use_me();
}

fn use_assign_var() -> i32 {
    var q: i32 = use_me();
    return q;
}

fn use_assign_let() -> i32 {
    var q: i32 = use_me();
    return q;
}

fn use_phony_assign() {
    use_me();
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    use_return();
    use_assign_var();
    use_assign_let();
    use_phony_assign();
}
