// Generated by WebGPU-KTypes WGSL Backend
const v_f32_one: vec4<f32> = vec4<f32>(1.0f, 1.0f, 1.0f, 1.0f);
const v_f32_zero: vec4<f32> = vec4<f32>(0.0f, 0.0f, 0.0f, 0.0f);
const v_f32_half: vec4<f32> = vec4<f32>(0.5f, 0.5f, 0.5f, 0.5f);
const v_i32_one: vec4<i32> = vec4<i32>(1, 1, 1, 1);
const b_false: bool = false;
const b_true: bool = true;
const short_circuit_1_invalid_rhs: bool = (false && (sqrt(-(1)) != 0));
const short_circuit_2_invalid_rhs: bool = (false && ((0u + 1.0f) > 0));
const short_circuit_4: vec3<f32> = !((b_false || any(vec3<f32>(false, false, false))));
const short_circuit_3: bool = (b_false || b_true);

fn splat(m: f32, n: i32) -> vec4<f32> {
    var a: vec2<f32> = (((2.0f + vec2<f32>(m)) - 4.0f) / 8.0f);
    var b: vec4<i32> = (vec4<i32>(n) % 2);
    return (a.xyxy + vec4<f32>(b));
}

fn splat_assignment() -> vec2<f32> {
    var a: vec2<f32> = vec2<f32>(2.0f);
    a = 1.0f;
    a = 3.0f;
    a = 4.0f;
    return a;
}

fn bool_cast(x: vec3<f32>) -> vec3<f32> {
    var y: vec3<bool> = vec3<bool>(x);
    return vec3<f32>(y);
}

fn p() -> bool {
    return true;
}

fn q() -> bool {
    return false;
}

fn r() -> bool {
    return true;
}

fn s() -> bool {
    return false;
}

fn arithmetic() {
    var one_i: i32 = 1;
    var one_u: u32 = 1u;
    var one_f: f32 = 1.0f;
    var two_i: i32 = 2;
    var two_u: u32 = 2u;
    var two_f: f32 = 2.0f;
    var neg0: f32 = -(one_f);
    var neg1: vec2<f32> = -(vec2<f32>(one_i));
    var neg2: vec2<f32> = -(vec2<f32>(one_f));
    var add0: i32 = (two_i + one_i);
    var add1: u32 = (two_u + one_u);
    var add2: f32 = (two_f + one_f);
    var add3: vec2<f32> = (vec2<f32>(two_i) + vec2<f32>(one_i));
    var add4: vec3<f32> = (vec3<f32>(two_u) + vec3<f32>(one_u));
    var add5: vec4<f32> = (vec4<f32>(two_f) + vec4<f32>(one_f));
    var sub0: i32 = (two_i - one_i);
    var sub1: u32 = (two_u - one_u);
    var sub2: f32 = (two_f - one_f);
    var sub3: vec2<f32> = (vec2<f32>(two_i) - vec2<f32>(one_i));
    var sub4: vec3<f32> = (vec3<f32>(two_u) - vec3<f32>(one_u));
    var sub5: vec4<f32> = (vec4<f32>(two_f) - vec4<f32>(one_f));
    var mul0: i32 = (two_i * one_i);
    var mul1: u32 = (two_u * one_u);
    var mul2: f32 = (two_f * one_f);
    var mul3: vec2<f32> = (vec2<f32>(two_i) * vec2<f32>(one_i));
    var mul4: vec3<f32> = (vec3<f32>(two_u) * vec3<f32>(one_u));
    var mul5: vec4<f32> = (vec4<f32>(two_f) * vec4<f32>(one_f));
    var div0: i32 = (two_i / one_i);
    var div1: u32 = (two_u / one_u);
    var div2: f32 = (two_f / one_f);
    var div3: vec2<f32> = (vec2<f32>(two_i) / vec2<f32>(one_i));
    var div4: vec3<f32> = (vec3<f32>(two_u) / vec3<f32>(one_u));
    var div5: vec4<f32> = (vec4<f32>(two_f) / vec4<f32>(one_f));
    var rem0: i32 = (two_i % one_i);
    var rem1: u32 = (two_u % one_u);
    var rem2: f32 = (two_f % one_f);
    var rem3: vec2<f32> = (vec2<f32>(two_i) % vec2<f32>(one_i));
    var rem4: vec3<f32> = (vec3<f32>(two_u) % vec3<f32>(one_u));
    var rem5: vec4<f32> = (vec4<f32>(two_f) % vec4<f32>(one_f));
    {
        var add0: vec2<f32> = (vec2<f32>(two_i) + one_i);
        var add1: vec2<f32> = (two_i + vec2<f32>(one_i));
        var add2: vec2<f32> = (vec2<f32>(two_u) + one_u);
        var add3: vec2<f32> = (two_u + vec2<f32>(one_u));
        var add4: vec2<f32> = (vec2<f32>(two_f) + one_f);
        var add5: vec2<f32> = (two_f + vec2<f32>(one_f));
        var sub0: vec2<f32> = (vec2<f32>(two_i) - one_i);
        var sub1: vec2<f32> = (two_i - vec2<f32>(one_i));
        var sub2: vec2<f32> = (vec2<f32>(two_u) - one_u);
        var sub3: vec2<f32> = (two_u - vec2<f32>(one_u));
        var sub4: vec2<f32> = (vec2<f32>(two_f) - one_f);
        var sub5: vec2<f32> = (two_f - vec2<f32>(one_f));
        var mul0: vec2<f32> = (vec2<f32>(two_i) * one_i);
        var mul1: vec2<f32> = (two_i * vec2<f32>(one_i));
        var mul2: vec2<f32> = (vec2<f32>(two_u) * one_u);
        var mul3: vec2<f32> = (two_u * vec2<f32>(one_u));
        var mul4: vec2<f32> = (vec2<f32>(two_f) * one_f);
        var mul5: vec2<f32> = (two_f * vec2<f32>(one_f));
        var div0: vec2<f32> = (vec2<f32>(two_i) / one_i);
        var div1: vec2<f32> = (two_i / vec2<f32>(one_i));
        var div2: vec2<f32> = (vec2<f32>(two_u) / one_u);
        var div3: vec2<f32> = (two_u / vec2<f32>(one_u));
        var div4: vec2<f32> = (vec2<f32>(two_f) / one_f);
        var div5: vec2<f32> = (two_f / vec2<f32>(one_f));
        var rem0: vec2<f32> = (vec2<f32>(two_i) % one_i);
        var rem1: vec2<f32> = (two_i % vec2<f32>(one_i));
        var rem2: vec2<f32> = (vec2<f32>(two_u) % one_u);
        var rem3: vec2<f32> = (two_u % vec2<f32>(one_u));
        var rem4: vec2<f32> = (vec2<f32>(two_f) % one_f);
        var rem5: vec2<f32> = (two_f % vec2<f32>(one_f));
    }
    var add: mat3x3<f32> = (mat3x3<f32>() + mat3x3<f32>());
    var sub: mat3x3<f32> = (mat3x3<f32>() - mat3x3<f32>());
    var mul_scalar0: mat3x3<f32> = (mat3x3<f32>() * one_f);
    var mul_scalar1: mat3x3<f32> = (two_f * mat3x3<f32>());
    var mul_vector0: vec4<f32> = (mat4x3<f32>() * vec4<f32>(one_f));
    var mul_vector1: vec3<f32> = (vec3<f32>(two_f) * mat4x3<f32>());
    var mul: mat4x3<f32> = (mat4x3<f32>() * mat3x4<f32>());
    var prevent_const_eval: i32;
    var wgpu_7437: i32 = (prevent_const_eval + -(2147483648));
}

fn bit() {
    var one_i: i32 = 1;
    var one_u: u32 = 1u;
    var two_i: i32 = 2;
    var two_u: u32 = 2u;
    var flip0: i32 = ~(one_i);
    var flip1: u32 = ~(one_u);
    var flip2: vec2<f32> = ~(vec2<f32>(one_i));
    var flip3: vec3<f32> = ~(vec3<f32>(one_u));
    var or0: i32 = (two_i | one_i);
    var or1: u32 = (two_u | one_u);
    var or2: vec2<f32> = (vec2<f32>(two_i) | vec2<f32>(one_i));
    var or3: vec3<f32> = (vec3<f32>(two_u) | vec3<f32>(one_u));
    var and0: i32 = (two_i & one_i);
    var and1: u32 = (two_u & one_u);
    var and2: vec2<f32> = (vec2<f32>(two_i) & vec2<f32>(one_i));
    var and3: vec3<f32> = (vec3<f32>(two_u) & vec3<f32>(one_u));
    var xor0: i32 = (two_i ^ one_i);
    var xor1: u32 = (two_u ^ one_u);
    var xor2: vec2<f32> = (vec2<f32>(two_i) ^ vec2<f32>(one_i));
    var xor3: vec3<f32> = (vec3<f32>(two_u) ^ vec3<f32>(one_u));
    var shl0: i32 = (two_i << one_u);
    var shl1: u32 = (two_u << one_u);
    var shl2: vec2<f32> = (vec2<f32>(two_i) << vec2<f32>(one_u));
    var shl3: vec3<f32> = (vec3<f32>(two_u) << vec3<f32>(one_u));
    var shr0: i32 = (two_i >> one_u);
    var shr1: u32 = (two_u >> one_u);
    var shr2: vec2<f32> = (vec2<f32>(two_i) >> vec2<f32>(one_u));
    var shr3: vec3<f32> = (vec3<f32>(two_u) >> vec3<f32>(one_u));
}

fn comparison() {
    var one_i: i32 = 1;
    var one_u: u32 = 1u;
    var one_f: f32 = 1.0f;
    var two_i: i32 = 2;
    var two_u: u32 = 2u;
    var two_f: f32 = 2.0f;
    var eq0: bool = (two_i == one_i);
    var eq1: bool = (two_u == one_u);
    var eq2: bool = (two_f == one_f);
    var eq3: vec2<bool> = (vec2<f32>(two_i) == vec2<f32>(one_i));
    var eq4: vec3<bool> = (vec3<f32>(two_u) == vec3<f32>(one_u));
    var eq5: vec4<bool> = (vec4<f32>(two_f) == vec4<f32>(one_f));
    var neq0: bool = (two_i != one_i);
    var neq1: bool = (two_u != one_u);
    var neq2: bool = (two_f != one_f);
    var neq3: vec2<bool> = (vec2<f32>(two_i) != vec2<f32>(one_i));
    var neq4: vec3<bool> = (vec3<f32>(two_u) != vec3<f32>(one_u));
    var neq5: vec4<bool> = (vec4<f32>(two_f) != vec4<f32>(one_f));
    var lt0: bool = (two_i < one_i);
    var lt1: bool = (two_u < one_u);
    var lt2: bool = (two_f < one_f);
    var lt3: vec2<bool> = (vec2<f32>(two_i) < vec2<f32>(one_i));
    var lt4: vec3<bool> = (vec3<f32>(two_u) < vec3<f32>(one_u));
    var lt5: vec4<bool> = (vec4<f32>(two_f) < vec4<f32>(one_f));
    var lte0: bool = (two_i <= one_i);
    var lte1: bool = (two_u <= one_u);
    var lte2: bool = (two_f <= one_f);
    var lte3: vec2<bool> = (vec2<f32>(two_i) <= vec2<f32>(one_i));
    var lte4: vec3<bool> = (vec3<f32>(two_u) <= vec3<f32>(one_u));
    var lte5: vec4<bool> = (vec4<f32>(two_f) <= vec4<f32>(one_f));
    var gt0: bool = (two_i > one_i);
    var gt1: bool = (two_u > one_u);
    var gt2: bool = (two_f > one_f);
    var gt3: vec2<bool> = (vec2<f32>(two_i) > vec2<f32>(one_i));
    var gt4: vec3<bool> = (vec3<f32>(two_u) > vec3<f32>(one_u));
    var gt5: vec4<bool> = (vec4<f32>(two_f) > vec4<f32>(one_f));
    var gte0: bool = (two_i >= one_i);
    var gte1: bool = (two_u >= one_u);
    var gte2: bool = (two_f >= one_f);
    var gte3: vec2<bool> = (vec2<f32>(two_i) >= vec2<f32>(one_i));
    var gte4: vec3<bool> = (vec3<f32>(two_u) >= vec3<f32>(one_u));
    var gte5: vec4<bool> = (vec4<f32>(two_f) >= vec4<f32>(one_f));
}

fn assignment() {
    var zero_i: i32 = 0;
    var one_i: i32 = 1;
    var one_u: u32 = 1u;
    var two_u: u32 = 2u;
    var a: i32 = one_i;
    a = one_i;
    a = one_i;
    a = a;
    a = a;
    a = one_i;
    a = zero_i;
    a = zero_i;
    a = zero_i;
    a = two_u;
    a = one_u;
    a = (a + 1);
    a = (a - 1);
    var vec0: vec3<i32> = vec3<i32>();
    vec0[one_i] = (vec0[one_i] + 1);
    vec0[one_i] = (vec0[one_i] - 1);
}

fn negation_avoids_prefix_decrement() {
    var i: i32 = 1;
    var i0: i32 = -(i);
    var i1: i32 = -(-(i));
    var i2: i32 = -(-(i));
    var i3: i32 = -(-(i));
    var i4: i32 = -(-(-(i)));
    var i5: i32 = -(-(-(-(i))));
    var i6: i32 = -(-(-(-(-(i)))));
    var i7: i32 = -(-(-(-(-(i)))));
    var f: f32 = 1.0f;
    var f0: f32 = -(f);
    var f1: f32 = -(-(f));
    var f2: f32 = -(-(f));
    var f3: f32 = -(-(f));
    var f4: f32 = -(-(-(f)));
    var f5: f32 = -(-(-(-(f))));
    var f6: f32 = -(-(-(-(-(f)))));
    var f7: f32 = -(-(-(-(-(f)))));
}

fn builtins() -> vec4<f32> {
    var condition: bool = true;
    var s1: i32 = select(0, 1, condition);
    var s2: vec4<f32> = select(v_f32_zero, v_f32_one, condition);
    var s3: vec4<f32> = select(v_f32_one, v_f32_zero, vec4<bool>(false, false, false, false));
    var m1: vec4<f32> = mix(v_f32_zero, v_f32_one, v_f32_half);
    var m2: vec4<f32> = mix(v_f32_zero, v_f32_one, 0.1f);
    var b1: f32 = bitcast<f32>(v_i32_one[0]);
    var b2: vec4<f32> = bitcast<vec4<f32>>(v_i32_one);
    var v_i32_zero: vec4<i32> = vec4<i32>(v_f32_zero);
    return (((((vec4<f32>((vec4<i32>(s1) + v_i32_zero)) + s2) + m1) + m2) + b1) + b2);
}

fn logical() {
    var t: bool = true;
    var f: bool = false;
    var neg0: bool = !(t);
    var neg1: vec2<f32> = !(vec2<f32>(t));
    var or: bool = (t || f);
    var and: bool = (t && f);
    var bitwise_or0: bool = (t | f);
    var bitwise_or1: vec3<f32> = (vec3<f32>(t) | vec3<f32>(f));
    var bitwise_and0: bool = (t & f);
    var bitwise_and1: vec4<f32> = (vec4<f32>(t) & vec4<f32>(f));
    var short_circuit_1_invalid: bool = (false && (sqrt(-(1)) != 0));
    var short_circuit_2_invalid_rhs: bool = (false && ((0u + 1.0f) > 0));
    var short_circuit_3: bool = (b_false || b_true);
    var short_circuit_4: vec3<f32> = !((b_false || any(vec3<f32>(false, false, false))));
    var short_circuit_5: vec3<f32> = !((f || any(vec3<f32>(false, false, false))));
    var short_circuit_6: bool = ((p() || q()) && (r() || s()));
    var short_circuit_7: bool = (true || q());
}

@compute
@workgroup_size(1, 1, 1)
fn main(@builtin(workgroup_id) id: vec3<u32>) {
    builtins();
    splat(f32(id[0]), i32(id[1]));
    splat_assignment();
    bool_cast(v_f32_one.xyz);
    logical();
    arithmetic();
    bit();
    comparison();
    assignment();
    negation_avoids_prefix_decrement();
}
