// Generated by WebGPU-KTypes WGSL Backend
override has_point_light: bool = true;
override specular_param: f32 = 2.3f;
override gain: f32;
override width: f32 = 0.0f;
override depth: f32;
override inferred_f32: f32 = 2.718f;
override auto_conversion: u32 = 0;
var<private> store_override: f32;
var<private> gain_x_10: f32 = (gain * 10.0f);
override height: f32 = (2 * depth);

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var t: f32 = (height * 5);
    var a: bool = !(has_point_light);
    var x: bool = a;
    var gain_x_100: f32 = (gain_x_10 * 10.0f);
    store_override = gain;
    _ = specular_param;
    _ = width;
    _ = inferred_f32;
    _ = auto_conversion;
}
