// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    chunk: vec3<i32>,
    texture_index: u32,
}
struct Struct_6 {
    @builtin(position) clip_position: vec4<f32>,
}

@vertex
fn vs_main(in: Struct_3) -> Struct_6 {
    var out: Struct_6;
    var position: vec3<f32> = vec3<f32>((in.chunk - vec3<i32>(5)));
    return out;
}
