// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<uniform> binding: f32;

fn five() -> i32 {
    return 5;
}

@compute
@workgroup_size(1, 1, 1)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
    _ = binding;
    _ = binding;
    var a: i32 = 5;
    _ = a;
    five();
    var b: i32 = five();
    var phony: f32 = binding;
}
