// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    a: array<vec4<f32>, 10>,
}
struct Struct_5 {
    a: array<vec4<f32>, 20>,
}
@group(0) @binding(2)
var image_2d_array: texture_2d_array<f32>;
var<workgroup> in_workgroup: array<f32, 30>;
var<private> in_private: array<f32, 40>;
@group(0) @binding(0)
var<storage> in_storage: Struct_3;
@group(0) @binding(1)
var<uniform> in_uniform: Struct_5;

fn mock_function(c: vec2<i32>, i: i32, l: i32) -> vec4<f32> {
    var in_function: array<vec4<f32>, 2> = array<vec4<f32>, 2>(vec4<f32>(0.707f, 0.0f, 0.0f, 1.0f), vec4<f32>(0.0f, 0.707f, 0.0f, 1.0f));
    return (((((in_storage.a[i] + in_uniform.a[i]) + textureLoad(image_2d_array, c, i, l)) + in_workgroup[i]) + in_private[i]) + in_function[i]);
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    mock_function(vec2<f32>(1, 2), 3, 4);
}
