// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    multiplier: f32,
}
struct Struct_3 {
    color: vec4<f32>,
}
var<private> im: Struct_1;

@vertex
fn vert_main(@location(0) pos: vec2<f32>, @builtin(instance_index) ii: u32, @builtin(vertex_index) vi: u32) -> vec4<f32> {
    return vec4<f32>((((f32(ii) * f32(vi)) * im.multiplier) * pos), 0.0f, 1.0f);
}

@fragment
fn main(in: Struct_3) -> vec4<f32> {
    return (in.color * im.multiplier);
}
