// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    uv: vec2<f32>,
    @builtin(position) position: vec4<f32>,
}
const c_scale: f32 = 1.2f;
@group(0) @binding(0)
var u_texture: texture_2d<f32>;
@group(0) @binding(1)
var u_sampler: sampler;

@fragment
fn fs_extra() -> vec4<f32> {
    return vec4<f32>(0.0f, 0.5f, 0.0f, 0.5f);
}

@vertex
fn vert_main(@location(0) pos: vec2<f32>, @location(1) uv: vec2<f32>) -> Struct_3 {
    return Struct_3(uv, vec4<f32>((c_scale * pos), 0.0f, 1.0f));
}

@fragment
fn frag_main(@location(0) uv: vec2<f32>) -> vec4<f32> {
    var color: vec4<f32> = textureSample(u_texture, u_sampler, uv);
    if ((color[3] == 0.0f)) {
        discard;
    }
    var premultiplied: vec4<f32> = (color[3] * color);
    return premultiplied;
}
