// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    visible: u32,
    normal: vec3<f32>,
}
struct Struct_8 {
    kind: u32,
    t: f32,
    instance_custom_data: u32,
    instance_index: u32,
    sbt_record_offset: u32,
    geometry_index: u32,
    primitive_index: u32,
    barycentrics: vec2<f32>,
    front_face: bool,
    object_to_world: mat4x3<f32>,
    world_to_object: mat4x3<f32>,
}
@group(0) @binding(0)
var<private> acc_struct: acceleration_structure;
@group(0) @binding(1)
var<storage, read_write> output: Struct_3;

fn query_loop(pos: vec3<f32>, dir: vec3<f32>, acs: acceleration_structure) -> Struct_8 {
    var rq: ray_query;
    rayQueryInitialize(&rq, acs, RayDesc(4u, 0, 0.1f, 100.0f, pos, dir));
    loop {
        if (rayQueryProceed(&rq)) {
        } else {
            break;
        }
    }
    return rayQueryGetCommittedIntersection(&rq);
}

fn RayDesc(arg_0: u32, arg_1: i32, arg_2: f32, arg_3: f32, arg_4: vec3<f32>, arg_5: vec3<f32>) -> u32 {
}

fn rayQueryInitialize(arg_0: ptr<function, ray_query>, arg_1: acceleration_structure, arg_2: u32) -> ptr<function, ray_query> {
}

fn rayQueryProceed(arg_0: ptr<function, ray_query>) -> bool {
}

fn rayQueryGetCommittedIntersection(arg_0: ptr<function, ray_query>) -> Struct_8 {
}

fn get_torus_normal(world_point: vec3<f32>, intersection: Struct_8) -> vec3<f32> {
    var local_point: vec4<f32> = (intersection.world_to_object * vec4<f32>(world_point, 1.0f));
    var point_on_guiding_line: vec2<f32> = (normalize(local_point.xy) * 2.4f);
    var world_point_on_guiding_line: vec4<f32> = (intersection.object_to_world * vec4<f32>(point_on_guiding_line, 0.0f, 1.0f));
    return normalize((world_point - world_point_on_guiding_line));
}

fn RayDesc(arg_0: u32, arg_1: i32, arg_2: f32, arg_3: f32, arg_4: vec3<f32>, arg_5: vec3<f32>) -> u32 {
}

fn rayQueryInitialize(arg_0: ptr<function, ray_query>, arg_1: acceleration_structure, arg_2: u32) -> ptr<function, ray_query> {
}

fn rayQueryGetCandidateIntersection(arg_0: ptr<function, ray_query>) -> Struct_8 {
}

fn rayQueryGenerateIntersection(arg_0: ptr<function, ray_query>, arg_1: f32) {
}

fn rayQueryConfirmIntersection(arg_0: ptr<function, ray_query>) {
}

fn rayQueryTerminate(arg_0: ptr<function, ray_query>) {
}

@compute
@workgroup_size(1, 1, 1)
fn main_candidate() {
    var pos: vec3<f32> = vec3<f32>(0.0f);
    var dir: vec3<f32> = vec3<f32>(0.0f, 1.0f, 0.0f);
    var rq: ray_query;
    rayQueryInitialize(&rq, acc_struct, RayDesc(4u, 0, 0.1f, 100.0f, pos, dir));
    var intersection: Struct_8 = rayQueryGetCandidateIntersection(&rq);
    if ((intersection.kind == 3u)) {
        rayQueryGenerateIntersection(&rq, 10.0f);
    } else {
        if ((intersection.kind == 1u)) {
            rayQueryConfirmIntersection(&rq);
        } else {
            rayQueryTerminate(&rq);
        }
    }
}

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var pos: vec3<f32> = vec3<f32>(0.0f);
    var dir: vec3<f32> = vec3<f32>(0.0f, 1.0f, 0.0f);
    var intersection: Struct_8 = query_loop(pos, dir, acc_struct);
    output.visible = u32((intersection.kind == 0u));
    output.normal = get_torus_normal((dir * intersection.t), intersection);
}
