// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var texture: texture_depth_cube_array;
@group(0) @binding(1)
var texture_sampler: sampler_comparison;

@fragment
fn main() -> f32 {
    var pos: vec3<f32> = vec3<f32>(0.0f);
    var array_index: i32 = 0;
    var depth: f32 = 0.0f;
    return textureSampleCompareLevel(texture, texture_sampler, pos, array_index, depth);
}
