// Generated by WebGPU-KTypes WGSL Backend

@compute
@workgroup_size(1, 1, 1)
fn main() {
    select(1, 2.0f, false);
    var x0: vec2<f32> = vec2<f32>(1, 2);
    var i1: vec2<f32> = select(vec2<f32>(1.0f, 0.0f), vec2<f32>(0.0f, 1.0f), (x0[0] < x0[1]));
}
