// Generated by WebGPU-KTypes WGSL Backend

fn derivatives() {
    var x: f32 = dpdx(0.0f);
    var y: f32 = dpdy(0.0f);
    var width: f32 = fwidth(0.0f);
}

fn barriers() {
    storageBarrier();
    workgroupBarrier();
    textureBarrier();
}

@fragment
fn fragment() -> vec4<f32> {
    derivatives();
    return vec4<f32>();
}

@compute
@workgroup_size(1, 1, 1)
fn compute() {
    barriers();
}
