// Generated by WebGPU-KTypes WGSL Backend
struct Struct_4 {
    view_proj: mat4x4<f32>,
    num_lights: vec4<u32>,
}
struct Struct_6 {
    world: mat4x4<f32>,
    color: vec4<f32>,
}
struct Struct_8 {
    @builtin(position) proj_position: vec4<f32>,
    world_normal: vec3<f32>,
    world_position: vec4<f32>,
}
struct Struct_9 {
    proj: mat4x4<f32>,
    pos: vec4<f32>,
    color: vec4<f32>,
}
@group(0) @binding(2)
var t_shadow: texture_depth_2d_array;
@group(0) @binding(3)
var sampler_shadow: sampler_comparison;
const c_ambient: vec3<f32> = vec3<f32>(0.05f, 0.05f, 0.05f);
const c_max_lights: u32 = 10u;
@group(0) @binding(0)
var<uniform> u_globals: Struct_4;
@group(1) @binding(0)
var<uniform> u_entity: Struct_6;
@group(0) @binding(1)
var<storage, read> s_lights: array<Struct_9>;
@group(0) @binding(1)
var<uniform> u_lights: array<Struct_9, 10>;

fn fetch_shadow(light_id: u32, homogeneous_coords: vec4<f32>) -> f32 {
    if ((homogeneous_coords[3] <= 0.0f)) {
        return 1.0f;
    }
    var flip_correction: vec2<f32> = vec2<f32>(0.5f, -(0.5f));
    var proj_correction: f32 = (1.0f / homogeneous_coords[3]);
    var light_local: vec2<f32> = (((homogeneous_coords.xy * flip_correction) * proj_correction) + vec2<f32>(0.5f, 0.5f));
    return textureSampleCompareLevel(t_shadow, sampler_shadow, light_local, i32(light_id), (homogeneous_coords[2] * proj_correction));
}

@vertex
fn vs_main(@location(0) position: vec4<i32>, @location(1) normal: vec4<i32>) -> Struct_8 {
    var w: mat4x4<f32> = u_entity.world;
    var world_pos: vec4<f32> = (u_entity.world * vec4<f32>(position));
    var out: Struct_8;
    out.world_normal = (mat3x3<f32>(w[0].xyz, w[1].xyz, w[2].xyz) * vec3<f32>(normal.xyz));
    out.world_position = world_pos;
    out.proj_position = (u_globals.view_proj * world_pos);
    return out;
}

@fragment
fn fs_main(in: Struct_8) -> vec4<f32> {
    var normal: vec3<f32> = normalize(in.world_normal);
    var color: vec3<f32> = c_ambient;
    {
        var i: u32 = 0u;
        loop {
            if ((i < min(u_globals.num_lights[0], c_max_lights))) {
                {
                    var light: Struct_9 = s_lights[i];
                    var shadow: f32 = fetch_shadow(i, (light.proj * in.world_position));
                    var light_dir: vec3<f32> = normalize((light.pos.xyz - in.world_position.xyz));
                    var diffuse: f32 = max(0.0f, dot(normal, light_dir));
                    color = ((shadow * diffuse) * light.color.xyz);
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
    return (vec4<f32>(color, 1.0f) * u_entity.color);
}

@fragment
fn fs_main_without_storage(in: Struct_8) -> vec4<f32> {
    var normal: vec3<f32> = normalize(in.world_normal);
    var color: vec3<f32> = c_ambient;
    {
        var i: u32 = 0u;
        loop {
            if ((i < min(u_globals.num_lights[0], c_max_lights))) {
                {
                    var light: Struct_9 = u_lights[i];
                    var shadow: f32 = fetch_shadow(i, (light.proj * in.world_position));
                    var light_dir: vec3<f32> = normalize((light.pos.xyz - in.world_position.xyz));
                    var diffuse: f32 = max(0.0f, dot(normal, light_dir));
                    color = ((shadow * diffuse) * light.color.xyz);
                }
                i = (i + 1u);
            } else {
                break;
            }
        }
    }
    return (vec4<f32>(color, 1.0f) * u_entity.color);
}
