// Generated by WebGPU-KTypes WGSL Backend
struct Struct_3 {
    @builtin(position) position: vec4<f32>,
    uv: vec3<f32>,
}
struct Struct_5 {
    proj_inv: mat4x4<f32>,
    view: mat4x4<f32>,
}
@group(0) @binding(1)
var r_texture: texture_cube<f32>;
@group(0) @binding(2)
var r_sampler: sampler;
@group(0) @binding(0)
var<uniform> r_data: Struct_5;

@fragment
fn fs_main(in: Struct_3) -> vec4<f32> {
    return textureSample(r_texture, r_sampler, in.uv);
}

@vertex
fn vs_main(@builtin(vertex_index) vertex_index: u32) -> Struct_3 {
    var tmp1: i32 = (i32(vertex_index) / 2);
    var tmp2: i32 = (i32(vertex_index) & 1);
    var pos: vec4<f32> = vec4<f32>(((f32(tmp1) * 4.0f) - 1.0f), ((f32(tmp2) * 4.0f) - 1.0f), 0.0f, 1.0f);
    var inv_model_view: mat3x3<f32> = transpose(mat3x3<f32>(r_data.view[0].xyz, r_data.view[1].xyz, r_data.view[2].xyz));
    var unprojected: vec4<f32> = (r_data.proj_inv * pos);
    return Struct_3(pos, (inv_model_view * unprojected.xyz));
}
