// Generated by WebGPU-KTypes WGSL Backend

fn test_any_and_all_for_bool() -> bool {
    var a: bool = any(true);
    return all(a);
}

@fragment
fn derivatives(@builtin(position) foo: vec4<f32>) -> vec4<f32> {
    var x: vec4<f32> = dpdxCoarse(foo);
    var y: vec4<f32> = dpdyCoarse(foo);
    var z: vec4<f32> = fwidthCoarse(foo);
    x = dpdxFine(foo);
    y = dpdyFine(foo);
    z = fwidthFine(foo);
    x = dpdx(foo);
    y = dpdy(foo);
    z = fwidth(foo);
    var a: bool = test_any_and_all_for_bool();
    return ((x + y) * z);
}
