// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    v3: vec3<f32>,
    f3: f32,
}
struct Struct_3 {
    f3_forces_padding: f32,
    v3_needs_padding: vec3<f32>,
    f3: f32,
}
@group(0) @binding(0)
var<uniform> no_padding_uniform: Struct_2;
@group(0) @binding(1)
var<storage, read_write> no_padding_storage: Struct_2;
@group(0) @binding(2)
var<uniform> needs_padding_uniform: Struct_3;
@group(0) @binding(3)
var<storage, read_write> needs_padding_storage: Struct_3;

@fragment
fn no_padding_frag(input: Struct_2) -> vec4<f32> {
    _ = input;
    return vec4<f32>(0.0f);
}

@vertex
fn no_padding_vert(input: Struct_2) -> vec4<f32> {
    _ = input;
    return vec4<f32>(0.0f);
}

@fragment
fn needs_padding_frag(input: Struct_3) -> vec4<f32> {
    _ = input;
    return vec4<f32>(0.0f);
}

@vertex
fn needs_padding_vert(input: Struct_3) -> vec4<f32> {
    _ = input;
    return vec4<f32>(0.0f);
}

@compute
@workgroup_size(16, 1, 1)
fn no_padding_comp() {
    var x: Struct_2;
    x = no_padding_uniform;
    x = no_padding_storage;
}

@compute
@workgroup_size(16, 1, 1)
fn needs_padding_comp() {
    var x: Struct_3;
    x = needs_padding_uniform;
    x = needs_padding_storage;
}
