// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    num_subgroups: u32,
    subgroup_size: u32,
}

@compute
@workgroup_size(1, 1, 1)
fn main(sizes: Struct_1, subgroup_id: u32, subgroup_invocation_id: u32) {
    subgroupBallot(((subgroup_invocation_id & 1u) == 1u));
    subgroupBallot();
    subgroupAll((subgroup_invocation_id != 0u));
    subgroupAny((subgroup_invocation_id == 0u));
    subgroupAdd(subgroup_invocation_id);
    subgroupMul(subgroup_invocation_id);
    subgroupMin(subgroup_invocation_id);
    subgroupMax(subgroup_invocation_id);
    subgroupAnd(subgroup_invocation_id);
    subgroupOr(subgroup_invocation_id);
    subgroupXor(subgroup_invocation_id);
    subgroupExclusiveAdd(subgroup_invocation_id);
    subgroupExclusiveMul(subgroup_invocation_id);
    subgroupInclusiveAdd(subgroup_invocation_id);
    subgroupInclusiveMul(subgroup_invocation_id);
    subgroupBroadcastFirst(subgroup_invocation_id);
    subgroupBroadcast(subgroup_invocation_id, 4u);
    subgroupShuffle(subgroup_invocation_id, ((sizes.subgroup_size - 1u) - subgroup_invocation_id));
    subgroupShuffleDown(subgroup_invocation_id, 1u);
    subgroupShuffleUp(subgroup_invocation_id, 1u);
    subgroupShuffleXor(subgroup_invocation_id, (sizes.subgroup_size - 1u));
    quadBroadcast(subgroup_invocation_id, 4u);
    quadSwapX(subgroup_invocation_id);
    quadSwapY(subgroup_invocation_id);
    quadSwapDiagonal(subgroup_invocation_id);
}
