// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var<storage, read_write> out: array<i32, 2>;

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var tmp: array<i32>;
    {
        var i: i32 = 0;
        loop {
            if ((i < 2)) {
                {
                    out[i] = tmp[i];
                }
                i = (i + 1);
            } else {
                break;
            }
        }
    }
}
