// Generated by WebGPU-KTypes WGSL Backend
@group(0) @binding(0)
var tex: texture_external;
@group(0) @binding(1)
var samp: sampler;

fn test(t: texture_external) -> vec4<f32> {
    var a: vec4<f32> = textureSampleBaseClampToEdge(t, samp, vec2<f32>(0.0f));
    var b: texture_external = textureLoad(t, vec2<f32>(0));
    var c: texture_external = textureLoad(t, vec2<f32>(0u));
    var d: vec2<u32> = textureDimensions(t);
    return (((a + b) + c) + vec2<f32>(d).xyxy);
}

@fragment
fn fragment_main() -> vec4<f32> {
    return test(tex);
}

@vertex
fn vertex_main() -> vec4<f32> {
    return test(tex);
}

@compute
@workgroup_size(1, 1, 1)
fn compute_main() {
    test(tex);
}
