// Generated by WebGPU-KTypes WGSL Backend

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var a: vec3<f32> = vec3<f32>(0.0f, 0.0f, 0.0f);
    var c: vec3<f32> = vec3<f32>(0.0f);
    var b: vec3<f32> = vec3<f32>(vec2<f32>(0.0f), 0.0f);
    var d: vec3<f32> = vec3<f32>(vec2<f32>(0.0f), 0.0f);
    var e: vec3<i32> = vec3<i32>(d);
    var f: mat2x2<f32> = mat2x2<f32>(1.0f, 2.0f, 3.0f, 4.0f);
    var g: mat3x3<f32> = mat3x3<f32>(a, a, a);
    var h: vec2<i32> = vec2<i32>();
    var i: mat2x2<f32> = mat2x2<f32>();
}
