// Generated by WebGPU-KTypes WGSL Backend
const g0: i32 = 1;
const g1: u32 = 1u;
const g2: f32 = 1.0f;
const g3: f32 = 1.0f;
const g4: vec4<i32> = vec4<i32>();
const g5: vec4<f32> = vec4<f32>(1);
const g6: mat2x2<f32> = mat2x2<f32>(vec2<f32>(), vec2<f32>());
const g7: mat2x2<f32> = mat2x2<f32>(vec2<f32>(1.0f, 1), vec2<f32>(1, 1));

@compute
@workgroup_size(1, 1, 1)
fn main() {
    var g0x: i32 = g0;
    var g2x: f32 = g2;
    var g7x: mat2x2<f32> = g7;
    var c0: i32 = 1;
    var c1: u32 = 1u;
    var c2: f32 = 1.0f;
    var c3: f32 = 1.0f;
    var c4: vec4<i32> = vec4<i32>();
    var c5: vec4<f32> = vec4<f32>(1);
    var c6: mat2x2<f32> = mat2x2<f32>(vec2<f32>(), vec2<f32>());
    var c7: mat2x2<f32> = mat2x2<f32>(vec2<f32>(1.0f, 1), vec2<f32>(1, 1));
    var c0x: i32 = c0;
    var c1x: u32 = c1;
    var c2x: f32 = c2;
    var c3x: f32 = c3;
    var c4x: vec4<i32> = c4;
    var c5x: vec4<f32> = c5;
    var c6x: mat2x2<f32> = c6;
    var c7x: mat2x2<f32> = c7;
    var l0: i32 = 1;
    var l1: u32 = 1u;
    var l2: f32 = 1.0f;
    var l3: f32 = 1.0f;
    var l4: vec4<i32> = vec4<i32>();
    var l5: vec4<f32> = vec4<f32>(1);
    var l6: mat2x2<f32> = mat2x2<f32>(vec2<f32>(), vec2<f32>());
    var l7: mat2x2<f32> = mat2x2<f32>(vec2<f32>(1.0f, 1), vec2<f32>(1, 1));
    var l0x: i32 = l0;
    var l1x: u32 = l1;
    var l2x: f32 = l2;
    var l3x: f32 = l3;
    var l4x: vec4<i32> = l4;
    var v0: i32 = 1;
    var v1: u32 = 1u;
    var v2: f32 = 1.0f;
    var v3: f32 = 1.0f;
    var v4: vec4<i32> = vec4<i32>();
    var v5: vec4<f32> = vec4<f32>(1);
    var v6: mat2x2<f32> = mat2x2<f32>(vec2<f32>(), vec2<f32>());
    var v7: mat2x2<f32> = mat2x2<f32>(vec2<f32>(1.0f, 1), vec2<f32>(1, 1));
}
