// Generated by WebGPU-KTypes WGSL Backend
struct Struct_1 {
    test_m: u32,
}
@group(0) @binding(0)
var<uniform> mvp_matrix: mat4x4<f32>;
var<workgroup> w_mem: mat2x2<f32>;
var<workgroup> w_mem2: mat2x2<f32>;
const test_c: u32 = 1;

fn test_f() {
}

fn test_g() {
}

@compute
@workgroup_size(1, 1, 1)
fn test_ep() {
    _ = w_mem2;
    _ = Struct_1();
    test_g();
}
