// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    value: f32,
    value2: f32,
    @builtin(position) position: vec4<f32>,
}

@fragment
fn fs_main(v_out: Struct_2) -> vec4<f32> {
    return vec4<f32>(v_out.value, v_out.value, v_out.value2, v_out.value2);
}
