// Generated by WebGPU-KTypes WGSL Backend
struct Struct_2 {
    @builtin(position) position: vec4<f32>,
    value: f32,
    unused_value2: vec4<f32>,
    unused_value: f32,
    value2: f32,
}

@vertex
fn vs_main() -> Struct_2 {
    return Struct_2(vec4<f32>(1.0f), 1.0f, vec4<f32>(2.0f), 1.0f, 0.5f);
}
