// Generated by WebGPU-KTypes WGSL Backend
struct Struct_6 {
    arr: array<u32, 512>,
    atom: atomic<i32>,
    atom_arr: array<array<atomic<i32>, 8>, 8>,
}
@group(0) @binding(0)
var<storage, read_write> output: array<u32, 512>;
var<workgroup> w_mem: Struct_6;

@compute
@workgroup_size(1, 1, 1)
fn main() {
    output = w_mem.arr;
}
