// Generated by WebGPU-KTypes WGSL Backend
const SIZE: u32 = 128u;
var<workgroup> arr_i32: array<i32, 128>;

@compute
@workgroup_size(4, 1, 1)
fn test_workgroupUniformLoad(@builtin(workgroup_id) workgroup_id: vec3<u32>) {
    var x: ptr<function, i32> = &arr_i32[workgroup_id[0]];
    var val: ptr<function, i32> = workgroupUniformLoad(x);
    if ((val > 10)) {
        workgroupBarrier();
    }
}
