[versions]
# Core Tooling
kotlin = "2.4.10"
agp = "9.0.0"
dokka = "2.2.0"
maven-publish = "0.36.0"

# Libraries
kotlinx-serialization = "1.8.0"
kotlinx-serialization-json = "1.11.0"
logging = "7.0.4"
kotest = "6.1.11"
kover = "0.9.8"
clikt = "5.0.2"
logback = "1.5.16"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
kotest-core = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
kotlin-dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[bundles]
kotest = ["kotest-core", "kotest-assertions"]
