package org.graphiks.wgsl.wgsl

import org.graphiks.wgsl.arena.Handle
import org.graphiks.wgsl.back.WgslOptions
import org.graphiks.wgsl.back.WriterBase
import org.graphiks.wgsl.back.BackendWriter
import org.graphiks.wgsl.ir.*
import org.graphiks.wgsl.ir.Function
import org.graphiks.wgsl.proc.Layouter
import org.graphiks.wgsl.proc.Namer
import org.graphiks.wgsl.valid.ModuleInfo

class WgslWriter(
    output: StringBuilder,
    module: Module,
    moduleInfo: ModuleInfo,
    options: WgslOptions,
    namer: Namer,
    layouter: Layouter
) : WriterBase<WgslOptions>(output, module, moduleInfo, options, namer, layouter), BackendWriter<WgslOptions> {

    override fun write(module: Module, moduleInfo: ModuleInfo): String {
        return WgslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter).write()
    }

    override fun withOptions(options: WgslOptions): BackendWriter<WgslOptions> {
        return WgslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter)
    }

    override fun canHandle(module: Module, moduleInfo: ModuleInfo): Boolean = true

    override fun writeHeader() {
        writeLine("// Generated by WebGPU-KTypes WGSL Backend")
    }

    override fun writeStructType(handle: Handle<Type>, structInner: TypeInner.Struct, name: String) {
        writeLine("struct $name {")
        indent {
            for (member in structInner.members) {
                val memberName = member.name
                val typeName = getTypeName(member.type)
                val attribute = member.binding?.let { writeStructMemberBindingAttribute(it)?.let { attr -> "$attr " } } ?: ""
                writeLine("$attribute$memberName: $typeName,")
            }
        }
        writeLine("}")
    }

    override fun writeFunctionSignature(func: Function, name: String) {
        val returnType = func.returnType?.let { " -> ${getTypeName(it)}" } ?: ""
        write("fn $name(")
        func.parameters.forEachIndexed { i, param ->
            if (i > 0) write(", ")
            val typeName = getTypeName(param.type)
            write("${param.name}: $typeName")
        }
        write(")$returnType")
    }

    override fun writeGlobalVariables() {
        module.globalVariables.forEachWithHandle { handle, variable ->
            val name = getGlobalVariableName(handle)
            val typeName = getTypeName(variable.type)
            val binding = variable.binding
            if (binding != null) {
                writeLine("@group(${binding.group}) @binding(${binding.index})")
            }
            val init = variable.init?.let { " = ${writeExpression(it)}" } ?: ""
            when (variable.declaration) {
                GlobalVariableDeclaration.Const -> {
                    writeLine("const $name: $typeName$init;")
                    return@forEachWithHandle
                }
                GlobalVariableDeclaration.Override -> {
                    writeLine("override $name: $typeName$init;")
                    return@forEachWithHandle
                }
                GlobalVariableDeclaration.Var -> {}
            }
            val space = when (variable.storageClass) {
                StorageClass.Uniform -> "<uniform>"
                StorageClass.Storage -> {
                    val mode = when (variable.accessMode) {
                        AccessMode.Read -> ", read"
                        AccessMode.Write -> ", write"
                        AccessMode.ReadWrite -> ", read_write"
                        null -> ""
                    }
                    "<storage$mode>"
                }
                StorageClass.Workgroup -> "<workgroup>"
                StorageClass.Private -> "<private>"
                StorageClass.PushConstant -> "<push_constant>"
                StorageClass.Function -> "<function>"
                StorageClass.Handle -> ""
            }
            writeLine("var$space $name: $typeName$init;")
        }
    }

    override fun writeEntryPoint(ep: EntryPoint, index: Int) {
        writeLine()
        val stage = ep.stage.name.lowercase()
        writeLine("@$stage")
        val workgroupSize = ep.workgroupSize
        if (ep.stage == ShaderStage.Compute && workgroupSize != null) {
            val (x, y, z) = workgroupSize
            writeLine("@workgroup_size($x, $y, $z)")
        }
        val func = module.functions[ep.function]
        val returnType = func.returnType?.let { " -> ${getTypeName(it)}" } ?: ""

        currentFunction = func

        write("fn ${ep.name}(")

        val args = mutableListOf<String>()
        func.parameters.forEach { param ->
            val typeName = getTypeName(param.type)
            val binding = param.binding
            if (binding is BindingAttribute.Builtin) {
                args.add("@builtin(${getWgslBuiltinName(binding.builtin)}) ${param.name}: $typeName")
            } else if (binding is BindingAttribute.Location) {
                args.add("@location(${binding.location}) ${param.name}: $typeName")
            } else {
                args.add("${param.name}: $typeName")
            }
        }

        write(args.joinToString(", "))
        writeLine(")$returnType {")
        indent {
            writeBlock(func.body)
        }
        writeLine("}")

        currentFunction = null
    }

    override fun writeFunction(func: Function, handle: Handle<Function>) {
        val isEntryPoint = module.entryPoints.any { it.function == handle }
        if (isEntryPoint) return // written via writeEntryPoint
        if (isEmptyNativeWgslBuiltinStub(func)) return
        super.writeFunction(func, handle)
    }

    private fun isEmptyNativeWgslBuiltinStub(func: Function): Boolean {
        val block = func.blocks.getOrNull(func.body) ?: return false
        return block.statements.isEmpty() && func.name in nativeWgslBuiltins
    }

    override fun getGlobalVariableName(handle: Handle<GlobalVariable>): String {
        val variable = module.globalVariables[handle]
        return variable.name.ifEmpty { "global_${handle.index}" }
    }

    override fun getLocalVariableName(handle: Handle<LocalVariable>): String {
        val variable = currentFunction?.localVariables?.get(handle)
        return variable?.name?.ifEmpty { null } ?: "local_${handle.index}"
    }

    override fun writeExpression(handle: Handle<Expression>): String {
        val expressions = currentFunction?.expressions ?: module.globalExpressions
        val expr = expressions[handle]

        if (expr.kind is ExpressionKind.ArrayLength) {
            val e = writeExpression((expr.kind as ExpressionKind.ArrayLength).expr)
            return "arrayLength(&$e)"
        }

        val kind = expr.kind
        if (kind is ExpressionKind.Unary && kind.operator == UnaryOperator.Negate) {
            val operand = expressions[kind.expr]
            val magnitude = ((operand.kind as? ExpressionKind.Literal)?.value as? LiteralValue.Scalar)
                ?.value
                ?.minimumIntegerMagnitude()
            if (magnitude != null) {
                return "-($magnitude)"
            }
        }

        return super.writeExpression(handle)
    }

    override fun writeSample(
        texture: String,
        sampler: String?,
        coordinate: String,
        level: SampleLevel?,
        depthRef: Handle<Expression>?
    ): String {
        return "textureSample($texture, ${sampler ?: "/* no sampler */"}, $coordinate)"
    }

    override fun writeTextureQuery(texture: String, query: TextureQueryKind): String {
        val method = when (query) {
            TextureQueryKind.Size -> "textureDimensions($texture)"
            TextureQueryKind.SizeLevel -> "textureDimensions($texture, level)" // TODO: level
            TextureQueryKind.NumLevels -> "textureNumLevels($texture)"
            TextureQueryKind.NumLayers -> "textureNumLayers($texture)"
            TextureQueryKind.NumSamples -> "textureNumSamples($texture)"
        }
        return method
    }

    private fun getWgslBuiltinName(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.VertexIndex -> "vertex_index"
        BuiltinValue.InstanceIndex -> "instance_index"
        BuiltinValue.FrontFacing -> "front_facing"
        BuiltinValue.PrimitiveIndex -> "primitive_index"
        BuiltinValue.SampleIndex -> "sample_index"
        BuiltinValue.SampleMask -> "sample_mask"
        BuiltinValue.ViewportIndex -> "viewport_index"
        BuiltinValue.ClipDistance -> "clip_distances"
        BuiltinValue.CullDistance -> "cull_distances"
        BuiltinValue.PointSize -> "point_size"
        BuiltinValue.ViewIndex -> "view_index"
        BuiltinValue.LocalInvocationId -> "local_invocation_id"
        BuiltinValue.LocalInvocationIndex -> "local_invocation_index"
        BuiltinValue.GlobalInvocationId -> "global_invocation_id"
        BuiltinValue.WorkgroupId -> "workgroup_id"
        BuiltinValue.NumWorkgroups -> "num_workgroups"
        BuiltinValue.DrawIndex -> "draw_index"
        else -> builtin.name.lowercase()
    }

    private fun getWgslBuiltinType(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.Position -> "vec4<f32>"
        BuiltinValue.VertexIndex, BuiltinValue.InstanceIndex, BuiltinValue.SampleIndex -> "u32"
        BuiltinValue.FrontFacing -> "bool"
        BuiltinValue.LocalInvocationId, BuiltinValue.GlobalInvocationId,
        BuiltinValue.WorkgroupId, BuiltinValue.NumWorkgroups -> "vec3<u32>"
        BuiltinValue.LocalInvocationIndex, BuiltinValue.SampleMask -> "u32"
        else -> "u32"
    }

    private fun writeStructMemberBindingAttribute(binding: BindingAttribute): String? = when (binding) {
        is BindingAttribute.Builtin -> "@builtin(${getWgslBuiltinName(binding.builtin)})"
        is BindingAttribute.Location -> null
        is BindingAttribute.Interpolate -> null
    }

    override fun getScalarTypeName(scalar: TypeInner.Scalar): String {
        return when (scalar.kind) {
            ScalarKind.Bool -> "bool"
            ScalarKind.Sint -> "i${scalar.width * 8}"
            ScalarKind.Uint -> "u${scalar.width * 8}"
            ScalarKind.F32 -> "f32"
            ScalarKind.F16 -> "f16"
            ScalarKind.F64 -> "f64"
            else -> "/* unknown scalar */"
        }
    }

    private fun ScalarValue.minimumIntegerMagnitude(): String? {
        return when (this) {
            is ScalarValue.I32 -> value.takeIf { it == Int.MIN_VALUE }?.let { -(it.toLong()) }?.toString()
            is ScalarValue.I64 -> if (value == Long.MIN_VALUE) "9223372036854775808li" else null
            is ScalarValue.AbstractInt -> if (value == Long.MIN_VALUE) "9223372036854775808" else null
            else -> null
        }
    }

    override fun writeScalarValue(value: ScalarValue): String {
        return when (value) {
            is ScalarValue.I64 -> "${value.value}li"
            is ScalarValue.U64 -> "${value.value}lu"
            is ScalarValue.F16 -> writeNonFiniteFloat(value.value, "h") ?: super.writeScalarValue(value)
            is ScalarValue.F32 -> writeNonFiniteFloat(value.value, "f") ?: super.writeScalarValue(value)
            is ScalarValue.F64 -> writeNonFiniteFloat(value.value, "lf") ?: super.writeScalarValue(value)
            is ScalarValue.AbstractFloat -> writeNonFiniteFloat(value.value, "f") ?: super.writeScalarValue(value)
            else -> super.writeScalarValue(value)
        }
    }

    private fun writeNonFiniteFloat(value: Float, suffix: String): String? {
        return when {
            value.isNaN() -> "NaN$suffix"
            value == Float.POSITIVE_INFINITY -> "Infinity$suffix"
            value == Float.NEGATIVE_INFINITY -> "-Infinity$suffix"
            else -> null
        }
    }

    private fun writeNonFiniteFloat(value: Double, suffix: String): String? {
        return when {
            value.isNaN() -> "NaN$suffix"
            value == Double.POSITIVE_INFINITY -> "Infinity$suffix"
            value == Double.NEGATIVE_INFINITY -> "-Infinity$suffix"
            else -> null
        }
    }

    override fun getTypeName(handle: Handle<Type>): String {
        val type = module.types[handle]
        return when (val inner = type.inner) {
            is TypeInner.Scalar -> getScalarTypeName(inner)
            is TypeInner.Vector -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "vec${inner.size.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Matrix -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "mat${inner.columns.ordinal + 2}x${inner.rows.ordinal + 2}<$scalarName>"
            }
            is TypeInner.Struct -> "Struct_${handle.index}"
            is TypeInner.Pointer -> {
                val baseName = getTypeName(inner.base)
                val space = inner.addressSpace.name.lowercase()
                val mode = when (inner.accessMode) {
                    AccessMode.Read -> ", read"
                    AccessMode.Write -> ", write"
                    AccessMode.ReadWrite -> ", read_write"
                    null -> ""
                }
                "ptr<$space, $baseName$mode>"
            }
            is TypeInner.ValuePointer -> {
                val baseName = getTypeName(inner.base)
                "ptr<function, $baseName>"
            }
            is TypeInner.Array -> {
                val elementTypeName = getTypeName(inner.element)
                val sizeStr = when (val size = inner.size) {
                    is ArraySize.Constant -> size.value.toString()
                    is ArraySize.Dynamic -> ""
                }
                if (sizeStr.isNotEmpty()) "array<$elementTypeName, $sizeStr>" else "array<$elementTypeName>"
            }
            is TypeInner.Atomic -> "atomic<${getTypeName(inner.inner)}>"
            is TypeInner.Abstract -> {
                when (inner.scalar) {
                    ScalarKind.AbstractInt -> "abstract-int"
                    ScalarKind.AbstractFloat -> "abstract-float"
                    else -> "/* unknown abstract */"
                }
            }
            is TypeInner.Opaque -> inner.name
            else -> "/* unknown type */"
        }
    }

    override fun writeStatement(stmt: Statement) {
        when (stmt) {
            is Statement.Declare -> {
                val variable = currentFunction!!.localVariables[stmt.variable]
                val name = getLocalVariableName(stmt.variable)
                val typeName = getTypeName(variable.type)
                writeLine("var $name: $typeName;")
            }
            is Statement.Init -> {
                val variable = currentFunction!!.localVariables[stmt.variable]
                val name = getLocalVariableName(stmt.variable)
                val typeName = getTypeName(variable.type)
                val init = variable.init?.let { writeExpression(it) } ?: "/* error: no init */"
                writeLine("var $name: $typeName = $init;")
            }
            is Statement.Loop -> {
                writeLine("loop {")
                indent {
                    writeBlock(stmt.body)
                    val continuing = stmt.continuing
                    if (continuing != null) {
                        writeLine("continuing {")
                        indent {
                            writeBlock(continuing)
                        }
                        writeLine("}")
                    }
                }
                writeLine("}")
            }
            is Statement.Emit -> {
                stmt.range.toList().forEach { index ->
                    val handle = Handle<Expression>(index)
                    val expression = currentFunction!!.expressions[handle]
                    val rendered = writeExpression(handle)
                    when (expression.kind) {
                        is ExpressionKind.Call,
                        is ExpressionKind.BuiltinCall -> writeLine("$rendered;")
                        else -> writeLine("_ = $rendered;")
                    }
                }
            }
            else -> super.writeStatement(stmt)
        }
    }

    override fun writeRelational(function: RelationalFunction, arguments: List<String>): String {
        return "${function.name.lowercase()}(${arguments.joinToString()})"
    }

    override fun writeAtomic(pointer: String, function: AtomicFunction, arguments: List<String>): String {
        val wgslFunc = when (function) {
            AtomicFunction.Add -> "atomicAdd"
            AtomicFunction.Subtract -> "atomicSub"
            AtomicFunction.And -> "atomicAnd"
            AtomicFunction.Or -> "atomicOr"
            AtomicFunction.Xor -> "atomicXor"
            AtomicFunction.Min -> "atomicMin"
            AtomicFunction.Max -> "atomicMax"
            AtomicFunction.Exchange -> "atomicExchange"
            AtomicFunction.CompSwap -> "atomicCompareExchangeWeak"
        }
        return "$wgslFunc($pointer, ${arguments.joinToString()})"
    }

    override fun getBuiltinFunctionName(function: BuiltinFunction): String = when (function) {
        BuiltinFunction.Ln -> "log"
        else -> super.getBuiltinFunctionName(function)
    }
}

private val nativeWgslBuiltins = setOf(
    "abs", "acos", "acosh", "all", "any", "arrayLength", "asin", "asinh", "atan", "atan2", "atanh",
    "ceil", "clamp", "cos", "cosh", "countLeadingZeros", "countOneBits", "countTrailingZeros",
    "cross", "degrees", "determinant", "distance", "dot", "dot4I8Packed", "dot4U8Packed",
    "dpdx", "dpdxCoarse", "dpdxFine", "dpdy", "dpdyCoarse", "dpdyFine",
    "exp", "exp2", "extractBits", "faceForward", "firstLeadingBit", "firstTrailingBit",
    "floor", "fma", "fract", "frexp", "fwidth", "fwidthCoarse", "fwidthFine",
    "insertBits", "inverseSqrt", "ldexp", "length", "log", "log2", "max", "min", "mix", "modf",
    "normalize", "pack2x16float", "pack2x16snorm", "pack2x16unorm", "pack4x8snorm",
    "pack4x8unorm", "pow", "quantizeToF16", "radians", "reflect", "refract", "reverseBits",
    "round", "saturate", "select", "sign", "sin", "sinh", "smoothstep", "sqrt", "step",
    "tan", "tanh", "transpose", "trunc", "unpack2x16float", "unpack2x16snorm",
    "unpack2x16unorm", "unpack4x8snorm", "unpack4x8unorm",
    "textureDimensions", "textureGather", "textureGatherCompare", "textureLoad",
    "textureNumLayers", "textureNumLevels", "textureNumSamples", "textureSample",
    "textureSampleBaseClampToEdge", "textureSampleBias", "textureSampleCompare",
    "textureSampleCompareLevel", "textureSampleGrad", "textureSampleLevel", "textureStore",
    "textureAtomicAdd", "textureAtomicAnd", "textureAtomicMax", "textureAtomicMin",
    "textureAtomicOr", "textureAtomicXor",
    "atomicAdd", "atomicAnd", "atomicCompareExchangeWeak", "atomicExchange", "atomicLoad",
    "atomicMax", "atomicMin", "atomicOr", "atomicStore", "atomicSub", "atomicXor",
    "storageBarrier", "subgroupBarrier", "textureBarrier", "workgroupBarrier",
    "workgroupUniformLoad",
    "subgroupBallot", "subgroupAll", "subgroupAny", "subgroupAdd", "subgroupMul",
    "subgroupMin", "subgroupMax", "subgroupAnd", "subgroupOr", "subgroupXor",
    "subgroupExclusiveAdd", "subgroupExclusiveMul", "subgroupInclusiveAdd", "subgroupInclusiveMul",
    "subgroupBroadcastFirst", "subgroupBroadcast", "subgroupShuffle", "subgroupShuffleDown",
    "subgroupShuffleUp", "subgroupShuffleXor", "quadBroadcast", "quadSwapX", "quadSwapY",
    "quadSwapDiagonal",
)
