blank_issues_enabled: true
contact_links:
  - name: 💬 Discussion / Question
    url: https://github.com/ygdrasil-io/project-template/discussions
    about: For general questions and discussions.
  - name: 📖 Documentation
    url: https://ygdrasil-io.github.io/project-template/
    about: Please check the documentation before opening an issue.
