blank_issues_enabled: true
contact_links:
  - name: 💬 Discussion / Question
    url: https://github.com/Graphiks-org/wgsl4k/discussions
    about: For general questions and discussions.
  - name: 📖 Documentation
    url: https://graphiks-org.github.io/wgsl4k/
    about: Please check the documentation before opening an issue.
