package org.graphiks.wgsl.generator.hlsl

import org.graphiks.wgsl.arena.Handle
import org.graphiks.wgsl.back.HlslOptions
import org.graphiks.wgsl.back.BindingMap
import org.graphiks.wgsl.back.WriterBase
import org.graphiks.wgsl.back.BackendWriter
import org.graphiks.wgsl.ir.*
import org.graphiks.wgsl.ir.Function
import org.graphiks.wgsl.proc.Layouter
import org.graphiks.wgsl.proc.Namer
import org.graphiks.wgsl.valid.ModuleInfo

class HlslWriter(
    output: StringBuilder,
    module: Module,
    moduleInfo: ModuleInfo,
    options: HlslOptions,
    namer: Namer,
    layouter: Layouter
) : WriterBase<HlslOptions>(output, module, moduleInfo, options, namer, layouter), BackendWriter<HlslOptions> {

    override fun write(module: Module, moduleInfo: ModuleInfo): String {
        return HlslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter).write()
    }

    override fun withOptions(options: HlslOptions): BackendWriter<HlslOptions> {
        return HlslWriter(StringBuilder(), module, moduleInfo, options, namer, layouter)
    }

    override fun canHandle(module: Module, moduleInfo: ModuleInfo): Boolean = true

    override fun writeHeader() {
        writeLine("// Generated by WebGPU-KTypes HLSL Backend")
        writeLine("#pragma pack_matrix(column_major)")
        writeLine()
    }

    override fun writeStructType(handle: Handle<Type>, structInner: TypeInner.Struct, name: String) {
        writeLine("struct $name {")
        indent {
            for (member in structInner.members) {
                writeLine("${getTypeDeclarator(member.type, member.name)};")
            }
        }
        writeLine("};")
    }

    override fun writeFunctionSignature(func: Function, name: String) {
        val arguments = buildString {
            func.parameters.forEachIndexed { i, param ->
                if (i > 0) append(", ")
                append(getTypeDeclarator(param.type, param.name))
            }
        }
        val signature = func.returnType
            ?.let { getTypeDeclarator(it, "$name($arguments)") }
            ?: "void $name($arguments)"
        write(signature)
    }

    private fun getTypeDeclarator(type: Handle<Type>, name: String): String {
        return when (val inner = module.types[type].inner) {
            is TypeInner.Array -> {
                val size = when (val arraySize = inner.size) {
                    is ArraySize.Constant -> arraySize.value.toString()
                    is ArraySize.Dynamic -> ""
                }
                getTypeDeclarator(inner.element, "$name[$size]")
            }
            else -> "${getTypeName(type)} $name"
        }
    }

    override fun writeStatement(stmt: Statement) {
        when (stmt) {
            is Statement.Declare -> {
                val variable = currentFunction!!.localVariables[stmt.variable]
                val name = getLocalVariableName(stmt.variable)
                writeLine("${getTypeDeclarator(variable.type, name)};")
            }
            is Statement.Init -> {
                val variable = currentFunction!!.localVariables[stmt.variable]
                val name = getLocalVariableName(stmt.variable)
                val init = variable.init?.let { writeExpression(it) } ?: "/* error: no init */"
                writeLine("${getTypeDeclarator(variable.type, name)} = $init;")
            }
            else -> super.writeStatement(stmt)
        }
    }

    override fun writeGlobalVariables() {
        module.globalVariables.forEachWithHandle { handle, variable ->
            val name = getGlobalVariableName(handle)
            val binding = variable.binding
            if (binding != null) {
                val target = options.bindingMap[binding]
                val register = when (variable.storageClass) {
                    StorageClass.Uniform -> "register(b${target?.buffer ?: binding.index})"
                    StorageClass.Storage -> "register(u${target?.buffer ?: binding.index})"
                    // TODO: handle textures and samplers properly
                    else -> "register(t${target?.texture ?: binding.index})"
                }
                writeLine("${getTypeDeclarator(variable.type, name)} : $register;")
            } else {
                val init = variable.init?.let { " = ${writeExpression(it)}" } ?: ""
                writeLine("${getTypeDeclarator(variable.type, name)}$init;")
            }
        }
    }

    override fun writeFunction(func: Function, handle: Handle<Function>) {
        val ep = module.entryPoints.find { it.function == handle }
        if (ep != null) {
            writeEntryPoint(ep, 0)
        } else {
            super.writeFunction(func, handle)
        }
    }

    override fun writeEntryPoints() {
        // Do nothing, handled in writeFunction
    }

    override fun writeEntryPoint(ep: EntryPoint, index: Int) {
        writeLine()
        val inputStructName = writeInputStruct(ep)
        val outputStructName = writeOutputStruct(ep)

        val stageAttr = when (ep.stage) {
            ShaderStage.Vertex -> ""
            ShaderStage.Fragment -> ""
            ShaderStage.Compute -> {
                val (x, y, z) = ep.workgroupSize ?: listOf(1, 1, 1)
                "[numthreads($x, $y, $z)]"
            }
        }

        if (ep.stage == ShaderStage.Compute) {
            writeLine(stageAttr)
        }

        val func = module.functions[ep.function]
        currentFunction = func
        val returnType = outputStructName ?: (func.returnType?.let { getTypeName(it) } ?: "void")

        write("$returnType ${ep.name}(")

        val args = mutableListOf<String>()
        if (inputStructName != null) {
            args.add("$inputStructName stage_in")
        }

        // 1. Built-ins that are not in stage_in (like compute built-ins)
        func.parameters.forEach { param ->
            val binding = param.binding
            if (binding is BindingAttribute.Builtin && ep.stage == ShaderStage.Compute) {
                val hlslSemantic = getHlslSemantic(binding.builtin)
                val typeName = getHlslBuiltinType(binding.builtin)
                args.add("$typeName ${param.name} : $hlslSemantic")
            }
        }

        write(args.joinToString(", "))
        writeLine(") {")
        indent {
            if (outputStructName != null) {
                writeLine("$outputStructName stage_out;")
            }

            // Assign inputs to local variables or function arguments
            func.parameters.forEach { param ->
                val binding = param.binding
                if (binding is BindingAttribute.Location || (binding is BindingAttribute.Builtin && ep.stage != ShaderStage.Compute)) {
                    writeLine("${getTypeName(param.type)} ${param.name} = stage_in.${param.name};")
                }
            }

            writeBlock(func.body)

            if (outputStructName != null) {
                // If the return type was a struct, we need to map its fields to stage_out
                // This assumes the function body assigned values to something that will be returned
                // In a real writer, we'd need to handle this more carefully.
                // For now, let's assume the function returns a value that we assign to stage_out
                val returnExpr = func.result?.let { writeExpression(it) }
                if (returnExpr != null) {
                    writeLine("stage_out = $returnExpr;")
                }
                writeLine("return stage_out;")
            }
        }
        writeLine("}")
        currentFunction = null
    }

    protected fun writeInputStruct(ep: EntryPoint): String? {
        val func = module.functions[ep.function]
        val members = mutableListOf<String>()

        func.parameters.forEach { param ->
            val binding = param.binding
            if (binding is BindingAttribute.Location) {
                members.add("${getTypeDeclarator(param.type, param.name)} : TEXCOORD${binding.location};")
            } else if (binding is BindingAttribute.Builtin && ep.stage != ShaderStage.Compute) {
                val hlslSemantic = getHlslSemantic(binding.builtin)
                val typeName = getHlslBuiltinType(binding.builtin)
                members.add("$typeName ${param.name} : $hlslSemantic;")
            }
        }

        if (members.isEmpty()) return null

        val structName = "${ep.name}_Input"
        writeLine("struct $structName {")
        indent {
            members.forEach { writeLine(it) }
        }
        writeLine("};")
        return structName
    }

    protected fun writeOutputStruct(ep: EntryPoint): String? {
        val func = module.functions[ep.function]
        val returnTypeHandle = func.returnType ?: return null
        val returnType = module.types[returnTypeHandle]
        val inner = returnType.inner

        if (inner is TypeInner.Struct) {
            val structName = "${ep.name}_Output"
            writeLine("struct $structName {")
            indent {
                inner.members.forEach { member ->
                    val semantic = when (val binding = member.binding) {
                        is BindingAttribute.Builtin -> if (binding.builtin == BuiltinValue.Position) "SV_Position" else "SV_Target"
                        is BindingAttribute.Location -> "TEXCOORD${binding.location}"
                        else -> if (ep.stage == ShaderStage.Fragment) "SV_Target" else "COLOR"
                    }
                    writeLine("${getTypeDeclarator(member.type, member.name)} : $semantic;")
                }
            }
            writeLine("};")
            return structName
        } else if (ep.stage == ShaderStage.Vertex) {
            val structName = "${ep.name}_Output"
            writeLine("struct $structName {")
            indent {
                writeLine("float4 position : SV_Position;")
            }
            writeLine("};")
            return structName
        } else if (ep.stage == ShaderStage.Fragment) {
            val structName = "${ep.name}_Output"
            writeLine("struct $structName {")
            indent {
                val typeName = getTypeName(returnTypeHandle)
                writeLine("$typeName color : SV_Target;")
            }
            writeLine("};")
            return structName
        }
        return null
    }

    override fun writeLiteralValue(value: LiteralValue): String {
        return when (value) {
            is LiteralValue.Scalar -> writeScalarValue(value.value)
            is LiteralValue.Vector -> {
                val first = value.components.first()
                val prefix = when (first) {
                    is ScalarValue.F32 -> "float"
                    is ScalarValue.U32 -> "uint"
                    is ScalarValue.I32 -> "int"
                    is ScalarValue.Bool -> "bool"
                    else -> "float"
                }
                "$prefix${value.components.size}(${value.components.joinToString { writeScalarValue(it) }})"
            }
            is LiteralValue.Matrix -> "mat(...)"
        }
    }

    override fun writeSample(
        texture: String,
        sampler: String?,
        coordinate: String,
        level: SampleLevel?,
        depthRef: Handle<Expression>?
    ): String {
        return when (level) {
            is SampleLevel.Zero -> "$texture.SampleLevel($sampler, $coordinate, 0)"
            is SampleLevel.MIPMAP -> {
                val l = writeExpression(level.level)
                "$texture.SampleLevel($sampler, $coordinate, $l)"
            }
            is SampleLevel.AUTOMATIC -> "$texture.Sample($sampler, $coordinate)"
            null -> {
                if (depthRef != null) {
                    val d = writeExpression(depthRef)
                    "$texture.SampleCmp($sampler, $coordinate, $d)"
                } else {
                    "$texture.Sample($sampler, $coordinate)"
                }
            }
        }
    }

    override fun writeTextureQuery(texture: String, query: TextureQueryKind): String {
        val method = when (query) {
            TextureQueryKind.Size -> "GetDimensions()" // Simplified, returns multiple values
            TextureQueryKind.SizeLevel -> "GetDimensions()"
            TextureQueryKind.NumLevels -> "/* unsupported */"
            TextureQueryKind.NumLayers -> "/* unsupported */"
            TextureQueryKind.NumSamples -> "/* unsupported */"
        }
        return "$texture.$method"
    }

    private fun getHlslSemantic(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.Position -> "SV_Position"
        BuiltinValue.VertexIndex -> "SV_VertexID"
        BuiltinValue.InstanceIndex -> "SV_InstanceID"
        BuiltinValue.FrontFacing -> "SV_IsFrontFace"
        BuiltinValue.LocalInvocationId -> "SV_GroupThreadID"
        BuiltinValue.LocalInvocationIndex -> "SV_GroupIndex"
        BuiltinValue.GlobalInvocationId -> "SV_DispatchThreadID"
        BuiltinValue.WorkgroupId -> "SV_GroupID"
        BuiltinValue.SampleIndex -> "SV_SampleIndex"
        BuiltinValue.SampleMask -> "SV_Coverage"
        else -> builtin.name.uppercase()
    }

    private fun getHlslBuiltinType(builtin: BuiltinValue): String = when (builtin) {
        BuiltinValue.Position -> "float4"
        BuiltinValue.VertexIndex, BuiltinValue.InstanceIndex, BuiltinValue.SampleIndex -> "uint"
        BuiltinValue.FrontFacing -> "bool"
        BuiltinValue.LocalInvocationId, BuiltinValue.GlobalInvocationId,
        BuiltinValue.WorkgroupId -> "uint3"
        BuiltinValue.LocalInvocationIndex, BuiltinValue.SampleMask -> "uint"
        else -> "uint"
    }

    override fun getScalarTypeName(scalar: TypeInner.Scalar): String {
        return when (scalar.kind) {
            ScalarKind.Bool -> "bool"
            ScalarKind.Sint -> when (scalar.width) {
                1 -> "int8_t"
                2 -> "int16_t"
                4 -> "int"
                8 -> "int64_t"
                else -> "int"
            }
            ScalarKind.Uint -> when (scalar.width) {
                1 -> "uint8_t"
                2 -> "uint16_t"
                4 -> "uint"
                8 -> "uint64_t"
                else -> "uint"
            }
            ScalarKind.F32 -> "float"
            ScalarKind.F16 -> "half"
            ScalarKind.F64 -> "double"
            else -> "void"
        }
    }

    override fun getTypeName(handle: Handle<Type>): String {
        val type = module.types[handle]
        return when (val inner = type.inner) {
            is TypeInner.Scalar -> getScalarTypeName(inner)
            is TypeInner.Vector -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "$scalarName${inner.size.ordinal + 2}"
            }
            is TypeInner.Matrix -> {
                val scalarType = module.types[inner.scalar]
                val scalarName = getScalarTypeName(scalarType.inner as TypeInner.Scalar)
                "$scalarName${inner.columns.ordinal + 2}x${inner.rows.ordinal + 2}"
            }
            is TypeInner.Struct -> "Struct_${handle.index}"
            is TypeInner.Pointer -> {
                val baseName = getTypeName(inner.base)
                // Simplified HLSL pointer mapping
                "$baseName*"
            }
            is TypeInner.Array -> {
                val elementTypeName = getTypeName(inner.element)
                val sizeStr = when (val size = inner.size) {
                    is ArraySize.Constant -> size.value.toString()
                    is ArraySize.Dynamic -> ""
                }
                "$elementTypeName[$sizeStr]"
            }
            is TypeInner.Atomic -> getTypeName(inner.inner)
            is TypeInner.Opaque -> {
                when {
                    inner.name == "sampler" -> "SamplerState"
                    inner.name == "comparison_sampler" -> "SamplerComparisonState"
                    inner.name == "acceleration_structure" -> "RaytracingAccelerationStructure"
                    inner.name == "ray_query" -> "RayQuery"
                    inner.name == "texture_1d<f32>" -> "Texture1D<float4>"
                    inner.name == "texture_2d<f32>" -> "Texture2D<float4>"
                    inner.name == "texture_2d_array<f32>" -> "Texture2DArray<float4>"
                    inner.name == "texture_3d<f32>" -> "Texture3D<float4>"
                    inner.name == "texture_cube<f32>" -> "TextureCube<float4>"
                    inner.name == "texture_cube_array<f32>" -> "TextureCubeArray<float4>"
                    inner.name == "texture_multisampled_2d<f32>" -> "Texture2DMS<float4>"
                    inner.name.startsWith("texture_depth") -> "Texture2D<float>"
                    else -> inner.name
                }
            }
            else -> "void"
        }
    }

    override fun writeBitcast(expr: String, targetType: Type, sourceType: Type): String {
        val inner = targetType.inner
        val prefix = when {
            inner is TypeInner.Scalar && inner.kind == ScalarKind.Uint -> "asuint"
            inner is TypeInner.Scalar && inner.kind == ScalarKind.F32 -> "asfloat"
            inner is TypeInner.Scalar && inner.kind == ScalarKind.Sint -> "asint"
            inner is TypeInner.Vector -> {
                val scalar = module.types[inner.scalar].inner as TypeInner.Scalar
                when (scalar.kind) {
                    ScalarKind.Uint -> "asuint"
                    ScalarKind.F32 -> "asfloat"
                    ScalarKind.Sint -> "asint"
                    else -> "asfloat"
                }
            }
            else -> "asfloat"
        }
        return "$prefix($expr)"
    }

    override fun writeRelational(function: RelationalFunction, arguments: List<String>): String {
        return when (function) {
            RelationalFunction.Any -> "any(${arguments.joinToString()})"
            RelationalFunction.All -> "all(${arguments.joinToString()})"
            RelationalFunction.IsNan -> "isnan(${arguments.joinToString()})"
            RelationalFunction.IsInf -> "isinf(${arguments.joinToString()})"
            RelationalFunction.IsFinite -> "isfinite(${arguments.joinToString()})"
            // HLSL doesn't have a direct isnormal, let's use a placeholder
            RelationalFunction.IsNormal -> "/* isnormal unsupported */ true"
            RelationalFunction.SignBit -> "signbit(${arguments.joinToString()})"
        }
    }

    override fun writeAtomic(pointer: String, function: AtomicFunction, arguments: List<String>): String {
        val hlslFunc = when (function) {
            AtomicFunction.Add -> "InterlockedAdd"
            AtomicFunction.Subtract -> "InterlockedAdd" // use negative
            AtomicFunction.And -> "InterlockedAnd"
            AtomicFunction.Or -> "InterlockedOr"
            AtomicFunction.Xor -> "InterlockedXor"
            AtomicFunction.Min -> "InterlockedMin"
            AtomicFunction.Max -> "InterlockedMax"
            AtomicFunction.Exchange -> "InterlockedExchange"
            AtomicFunction.CompSwap -> "InterlockedCompareExchange"
        }
        // HLSL Interlocked functions are statements, not expressions.
        // This is a major difference with WGSL/MSL.
        return "$hlslFunc($pointer, ${arguments.joinToString()}, /* old_value */)"
    }

    override fun getBuiltinFunctionName(function: BuiltinFunction): String = when (function) {
        BuiltinFunction.Ln -> "log"
        BuiltinFunction.Mix -> "lerp"
        BuiltinFunction.Fract -> "frac"
        BuiltinFunction.Atan2 -> "atan2"
        BuiltinFunction.Dot -> "dot"
        BuiltinFunction.Cross -> "cross"
        BuiltinFunction.Distance -> "distance"
        BuiltinFunction.Length -> "length"
        BuiltinFunction.Normalize -> "normalize"
        BuiltinFunction.Reflect -> "reflect"
        BuiltinFunction.Refract -> "refract"
        BuiltinFunction.Pow -> "pow"
        BuiltinFunction.Exp -> "exp"
        BuiltinFunction.Exp2 -> "exp2"
        BuiltinFunction.Log2 -> "log2"
        BuiltinFunction.Sqrt -> "sqrt"
        BuiltinFunction.InverseSqrt -> "rsqrt"
        BuiltinFunction.Floor -> "floor"
        BuiltinFunction.Ceil -> "ceil"
        BuiltinFunction.Round -> "round"
        BuiltinFunction.Trunc -> "trunc"
        BuiltinFunction.Sin -> "sin"
        BuiltinFunction.Cos -> "cos"
        BuiltinFunction.Tan -> "tan"
        BuiltinFunction.Asin -> "asin"
        BuiltinFunction.Acos -> "acos"
        BuiltinFunction.Atan -> "atan"
        BuiltinFunction.Sinh -> "sinh"
        BuiltinFunction.Cosh -> "cosh"
        BuiltinFunction.Tanh -> "tanh"
        BuiltinFunction.Asinh -> "asinh"
        BuiltinFunction.Acosh -> "acosh"
        BuiltinFunction.Atanh -> "atanh"
        BuiltinFunction.Abs -> "abs"
        BuiltinFunction.Min -> "min"
        BuiltinFunction.Max -> "max"
        BuiltinFunction.Clamp -> "clamp"
        BuiltinFunction.Step -> "step"
        BuiltinFunction.Smoothstep -> "smoothstep"
        BuiltinFunction.Fma -> "mad"
        BuiltinFunction.Determinant -> "determinant"
        else -> super.getBuiltinFunctionName(function)
    }
}
