import java.io.File
import java.util.TreeMap

plugins {
    id("ygdrasil.conventions.wgsl-library")
    id("ygdrasil.conventions.kmp-publish")
    id("ygdrasil.conventions.kmp-dokka")
    id("dev.opensavvy.dokka-mkdocs") version "0.6.3"
}

kotlin {
    sourceSets {
        commonMain.dependencies {
            implementation(project(":wgsl:wgsl-core"))
            implementation(project(":wgsl:wgsl-parser"))
            implementation(project(":wgsl:wgsl-generator"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.bundles.kotest)
        }
        jvmTest.dependencies {
            implementation(libs.kotest.runner.junit5)
            implementation(libs.kotlin.logging)
            implementation(libs.logback.classic)
        }
    }
}

tasks.named<org.gradle.api.tasks.testing.Test>("jvmTest") {
    useJUnitPlatform()
    val goldenUpdate = System.getenv("GOLDEN_UPDATE")?.toBoolean() ?: false
    val showFullExceptions = System.getenv("GOLDEN_DEBUG")?.toBoolean() ?: false
    testLogging {
        showExceptions = showFullExceptions
        showStandardStreams = false
        events = setOf(
            org.gradle.api.tasks.testing.logging.TestLogEvent.FAILED,
            org.gradle.api.tasks.testing.logging.TestLogEvent.PASSED,
        )
        exceptionFormat = if (goldenUpdate || showFullExceptions) {
            org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        } else {
            org.gradle.api.tasks.testing.logging.TestExceptionFormat.SHORT
        }
    }
    systemProperty(
        "logback.configurationFile",
        layout.projectDirectory.dir("src/jvmTest/resources").file("logback-test.xml").asFile.path,
    )
}

tasks.register("goldenCoverageReport") {
    group = "verification"
    description = "Generate a markdown coverage report for the WGSL golden corpus"
    dependsOn(tasks.named("jvmTest"))

    val goldenRoot = rootProject.layout.projectDirectory.dir("tests/golden")
    val inputsDir = goldenRoot.dir("inputs")
    val outputsDir = goldenRoot.dir("outputs")
    val junitResultsDir = layout.buildDirectory.dir("test-results/jvmTest")
    val reportFile = layout.buildDirectory.file("reports/golden-coverage/summary.md")

    inputs.files(inputsDir)
    inputs.files(outputsDir)
    inputs.files(junitResultsDir).optional()
    outputs.file(reportFile)

    doLast {
        val backendExtensions = linkedMapOf(
            "wgsl" to "wgsl",
            "glsl" to "glsl",
            "hlsl" to "hlsl",
            "msl" to "metal",
            "ir" to "json",
        )
        val inputFiles = inputsDir.asFile.listFilesWithExtension("wgsl")
        val inputStems = inputFiles.mapTo(sortedSetOf()) { it.nameWithoutExtension }
        val report = StringBuilder()

        report.appendLine("# Golden Corpus Coverage")
        report.appendLine()
        report.appendLine("Generated by `:wgsl:tests:goldenCoverageReport`.")
        report.appendLine()
        report.appendLine("## Corpus")
        report.appendLine()
        report.appendLine("- Input files: `${inputFiles.size}`")
        report.appendLine("- Backends: `${backendExtensions.keys.joinToString(", ")}`")
        report.appendLine()
        report.appendLine("| Backend | Expected outputs | Present outputs | Missing outputs | Orphan outputs |")
        report.appendLine("|---------|------------------|-----------------|-----------------|----------------|")

        val backendDetails = backendExtensions.map { (backend, extension) ->
            val backendDir = outputsDir.dir(backend).asFile
            val outputFiles = backendDir.listFilesWithExtension(extension)
            val outputStems = outputFiles.mapTo(sortedSetOf()) { it.nameWithoutExtension }
            val missing = inputStems.minus(outputStems)
            val orphan = outputStems.minus(inputStems)

            report.appendLine("| `$backend` | `${inputFiles.size}` | `${outputFiles.size}` | `${missing.size}` | `${orphan.size}` |")

            GoldenBackendCoverage(
                backend = backend,
                extension = extension,
                missing = missing.toList(),
                orphan = orphan.toList(),
            )
        }

        report.appendLine()
        report.appendLine("## Missing Outputs")
        report.appendLine()
        backendDetails.forEach { detail ->
            report.appendLine("### ${detail.backend}")
            report.appendLine()
            if (detail.missing.isEmpty()) {
                report.appendLine("No missing outputs.")
            } else {
                detail.missing.forEach { stem ->
                    report.appendLine("- `$stem.${detail.extension}`")
                }
            }
            report.appendLine()
        }

        report.appendLine("## Orphan Outputs")
        report.appendLine()
        backendDetails.forEach { detail ->
            report.appendLine("### ${detail.backend}")
            report.appendLine()
            if (detail.orphan.isEmpty()) {
                report.appendLine("No orphan outputs.")
            } else {
                detail.orphan.forEach { stem ->
                    report.appendLine("- `$stem.${detail.extension}`")
                }
            }
            report.appendLine()
        }

        val junitSummary = parseGoldenJUnitResults(junitResultsDir.get().asFile)
        report.appendLine("## JUnit Results")
        report.appendLine()
        if (junitSummary.suites.isEmpty()) {
            report.appendLine("No JUnit XML results found under `wgsl/tests/build/test-results/jvmTest`.")
        } else {
            report.appendLine("| Suite | Tests | Passed | Failures | Errors | Skipped |")
            report.appendLine("|-------|-------|--------|----------|--------|---------|")
            junitSummary.suites.forEach { suite ->
                report.appendLine(
                    "| `${suite.name}` | `${suite.tests}` | `${suite.passed}` | `${suite.failures}` | `${suite.errors}` | `${suite.skipped}` |"
                )
            }
            report.appendLine()
            report.appendLine("### Phase Failure Breakdown")
            report.appendLine()
            if (junitSummary.phaseFailures.isEmpty()) {
                report.appendLine("No `GoldenTestException` phase failures found in existing JUnit XML results.")
            } else {
                report.appendLine("| Backend | Phase | Failures |")
                report.appendLine("|---------|-------|----------|")
                junitSummary.phaseFailures.forEach { (key, count) ->
                    report.appendLine("| `${key.backend}` | `${key.phase}` | `$count` |")
                }
            }
        }
        report.appendLine()

        val outputFile = reportFile.get().asFile
        outputFile.parentFile.mkdirs()
        outputFile.writeText(report.toString())
        logger.lifecycle("Golden coverage report written to: ${outputFile.path}")
    }
}

// Task to run the golden debug tool
val goldenDebug by tasks.registering(JavaExec::class) {
    group = "debug"
    description = "Run golden test debugger on a single file"

    classpath = sourceSets["jvmTest"].runtimeClasspath
    mainClass = "org.graphiks.wgsl.tests.GoldenDebugKt"

    val goldenDebugEnabled = providers.gradleProperty("GOLDEN_DEBUG")
        .orElse(providers.environmentVariable("GOLDEN_DEBUG"))
        .orElse("false")
    val goldenUpdateEnabled = providers.gradleProperty("GOLDEN_UPDATE")
        .orElse(providers.environmentVariable("GOLDEN_UPDATE"))
        .orElse("false")

    environment("GOLDEN_DEBUG", goldenDebugEnabled.get())
    environment("GOLDEN_UPDATE", goldenUpdateEnabled.get())
    environment("DEBUG", goldenDebugEnabled.get())

    // Pass arguments to the main function
    args = project.properties.getOrDefault("args", "").toString().split("\\s+".toRegex())

    // Ensure the JVM arguments include the classpath
    jvmArgs = listOf("-Dfile.encoding=UTF-8", "-Dlogback.configurationFile=${layout.projectDirectory.dir("src/jvmTest/resources")}/logback-test.xml")
}

data class GoldenBackendCoverage(
    val backend: String,
    val extension: String,
    val missing: List<String>,
    val orphan: List<String>,
)

data class GoldenJUnitSummary(
    val suites: List<GoldenJUnitSuite>,
    val phaseFailures: Map<GoldenPhaseFailure, Int>,
)

data class GoldenJUnitSuite(
    val name: String,
    val tests: Int,
    val failures: Int,
    val errors: Int,
    val skipped: Int,
) {
    val passed: Int = tests - failures - errors - skipped
}

data class GoldenPhaseFailure(
    val backend: String,
    val phase: String,
)

fun File.listFilesWithExtension(extension: String): List<File> =
    listFiles()
        ?.filter { it.isFile && it.extension == extension }
        ?.sortedBy { it.name }
        .orEmpty()

fun parseGoldenJUnitResults(resultsDir: File): GoldenJUnitSummary {
    if (!resultsDir.isDirectory) {
        return GoldenJUnitSummary(emptyList(), emptyMap())
    }

    val phasePattern = Regex("\\[([^]]+)] ([a-z-]+) failed for ")
    val suitePattern = Regex("<testsuite\\b([^>]*)>")
    val failurePattern = Regex("<failure\\b[\\s\\S]*?</failure>")
    val phaseFailures = TreeMap<GoldenPhaseFailure, Int>(
        compareBy<GoldenPhaseFailure> { it.backend }.thenBy { it.phase }
    )
    val suites = resultsDir
        .listFilesWithExtension("xml")
        .mapNotNull { xmlFile ->
            runCatching {
                val xml = xmlFile.readText()
                val suiteAttributes = suitePattern.find(xml)?.groupValues?.get(1) ?: return@runCatching null
                failurePattern.findAll(xml).forEach { failure ->
                    phasePattern.find(failure.value)?.let { match ->
                        val key = GoldenPhaseFailure(
                            backend = match.groupValues[1],
                            phase = match.groupValues[2],
                        )
                        phaseFailures[key] = phaseFailures.getOrDefault(key, 0) + 1
                    }
                }
                GoldenJUnitSuite(
                    name = suiteAttributes.getXmlAttribute("name").removeSuffix("[jvm]"),
                    tests = suiteAttributes.getIntXmlAttribute("tests"),
                    failures = suiteAttributes.getIntXmlAttribute("failures"),
                    errors = suiteAttributes.getIntXmlAttribute("errors"),
                    skipped = suiteAttributes.getIntXmlAttribute("skipped"),
                )
            }.getOrNull()
        }
        .sortedBy { it.name }

    return GoldenJUnitSummary(suites, phaseFailures)
}

fun String.getXmlAttribute(name: String): String =
    Regex("""\b$name="([^"]*)"""").find(this)?.groupValues?.get(1).orEmpty()

fun String.getIntXmlAttribute(name: String): Int =
    getXmlAttribute(name).toIntOrNull() ?: 0
