// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void break_from_loop() {
    {
        int local_0 = 0;
        while (true) {
            if ((local_0 < 4)) {
                {
                    break;
                }
                local_0 = 1;
            } else {
                break;
            }
        }
    }
}

[numthreads(1, 1, 1)]
void main() {
    break_from_loop();
}
