// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    float2 texcoord;
};

struct fs_Output {
    float4 color : SV_Target;
};
fs_Output fs() {
    fs_Output stage_out;
    return float4(1.0f, 0.0f, 0.0f, 1.0f);
    return stage_out;
}

struct vs_Input {
    float2 xy : TEXCOORD0;
};
struct vs_Output {
    float4 position : SV_Position;
    float2 texcoord : TEXCOORD0;
};
vs_Output vs(vs_Input stage_in) {
    vs_Output stage_out;
    float2 xy = stage_in.xy;
    Struct_3 local_0;
    local_0.position = float4(xy, 0.0f, 1.0f);
    return local_0;
    return stage_out;
}
