// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


[numthreads(1, 1, 1)]
void main() {
    int local_0 = 2;
    unpack4xI8(12u)[local_0];
    unpack4xU8(12u)[1];
}

uint unpack4xI8(uint arg_0) {
}

uint unpack4xU8(uint arg_0) {
}
