// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float a;
    float3 b;
};

Struct_2 foobar(float3 normals[12], uint count) {
    {
        uint local_0 = 0u;
        while (true) {
            if ((local_0 < count)) {
                {
                    float3 local_1 = normals[local_0];
                }
                local_0 = (local_0 + 1u);
            } else {
                break;
            }
        }
    }
    {
        uint local_2 = 0u;
        while (true) {
            if ((local_2 < count)) {
                {
                    float3 local_3 = normals[local_2];
                }
                local_2 = (local_2 + 1u);
            } else {
                break;
            }
        }
    }
    return Struct_2(0.0f, float3(0.0f));
}

void main() {
    float3 local_0[12];
    foobar(local_0, 1);
}
