// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


[numthreads(1, 1, 1)]
void f() {
    float3 local_0[2] = float3[2]();
    float4 local_1 = float4(0);
    int local_2 = 0;
    int local_3 = 0;
    local_1[0] = (local_0[local_3][1] * local_0[local_2][2]);
}
