// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(u0);

float compute() {
    float local_0 = (global_0 + 9001.0f);
    return local_0;
}

[numthreads(1, 1, 1)]
void main() {
    compute();
}
