// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0 = 1;

int return_i32_ai() {
    return 1;
}

uint return_u32_ai() {
    return 1;
}

float return_f32_ai() {
    return 1;
}

float return_f32_af() {
    return 1.0f;
}

float2 return_vec2f32_ai() {
    return float2(1);
}

float return_arrf32_ai()[4] {
    return float[4](1, 1, 1, 1);
}

float2 return_vec2f32_const_ai() {
    float2 local_0 = float2(1);
    return local_0;
}

float return_const_f32_const_ai() {
    return global_0;
}

[numthreads(1, 1, 1)]
void main() {
    return_i32_ai();
    return_u32_ai();
    return_f32_ai();
    return_f32_af();
    return_vec2f32_ai();
    return_arrf32_ai();
    return_const_f32_const_ai();
    return_vec2f32_const_ai();
}
