// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float4> global_0 : register(t0);
SamplerState global_1 : register(t1);
Texture2D<float> global_2 : register(t2);
sampler_comparison global_3 : register(t3);
texture_storage_2d<rgba8unorm, read_write> global_4 : register(t4);

void color() {
    textureSample(global_0, global_1, float2(1, 2));
    textureSample(global_0, global_1, float2(1, 2), float2(3, 4));
    textureSampleLevel(global_0, global_1, float2(1, 2), 0);
    textureSampleLevel(global_0, global_1, float2(1, 2), 0.0f);
    textureSampleGrad(global_0, global_1, float2(1, 2), float2(3, 4), float2(5, 6));
    textureSampleBias(global_0, global_1, float2(1, 2), 1);
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float2 arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleGrad(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float2 arg_3, float2 arg_4) {
}

float4 textureSampleBias(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3) {
}

void depth() {
    textureSampleLevel(global_2, global_1, float2(1, 2), 1);
    textureSampleCompare(global_2, global_3, float2(1, 2), 0);
    textureGatherCompare(global_2, global_3, float2(1, 2), 0);
}

float4 textureSampleLevel(Texture2D<float> arg_0, SamplerState arg_1, float2 arg_2, int arg_3) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, int arg_3) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, int arg_3) {
}

void storage() {
    textureStore(global_4, float2(0, 1), float4(2, 3, 4, 5));
}

texture_storage_2d<rgba8unorm, read_write> textureStore(texture_storage_2d<rgba8unorm, read_write> arg_0, float2 arg_1, float4 arg_2) {
}

void main() {
    color();
    depth();
    storage();
}
