// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_10 {
    uint kind;
    float t;
    uint instance_custom_data;
    uint instance_index;
    uint sbt_record_offset;
    uint geometry_index;
    uint primitive_index;
    float2 barycentrics;
    bool front_face;
    float4x3 object_to_world;
    float4x3 world_to_object;
};
RaytracingAccelerationStructure global_0 : register(t0);

[numthreads(1, 1, 1)]
void main_candidate() {
    float3 local_0 = float3(0.0f);
    float3 local_1 = float3(0.0f, 1.0f, 0.0f);
    RayQuery local_2;
    rayQueryInitialize(&local_2, global_0, RayDesc(4u, 0, 0.1f, 100.0f, local_0, local_1));
    Struct_10 local_3 = rayQueryGetCandidateIntersection(&local_2);
    if ((local_3.kind == 3u)) {
        rayQueryGenerateIntersection(&local_2, 10.0f);
    } else {
        if ((local_3.kind == 1u)) {
            rayQueryConfirmIntersection(&local_2);
        } else {
            rayQueryTerminate(&local_2);
        }
    }
}

uint RayDesc(uint arg_0, int arg_1, float arg_2, float arg_3, float3 arg_4, float3 arg_5) {
}

void rayQueryInitialize(void arg_0, RaytracingAccelerationStructure arg_1, uint arg_2) {
}

Struct_10 rayQueryGetCandidateIntersection(void arg_0) {
}

void rayQueryGenerateIntersection(void arg_0, float arg_1) {
}

void rayQueryConfirmIntersection(void arg_0) {
}

void rayQueryTerminate(void arg_0) {
}
