// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


float ret_array()[2] {
    return float[2](1.0f, 2.0f);
}

float ret_array_array()[3][2] {
    return float[2][3](ret_array(), ret_array(), ret_array());
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    float local_0[3][2] = ret_array_array();
    return float4(local_0[0][0], local_0[0][1], 0.0f, 1.0f);
    return stage_out;
}
