// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float atomic_scalar;
    float atomic_arr[2];
};
float global_0 : register(u0);
float global_1[2] : register(u1);
Struct_3 global_2 : register(u2);

[numthreads(2, 1, 1)]
void cs_main(uint3 id : SV_GroupThreadID) {
    atomicStore(&global_0, 1.5f);
    atomicStore(&global_1[1], 1.5f);
    atomicStore(&global_2.atomic_scalar, 1.5f);
    atomicStore(&global_2.atomic_arr[1], 1.5f);
    workgroupBarrier();
    float local_0 = atomicLoad(&global_0);
    float local_1 = atomicLoad(&global_1[1]);
    float local_2 = atomicLoad(&global_2.atomic_scalar);
    float local_3 = atomicLoad(&global_2.atomic_arr[1]);
    workgroupBarrier();
    atomicAdd(&global_0, 1.5f);
    atomicAdd(&global_1[1], 1.5f);
    atomicAdd(&global_2.atomic_scalar, 1.5f);
    atomicAdd(&global_2.atomic_arr[1], 1.5f);
    workgroupBarrier();
    atomicExchange(&global_0, 1.5f);
    atomicExchange(&global_1[1], 1.5f);
    atomicExchange(&global_2.atomic_scalar, 1.5f);
    atomicExchange(&global_2.atomic_arr[1], 1.5f);
}

void atomicStore(void arg_0, float arg_1) {
}

void atomicStore(void arg_0, float arg_1) {
}

void atomicStore(void arg_0, float arg_1) {
}

void atomicStore(void arg_0, float arg_1) {
}

void workgroupBarrier() {
}

float atomicLoad(void arg_0) {
}

float atomicLoad(void arg_0) {
}

float atomicLoad(void arg_0) {
}

float atomicLoad(void arg_0) {
}

void workgroupBarrier() {
}

float atomicAdd(void arg_0, float arg_1) {
}

float atomicAdd(void arg_0, float arg_1) {
}

float atomicAdd(void arg_0, float arg_1) {
}

float atomicAdd(void arg_0, float arg_1) {
}

void workgroupBarrier() {
}

float atomicExchange(void arg_0, float arg_1) {
}

float atomicExchange(void arg_0, float arg_1) {
}

float atomicExchange(void arg_0, float arg_1) {
}

float atomicExchange(void arg_0, float arg_1) {
}
