// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_9 {
    int old_value;
    bool exchanged;
};
struct Struct_11 {
    uint old_value;
    bool exchanged;
};
uint global_0 = 128u;
int global_1[128] : register(u0);
uint global_2[128] : register(u1);

[numthreads(1, 1, 1)]
void test_atomic_compare_exchange_i32() {
    {
        uint local_0 = 0u;
        while (true) {
            if ((local_0 < global_0)) {
                {
                    int local_1 = atomicLoad(&global_1[local_0]);
                    bool local_2 = false;
                    while (true) {
                        if (!(local_2)) {
                            int local_3 = asint((asfloat(local_1) + 1.0f));
                            Struct_9 local_4 = atomicCompareExchangeWeak(&global_1[local_0], local_1, local_3);
                            local_1 = local_4.old_value;
                            local_2 = local_4.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                local_0 = (local_0 + 1u);
            } else {
                break;
            }
        }
    }
}

int atomicLoad(void arg_0) {
}

Struct_9 atomicCompareExchangeWeak(void arg_0, int arg_1, int arg_2) {
}

[numthreads(1, 1, 1)]
void test_atomic_compare_exchange_u32() {
    {
        uint local_0 = 0u;
        while (true) {
            if ((local_0 < global_0)) {
                {
                    uint local_1 = atomicLoad(&global_2[local_0]);
                    bool local_2 = false;
                    while (true) {
                        if (!(local_2)) {
                            uint local_3 = asuint((asfloat(local_1) + 1.0f));
                            Struct_11 local_4 = atomicCompareExchangeWeak(&global_2[local_0], local_1, local_3);
                            local_1 = local_4.old_value;
                            local_2 = local_4.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                local_0 = (local_0 + 1u);
            } else {
                break;
            }
        }
    }
}

uint atomicLoad(void arg_0) {
}

Struct_11 atomicCompareExchangeWeak(void arg_0, uint arg_1, uint arg_2) {
}
