// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r64uint, atomic> global_0 : register(t0);

[numthreads(2, 1, 1)]
void cs_main(uint3 id : SV_GroupThreadID) {
    textureAtomicMax(global_0, int2(0, 0), 1u);
    workgroupBarrier();
    textureAtomicMin(global_0, int2(0, 0), 1u);
}

texture_storage_2d<r64uint, atomic> textureAtomicMax(texture_storage_2d<r64uint, atomic> arg_0, int2 arg_1, uint64_t arg_2) {
}

void workgroupBarrier() {
}

texture_storage_2d<r64uint, atomic> textureAtomicMin(texture_storage_2d<r64uint, atomic> arg_0, int2 arg_1, uint64_t arg_2) {
}
