// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r32uint, atomic> global_0 : register(t0);
texture_storage_2d<r32sint, atomic> global_1 : register(t1);

[numthreads(2, 1, 1)]
void cs_main(uint3 id : SV_GroupThreadID) {
    textureAtomicMax(global_0, int2(0, 0), 1u);
    textureAtomicMin(global_0, int2(0, 0), 1u);
    textureAtomicAdd(global_0, int2(0, 0), 1u);
    textureAtomicAnd(global_0, int2(0, 0), 1u);
    textureAtomicOr(global_0, int2(0, 0), 1u);
    textureAtomicXor(global_0, int2(0, 0), 1u);
    textureAtomicMax(global_1, int2(0, 0), 1);
    textureAtomicMin(global_1, int2(0, 0), 1);
    textureAtomicAdd(global_1, int2(0, 0), 1);
    textureAtomicAnd(global_1, int2(0, 0), 1);
    textureAtomicOr(global_1, int2(0, 0), 1);
    textureAtomicXor(global_1, int2(0, 0), 1);
}

texture_storage_2d<r32uint, atomic> textureAtomicMax(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint, atomic> textureAtomicMin(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint, atomic> textureAtomicAdd(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint, atomic> textureAtomicAnd(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint, atomic> textureAtomicOr(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32uint, atomic> textureAtomicXor(texture_storage_2d<r32uint, atomic> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicMax(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicMin(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicAdd(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicAnd(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicOr(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_2d<r32sint, atomic> textureAtomicXor(texture_storage_2d<r32sint, atomic> arg_0, int2 arg_1, int arg_2) {
}
