// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    uint64_t atomic_scalar;
    uint64_t atomic_arr[2];
};
uint64_t global_0 : register(u0);
uint64_t global_1[2] : register(u1);
uint64_t global_2 : register(b3);
Struct_3 global_3 : register(u2);

[numthreads(2, 1, 1)]
void cs_main(uint3 id : SV_GroupThreadID) {
    atomicMax(&global_0, global_2);
    atomicMax(&global_1[1], (1 + global_2));
    atomicMax(&global_3.atomic_scalar, 1u);
    atomicMax(&global_3.atomic_arr[1], uint64_t(id[0]));
    workgroupBarrier();
    atomicMin(&global_0, global_2);
    atomicMin(&global_1[1], (1 + global_2));
    atomicMin(&global_3.atomic_scalar, 1u);
    atomicMin(&global_3.atomic_arr[1], uint64_t(id[0]));
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

uint64_t atomicMax(void arg_0, int arg_1) {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

uint64_t atomicMin(void arg_0, int arg_1) {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}
