// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_5 {
    uint64_t atomic_scalar;
    int64_t atomic_arr[2];
};
struct Struct_13 {
    uint64_t old_value;
    bool exchanged;
};
struct Struct_14 {
    int64_t old_value;
    bool exchanged;
};
uint64_t global_0 : register(u0);
int64_t global_1[2] : register(u1);
uint64_t global_2;
int64_t global_3[2];
Struct_5 global_4 : register(u2);
Struct_5 global_5;

[numthreads(2, 1, 1)]
void cs_main(uint3 id : SV_GroupThreadID) {
    atomicStore(&global_0, 1u);
    atomicStore(&global_1[1], 1);
    atomicStore(&global_4.atomic_scalar, 1u);
    atomicStore(&global_4.atomic_arr[1], 1);
    atomicStore(&global_2, 1u);
    atomicStore(&global_3[1], 1);
    atomicStore(&global_5.atomic_scalar, 1u);
    atomicStore(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    uint64_t local_0 = atomicLoad(&global_0);
    int64_t local_1 = atomicLoad(&global_1[1]);
    uint64_t local_2 = atomicLoad(&global_4.atomic_scalar);
    int64_t local_3 = atomicLoad(&global_4.atomic_arr[1]);
    uint64_t local_4 = atomicLoad(&global_2);
    int64_t local_5 = atomicLoad(&global_3[1]);
    uint64_t local_6 = atomicLoad(&global_5.atomic_scalar);
    int64_t local_7 = atomicLoad(&global_5.atomic_arr[1]);
    workgroupBarrier();
    atomicAdd(&global_0, 1u);
    atomicAdd(&global_1[1], 1);
    atomicAdd(&global_4.atomic_scalar, 1u);
    atomicAdd(&global_4.atomic_arr[1], 1);
    atomicAdd(&global_2, 1u);
    atomicAdd(&global_3[1], 1);
    atomicAdd(&global_5.atomic_scalar, 1u);
    atomicAdd(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicSub(&global_0, 1u);
    atomicSub(&global_1[1], 1);
    atomicSub(&global_4.atomic_scalar, 1u);
    atomicSub(&global_4.atomic_arr[1], 1);
    atomicSub(&global_2, 1u);
    atomicSub(&global_3[1], 1);
    atomicSub(&global_5.atomic_scalar, 1u);
    atomicSub(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicMax(&global_0, 1u);
    atomicMax(&global_1[1], 1);
    atomicMax(&global_4.atomic_scalar, 1u);
    atomicMax(&global_4.atomic_arr[1], 1);
    atomicMax(&global_2, 1u);
    atomicMax(&global_3[1], 1);
    atomicMax(&global_5.atomic_scalar, 1u);
    atomicMax(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicMin(&global_0, 1u);
    atomicMin(&global_1[1], 1);
    atomicMin(&global_4.atomic_scalar, 1u);
    atomicMin(&global_4.atomic_arr[1], 1);
    atomicMin(&global_2, 1u);
    atomicMin(&global_3[1], 1);
    atomicMin(&global_5.atomic_scalar, 1u);
    atomicMin(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicAnd(&global_0, 1u);
    atomicAnd(&global_1[1], 1);
    atomicAnd(&global_4.atomic_scalar, 1u);
    atomicAnd(&global_4.atomic_arr[1], 1);
    atomicAnd(&global_2, 1u);
    atomicAnd(&global_3[1], 1);
    atomicAnd(&global_5.atomic_scalar, 1u);
    atomicAnd(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicOr(&global_0, 1u);
    atomicOr(&global_1[1], 1);
    atomicOr(&global_4.atomic_scalar, 1u);
    atomicOr(&global_4.atomic_arr[1], 1);
    atomicOr(&global_2, 1u);
    atomicOr(&global_3[1], 1);
    atomicOr(&global_5.atomic_scalar, 1u);
    atomicOr(&global_5.atomic_arr[1], 1);
    workgroupBarrier();
    atomicXor(&global_0, 1u);
    atomicXor(&global_1[1], 1);
    atomicXor(&global_4.atomic_scalar, 1u);
    atomicXor(&global_4.atomic_arr[1], 1);
    atomicXor(&global_2, 1u);
    atomicXor(&global_3[1], 1);
    atomicXor(&global_5.atomic_scalar, 1u);
    atomicXor(&global_5.atomic_arr[1], 1);
    atomicExchange(&global_0, 1u);
    atomicExchange(&global_1[1], 1);
    atomicExchange(&global_4.atomic_scalar, 1u);
    atomicExchange(&global_4.atomic_arr[1], 1);
    atomicExchange(&global_2, 1u);
    atomicExchange(&global_3[1], 1);
    atomicExchange(&global_5.atomic_scalar, 1u);
    atomicExchange(&global_5.atomic_arr[1], 1);
    Struct_13 local_8 = atomicCompareExchangeWeak(&global_0, 1u, 2u);
    Struct_14 local_9 = atomicCompareExchangeWeak(&global_1[1], 1, 2);
    Struct_13 local_10 = atomicCompareExchangeWeak(&global_4.atomic_scalar, 1u, 2u);
    Struct_14 local_11 = atomicCompareExchangeWeak(&global_4.atomic_arr[1], 1, 2);
    Struct_13 local_12 = atomicCompareExchangeWeak(&global_2, 1u, 2u);
    Struct_14 local_13 = atomicCompareExchangeWeak(&global_3[1], 1, 2);
    Struct_13 local_14 = atomicCompareExchangeWeak(&global_5.atomic_scalar, 1u, 2u);
    Struct_14 local_15 = atomicCompareExchangeWeak(&global_5.atomic_arr[1], 1, 2);
}

void atomicStore(void arg_0, uint64_t arg_1) {
}

void atomicStore(void arg_0, int64_t arg_1) {
}

void atomicStore(void arg_0, uint64_t arg_1) {
}

void atomicStore(void arg_0, int64_t arg_1) {
}

void atomicStore(void arg_0, uint64_t arg_1) {
}

void atomicStore(void arg_0, int64_t arg_1) {
}

void atomicStore(void arg_0, uint64_t arg_1) {
}

void atomicStore(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicLoad(void arg_0) {
}

int64_t atomicLoad(void arg_0) {
}

uint64_t atomicLoad(void arg_0) {
}

int64_t atomicLoad(void arg_0) {
}

uint64_t atomicLoad(void arg_0) {
}

int64_t atomicLoad(void arg_0) {
}

uint64_t atomicLoad(void arg_0) {
}

int64_t atomicLoad(void arg_0) {
}

void workgroupBarrier() {
}

uint64_t atomicAdd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAdd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAdd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAdd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAdd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAdd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAdd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAdd(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicSub(void arg_0, uint64_t arg_1) {
}

int64_t atomicSub(void arg_0, int64_t arg_1) {
}

uint64_t atomicSub(void arg_0, uint64_t arg_1) {
}

int64_t atomicSub(void arg_0, int64_t arg_1) {
}

uint64_t atomicSub(void arg_0, uint64_t arg_1) {
}

int64_t atomicSub(void arg_0, int64_t arg_1) {
}

uint64_t atomicSub(void arg_0, uint64_t arg_1) {
}

int64_t atomicSub(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

int64_t atomicMax(void arg_0, int64_t arg_1) {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

int64_t atomicMax(void arg_0, int64_t arg_1) {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

int64_t atomicMax(void arg_0, int64_t arg_1) {
}

uint64_t atomicMax(void arg_0, uint64_t arg_1) {
}

int64_t atomicMax(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

int64_t atomicMin(void arg_0, int64_t arg_1) {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

int64_t atomicMin(void arg_0, int64_t arg_1) {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

int64_t atomicMin(void arg_0, int64_t arg_1) {
}

uint64_t atomicMin(void arg_0, uint64_t arg_1) {
}

int64_t atomicMin(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicAnd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAnd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAnd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAnd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAnd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAnd(void arg_0, int64_t arg_1) {
}

uint64_t atomicAnd(void arg_0, uint64_t arg_1) {
}

int64_t atomicAnd(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicOr(void arg_0, uint64_t arg_1) {
}

int64_t atomicOr(void arg_0, int64_t arg_1) {
}

uint64_t atomicOr(void arg_0, uint64_t arg_1) {
}

int64_t atomicOr(void arg_0, int64_t arg_1) {
}

uint64_t atomicOr(void arg_0, uint64_t arg_1) {
}

int64_t atomicOr(void arg_0, int64_t arg_1) {
}

uint64_t atomicOr(void arg_0, uint64_t arg_1) {
}

int64_t atomicOr(void arg_0, int64_t arg_1) {
}

void workgroupBarrier() {
}

uint64_t atomicXor(void arg_0, uint64_t arg_1) {
}

int64_t atomicXor(void arg_0, int64_t arg_1) {
}

uint64_t atomicXor(void arg_0, uint64_t arg_1) {
}

int64_t atomicXor(void arg_0, int64_t arg_1) {
}

uint64_t atomicXor(void arg_0, uint64_t arg_1) {
}

int64_t atomicXor(void arg_0, int64_t arg_1) {
}

uint64_t atomicXor(void arg_0, uint64_t arg_1) {
}

int64_t atomicXor(void arg_0, int64_t arg_1) {
}

uint64_t atomicExchange(void arg_0, uint64_t arg_1) {
}

int64_t atomicExchange(void arg_0, int64_t arg_1) {
}

uint64_t atomicExchange(void arg_0, uint64_t arg_1) {
}

int64_t atomicExchange(void arg_0, int64_t arg_1) {
}

uint64_t atomicExchange(void arg_0, uint64_t arg_1) {
}

int64_t atomicExchange(void arg_0, int64_t arg_1) {
}

uint64_t atomicExchange(void arg_0, uint64_t arg_1) {
}

int64_t atomicExchange(void arg_0, int64_t arg_1) {
}

Struct_13 atomicCompareExchangeWeak(void arg_0, uint64_t arg_1, uint64_t arg_2) {
}

Struct_14 atomicCompareExchangeWeak(void arg_0, int64_t arg_1, int64_t arg_2) {
}

Struct_13 atomicCompareExchangeWeak(void arg_0, uint64_t arg_1, uint64_t arg_2) {
}

Struct_14 atomicCompareExchangeWeak(void arg_0, int64_t arg_1, int64_t arg_2) {
}

Struct_13 atomicCompareExchangeWeak(void arg_0, uint64_t arg_1, uint64_t arg_2) {
}

Struct_14 atomicCompareExchangeWeak(void arg_0, int64_t arg_1, int64_t arg_2) {
}

Struct_13 atomicCompareExchangeWeak(void arg_0, uint64_t arg_1, uint64_t arg_2) {
}

Struct_14 atomicCompareExchangeWeak(void arg_0, int64_t arg_1, int64_t arg_2) {
}
