// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_9 {
    int64_t old_value;
    bool exchanged;
};
struct Struct_11 {
    uint64_t old_value;
    bool exchanged;
};
uint global_0 = 128u;
int64_t global_1[128] : register(u0);
uint64_t global_2[128] : register(u1);

[numthreads(1, 1, 1)]
void test_atomic_compare_exchange_i64() {
    {
        uint local_0 = 0u;
        while (true) {
            if ((local_0 < global_0)) {
                {
                    int64_t local_1 = atomicLoad(&global_1[local_0]);
                    bool local_2 = false;
                    while (true) {
                        if (!(local_2)) {
                            int64_t local_3 = asint((local_1 + 10));
                            Struct_9 local_4 = atomicCompareExchangeWeak(&global_1[local_0], local_1, local_3);
                            local_1 = local_4.old_value;
                            local_2 = local_4.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                local_0 = (local_0 + 1u);
            } else {
                break;
            }
        }
    }
}

int64_t atomicLoad(void arg_0) {
}

Struct_9 atomicCompareExchangeWeak(void arg_0, int64_t arg_1, int64_t arg_2) {
}

[numthreads(1, 1, 1)]
void test_atomic_compare_exchange_u64() {
    {
        uint local_0 = 0u;
        while (true) {
            if ((local_0 < global_0)) {
                {
                    uint64_t local_1 = atomicLoad(&global_2[local_0]);
                    bool local_2 = false;
                    while (true) {
                        if (!(local_2)) {
                            uint64_t local_3 = asuint((local_1 + 10u));
                            Struct_11 local_4 = atomicCompareExchangeWeak(&global_2[local_0], local_1, local_3);
                            local_1 = local_4.old_value;
                            local_2 = local_4.exchanged;
                        } else {
                            break;
                        }
                    }
                }
                local_0 = (local_0 + 1u);
            } else {
                break;
            }
        }
    }
}

uint64_t atomicLoad(void arg_0) {
}

Struct_11 atomicCompareExchangeWeak(void arg_0, uint64_t arg_1, uint64_t arg_2) {
}
