// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return float4(bary, 1.0f);
    return stage_out;
}

struct fs_main_no_perspective_Output {
    float4 color : SV_Target;
};
fs_main_no_perspective_Output fs_main_no_perspective() {
    fs_main_no_perspective_Output stage_out;
    return float4(bary, 1.0f);
    return stage_out;
}
