// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint index;
};
struct Struct_4 {
    uint x;
    int far[];
};
struct Struct_5 {
    uint index;
};
Struct_1 global_0 : register(b10);
Struct_4 global_1[1] : register(u0);

struct main_Output {
    uint color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    uint local_0 = global_0.index;
    uint local_1 = fragment_in.index;
    uint local_2 = 0u;
    local_2 = global_1[0].x;
    local_2 = global_1[local_0].x;
    local_2 = global_1[local_1].x;
    local_2 = arrayLength(&global_1[0].far);
    local_2 = arrayLength(&global_1[local_0].far);
    local_2 = arrayLength(&global_1[local_1].far);
    return local_2;
    return stage_out;
}

void arrayLength(void arg_0) {
}

void arrayLength(void arg_0) {
}

void arrayLength(void arg_0) {
}
