// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint index;
};
struct Struct_2 {
    uint index;
};
Texture2D<float4> global_0[] : register(t0);
Texture2D<float4> global_1[5] : register(t1);
Texture2DArray<float4> global_2[5] : register(t2);
Texture2DMS<float4> global_3[5] : register(t3);
Texture2D<float> global_4[5] : register(t4);
texture_storage_2d<rgba32float, write> global_5[5] : register(t5);
SamplerState global_6[5] : register(t6);
sampler_comparison global_7[5] : register(t7);
Struct_1 global_8 : register(b8);

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    uint local_0 = global_8.index;
    uint local_1 = fragment_in.index;
    uint local_2 = 0u;
    uint2 local_3 = uint2(0u);
    float local_4 = 0.0f;
    float4 local_5 = float4(0.0f);
    float2 local_6 = float2(0.0f);
    int2 local_7 = int2(0);
    local_3 = textureDimensions(global_0[0]);
    local_3 = textureDimensions(global_0[local_0]);
    local_3 = textureDimensions(global_0[local_1]);
    local_5 = textureGather(0, global_1[0], global_6[0], local_6);
    local_5 = textureGather(0, global_1[local_0], global_6[local_0], local_6);
    local_5 = textureGather(0, global_1[local_1], global_6[local_1], local_6);
    local_5 = textureGatherCompare(global_4[0], global_7[0], local_6, 0.0f);
    local_5 = textureGatherCompare(global_4[local_0], global_7[local_0], local_6, 0.0f);
    local_5 = textureGatherCompare(global_4[local_1], global_7[local_1], local_6, 0.0f);
    local_5 = textureLoad(global_0[0], local_7, 0);
    local_5 = textureLoad(global_0[local_0], local_7, 0);
    local_5 = textureLoad(global_0[local_1], local_7, 0);
    local_2 = textureNumLayers(global_2[0]);
    local_2 = textureNumLayers(global_2[local_0]);
    local_2 = textureNumLayers(global_2[local_1]);
    local_2 = textureNumLevels(global_1[0]);
    local_2 = textureNumLevels(global_1[local_0]);
    local_2 = textureNumLevels(global_1[local_1]);
    local_2 = textureNumSamples(global_3[0]);
    local_2 = textureNumSamples(global_3[local_0]);
    local_2 = textureNumSamples(global_3[local_1]);
    local_5 = textureSample(global_1[0], global_6[0], local_6);
    local_5 = textureSample(global_1[local_0], global_6[local_0], local_6);
    local_5 = textureSample(global_1[local_1], global_6[local_1], local_6);
    local_5 = textureSampleBias(global_1[0], global_6[0], local_6, 0.0f);
    local_5 = textureSampleBias(global_1[local_0], global_6[local_0], local_6, 0.0f);
    local_5 = textureSampleBias(global_1[local_1], global_6[local_1], local_6, 0.0f);
    local_4 = textureSampleCompare(global_4[0], global_7[0], local_6, 0.0f);
    local_4 = textureSampleCompare(global_4[local_0], global_7[local_0], local_6, 0.0f);
    local_4 = textureSampleCompare(global_4[local_1], global_7[local_1], local_6, 0.0f);
    local_4 = textureSampleCompareLevel(global_4[0], global_7[0], local_6, 0.0f);
    local_4 = textureSampleCompareLevel(global_4[local_0], global_7[local_0], local_6, 0.0f);
    local_4 = textureSampleCompareLevel(global_4[local_1], global_7[local_1], local_6, 0.0f);
    local_5 = textureSampleGrad(global_1[0], global_6[0], local_6, local_6, local_6);
    local_5 = textureSampleGrad(global_1[local_0], global_6[local_0], local_6, local_6, local_6);
    local_5 = textureSampleGrad(global_1[local_1], global_6[local_1], local_6, local_6, local_6);
    local_5 = textureSampleLevel(global_1[0], global_6[0], local_6, 0.0f);
    local_5 = textureSampleLevel(global_1[local_0], global_6[local_0], local_6, 0.0f);
    local_5 = textureSampleLevel(global_1[local_1], global_6[local_1], local_6, 0.0f);
    textureStore(global_5[0], local_7, local_5);
    textureStore(global_5[local_0], local_7, local_5);
    textureStore(global_5[local_1], local_7, local_5);
    float2 local_8 = float2((local_3 + uint2(local_2)));
    return ((local_5 + float4(local_8[0], local_8[1], local_8[0], local_8[1])) + local_4);
    return stage_out;
}

uint2 textureDimensions(Texture2D<float4> arg_0) {
}

uint2 textureDimensions(Texture2D<float4> arg_0) {
}

uint2 textureDimensions(Texture2D<float4> arg_0) {
}

int textureGather(int arg_0, Texture2D<float4> arg_1, SamplerState arg_2, float2 arg_3) {
}

int textureGather(int arg_0, Texture2D<float4> arg_1, SamplerState arg_2, float2 arg_3) {
}

int textureGather(int arg_0, Texture2D<float4> arg_1, SamplerState arg_2, float2 arg_3) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

Texture2D<float4> textureLoad(Texture2D<float4> arg_0, int2 arg_1, int arg_2) {
}

Texture2D<float4> textureLoad(Texture2D<float4> arg_0, int2 arg_1, int arg_2) {
}

Texture2D<float4> textureLoad(Texture2D<float4> arg_0, int2 arg_1, int arg_2) {
}

uint textureNumLayers(Texture2DArray<float4> arg_0) {
}

uint textureNumLayers(Texture2DArray<float4> arg_0) {
}

uint textureNumLayers(Texture2DArray<float4> arg_0) {
}

uint textureNumLevels(Texture2D<float4> arg_0) {
}

uint textureNumLevels(Texture2D<float4> arg_0) {
}

uint textureNumLevels(Texture2D<float4> arg_0) {
}

uint textureNumSamples(Texture2DMS<float4> arg_0) {
}

uint textureNumSamples(Texture2DMS<float4> arg_0) {
}

uint textureNumSamples(Texture2DMS<float4> arg_0) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSampleBias(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleBias(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleBias(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleGrad(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float2 arg_3, float2 arg_4) {
}

float4 textureSampleGrad(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float2 arg_3, float2 arg_4) {
}

float4 textureSampleGrad(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float2 arg_3, float2 arg_4) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

texture_storage_2d<rgba32float, write> textureStore(texture_storage_2d<rgba32float, write> arg_0, int2 arg_1, float4 arg_2) {
}

texture_storage_2d<rgba32float, write> textureStore(texture_storage_2d<rgba32float, write> arg_0, int2 arg_1, float4 arg_2) {
}

texture_storage_2d<rgba32float, write> textureStore(texture_storage_2d<rgba32float, write> arg_0, int2 arg_1, float4 arg_2) {
}
