// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_4 {
    uint a;
    uint b[10];
    uint c[];
};
Struct_4 global_0 : register(u0);

uint fetch_add_atomic() {
    return atomicAdd(&global_0.a, 1u);
}

uint atomicAdd(void arg_0, uint arg_1) {
}

uint fetch_add_atomic_static_sized_array(int i) {
    return atomicAdd(&global_0.b[i], 1u);
}

uint atomicAdd(void arg_0, uint arg_1) {
}

uint fetch_add_atomic_dynamic_sized_array(int i) {
    return atomicAdd(&global_0.c[i], 1u);
}

uint atomicAdd(void arg_0, uint arg_1) {
}

uint exchange_atomic() {
    return atomicExchange(&global_0.a, 1u);
}

uint atomicExchange(void arg_0, uint arg_1) {
}

uint exchange_atomic_static_sized_array(int i) {
    return atomicExchange(&global_0.b[i], 1u);
}

uint atomicExchange(void arg_0, uint arg_1) {
}

uint exchange_atomic_dynamic_sized_array(int i) {
    return atomicExchange(&global_0.c[i], 1u);
}

uint atomicExchange(void arg_0, uint arg_1) {
}

uint fetch_add_atomic_dynamic_sized_array_static_index() {
    return atomicAdd(&global_0.c[1000], 1u);
}

uint atomicAdd(void arg_0, uint arg_1) {
}

uint exchange_atomic_dynamic_sized_array_static_index() {
    return atomicExchange(&global_0.c[1000], 1u);
}

uint atomicExchange(void arg_0, uint arg_1) {
}

[numthreads(1, 1, 1)]
void main() {
    fetch_add_atomic();
    fetch_add_atomic_static_sized_array(1);
    fetch_add_atomic_dynamic_sized_array(1);
    exchange_atomic();
    exchange_atomic_static_sized_array(1);
    exchange_atomic_dynamic_sized_array(1);
    fetch_add_atomic_dynamic_sized_array_static_index();
    exchange_atomic_dynamic_sized_array_static_index();
}
