// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t0);
Texture2D<float> global_1 : register(t1);
Texture2D<float> global_2 : register(t2);

float test_textureLoad_depth_2d(int2 coords, int level) {
    return textureLoad(global_0, coords, level);
}

Texture2D<float> textureLoad(Texture2D<float> arg_0, int2 arg_1, int arg_2) {
}

float test_textureLoad_depth_2d_array_u(int2 coords, uint index, int level) {
    return textureLoad(global_1, coords, index, level);
}

Texture2D<float> textureLoad(Texture2D<float> arg_0, int2 arg_1, uint arg_2, int arg_3) {
}

float test_textureLoad_depth_2d_array_s(int2 coords, int index, int level) {
    return textureLoad(global_1, coords, index, level);
}

Texture2D<float> textureLoad(Texture2D<float> arg_0, int2 arg_1, int arg_2, int arg_3) {
}

float test_textureLoad_depth_multisampled_2d(int2 coords, int _sample) {
    return textureLoad(global_2, coords, _sample);
}

Texture2D<float> textureLoad(Texture2D<float> arg_0, int2 arg_1, int arg_2) {
}

struct fragment_shader_Output {
    float4 color : SV_Target;
};
fragment_shader_Output fragment_shader() {
    fragment_shader_Output stage_out;
    test_textureLoad_depth_2d(int2(), 0);
    test_textureLoad_depth_2d_array_u(int2(), 0u, 0);
    test_textureLoad_depth_2d_array_s(int2(), 0, 0);
    test_textureLoad_depth_multisampled_2d(int2(), 0);
    return float4(0.0f, 0.0f, 0.0f, 0.0f);
    return stage_out;
}
