// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    float clip_distances[1];
};

struct main_Output {
    float4 position : SV_Position;
    float clip_distances[1] : COLOR;
};
main_Output main() {
    main_Output stage_out;
    Struct_3 local_0;
    local_0.clip_distances[0] = 0.5f;
    return local_0;
    return stage_out;
}
