// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0 = 1;
int global_1 = 2;
bool global_2 = false;

[numthreads(1, 1, 1)]
void foo() {
    int local_0 = ((global_0 + global_1) - 2);
    bool local_1 = false;
}

float3 any(float3 arg_0) {
}

float3 any(float3 arg_0) {
}
