// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0 = 1;

void control_flow() {
    storageBarrier();
    workgroupBarrier();
    textureBarrier();
    int local_0;
    switch (1) {
        default: {
            local_0 = 1;
            break;
        }
    }
    switch (local_0) {
        case 1: {
            local_0 = 0;
            break;
            break;
        }
        case 2: {
            local_0 = 1;
            break;
        }
        case 3: {
            local_0 = 2;
            break;
        }
        case 4: {
            local_0 = 2;
            break;
        }
        case 5: {
            local_0 = 3;
            break;
        }
        case 6: {
            local_0 = 4;
            break;
        }
    }
    switch (0u) {
        case 0u: {
            break;
        }
        default: {
            break;
        }
    }
    switch (local_0) {
        case 1: {
            local_0 = 0;
            break;
            break;
        }
        case 2: {
            local_0 = 1;
            break;
        }
        case 3: {
            local_0 = 2;
            break;
        }
        case 4: {
            break;
        }
        default: {
            local_0 = 3;
            break;
        }
    }
    switch (local_0) {
        case 1: {
            local_0 = 0;
            break;
        }
        case 2: {
            local_0 = 1;
            break;
        }
        case 3: {
            local_0 = 2;
            break;
        }
        case 4: {
            local_0 = 2;
            break;
        }
        case 5: {
            local_0 = 3;
            break;
        }
        case 6: {
            local_0 = 3;
            break;
        }
        default: {
            local_0 = 4;
            break;
        }
    }
}

void storageBarrier() {
}

void workgroupBarrier() {
}

void textureBarrier() {
}

void switch_default_break(int i) {
    switch (i) {
        default: {
            break;
            break;
        }
    }
}

void switch_case_break() {
    switch (0) {
        case 0: {
            break;
            break;
        }
        default: {
            break;
        }
    }
    return;
}

void switch_selector_type_conversion() {
    switch (0u) {
        case 0: {
            break;
        }
        default: {
            break;
        }
    }
    switch (0) {
        case 0u: {
            break;
        }
        default: {
            break;
        }
    }
}

void loop_switch_continue(int x) {
    while (true) {
        switch (x) {
            case 1: {
                continue;
                break;
            }
            default: {
                break;
            }
        }
    }
}

void loop_switch_continue_nesting(int x, int y, int z) {
    while (true) {
        switch (x) {
            case 1: {
                continue;
                break;
            }
            case 2: {
                switch (y) {
                    case 1: {
                        continue;
                        break;
                    }
                    default: {
                        while (true) {
                            switch (z) {
                                case 1: {
                                    continue;
                                    break;
                                }
                                default: {
                                    break;
                                }
                            }
                        }
                        break;
                    }
                }
                break;
            }
            default: {
                break;
            }
        }
        switch (y) {
            default: {
                continue;
                break;
            }
        }
    }
    while (true) {
        switch (y) {
            case 1: {
                switch (z) {
                    default: {
                        continue;
                        break;
                    }
                }
                break;
            }
        }
    }
}

void loop_switch_omit_continue_variable_checks(int x, int y, int z, int w) {
    int local_0 = 0;
    while (true) {
        switch (x) {
            case 1: {
                local_0 = 1;
                break;
            }
            default: {
                break;
            }
        }
    }
    while (true) {
        switch (x) {
            case 1: {
                break;
            }
            case 2: {
                switch (y) {
                    case 1: {
                        continue;
                        break;
                    }
                    default: {
                        switch (z) {
                            case 1: {
                                local_0 = 2;
                                break;
                            }
                            default: {
                                break;
                            }
                        }
                        break;
                    }
                }
                break;
            }
            default: {
                break;
            }
        }
    }
}

void switch_const_expr_case_selectors() {
    int local_0 = 2;
    switch (0) {
        case 0: {
            break;
        }
        case 1: {
            break;
        }
        case 2: {
            break;
        }
        case 3: {
            break;
        }
        case 4: {
            break;
        }
        default: {
            break;
        }
    }
}

[numthreads(1, 1, 1)]
void main() {
    control_flow();
    switch_default_break(1);
    switch_case_break();
    switch_selector_type_conversion();
    switch_const_expr_case_selectors();
    loop_switch_continue(1);
    loop_switch_continue_nesting(1, 2, 3);
    loop_switch_omit_continue_variable_checks(1, 2, 3, 4);
}
