// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

half global_0 = -(65504.0h);
half global_1 = 65504.0h;
float global_2 = -(3.4028235E38f);
float global_3 = 3.4028235E38f;
double global_4 = -(1.7976931348623157E308);
double global_5 = 1.7976931348623157E308;
float global_6 = -(Infinity.0f);
float global_7 = Infinity.0f;

int test_f16_to_i32(half f) {
    return int(f);
}

uint test_f16_to_u32(half f) {
    return uint(f);
}

int64_t test_f16_to_i64(half f) {
    return int64_t(f);
}

uint64_t test_f16_to_u64(half f) {
    return uint64_t(f);
}

int test_f32_to_i32(float f) {
    return int(f);
}

uint test_f32_to_u32(float f) {
    return uint(f);
}

int64_t test_f32_to_i64(float f) {
    return int64_t(f);
}

uint64_t test_f32_to_u64(float f) {
    return uint64_t(f);
}

int test_f64_to_i32(double f) {
    return int(f);
}

uint test_f64_to_u32(double f) {
    return uint(f);
}

int64_t test_f64_to_i64(double f) {
    return int64_t(f);
}

uint64_t test_f64_to_u64(double f) {
    return uint64_t(f);
}

int2 test_f16_to_i32_vec(half2 f) {
    return int2(f);
}

uint2 test_f16_to_u32_vec(half2 f) {
    return uint2(f);
}

int64_t2 test_f16_to_i64_vec(half2 f) {
    return int64_t2(f);
}

uint64_t2 test_f16_to_u64_vec(half2 f) {
    return uint64_t2(f);
}

int2 test_f32_to_i32_vec(float2 f) {
    return int2(f);
}

uint2 test_f32_to_u32_vec(float2 f) {
    return uint2(f);
}

int64_t2 test_f32_to_i64_vec(float2 f) {
    return int64_t2(f);
}

uint64_t2 test_f32_to_u64_vec(float2 f) {
    return uint64_t2(f);
}

int2 test_f64_to_i32_vec(double2 f) {
    return int2(f);
}

uint2 test_f64_to_u32_vec(double2 f) {
    return uint2(f);
}

int64_t2 test_f64_to_i64_vec(double2 f) {
    return int64_t2(f);
}

uint64_t2 test_f64_to_u64_vec(double2 f) {
    return uint64_t2(f);
}

void test_const_eval() {
    int local_0 = int(global_0);
    int local_1 = int(global_1);
    uint local_2 = uint(global_0);
    uint local_3 = uint(global_1);
    int64_t local_4 = int64_t(global_0);
    int64_t local_5 = int64_t(global_1);
    uint64_t local_6 = uint64_t(global_0);
    uint64_t local_7 = uint64_t(global_1);
    int local_8 = int(global_2);
    int local_9 = int(global_3);
    uint local_10 = uint(global_2);
    uint local_11 = uint(global_3);
    int64_t local_12 = int64_t(global_2);
    int64_t local_13 = int64_t(global_3);
    uint64_t local_14 = uint64_t(global_2);
    uint64_t local_15 = uint64_t(global_3);
    int64_t local_16 = int64_t(global_4);
    int64_t local_17 = int64_t(global_5);
    uint64_t local_18 = uint64_t(global_4);
    uint64_t local_19 = uint64_t(global_5);
    int local_20 = int(global_6);
    int local_21 = int(global_7);
    uint local_22 = uint(global_6);
    uint local_23 = uint(global_7);
    int64_t local_24 = int64_t(global_6);
    int64_t local_25 = int64_t(global_7);
    uint64_t local_26 = uint64_t(global_6);
    uint64_t local_27 = uint64_t(global_7);
}

[numthreads(1, 1, 1)]
void main() {
    test_const_eval();
    test_f16_to_i32(1.0h);
    test_f16_to_u32(1.0h);
    test_f16_to_i64(1.0h);
    test_f16_to_u64(1.0h);
    test_f32_to_i32(1.0f);
    test_f32_to_u32(1.0f);
    test_f32_to_i64(1.0f);
    test_f32_to_u64(1.0f);
    test_f64_to_i32(1.0);
    test_f64_to_u32(1.0);
    test_f64_to_i64(1.0);
    test_f64_to_u64(1.0);
    test_f16_to_i32_vec(float2(1.0f, 2.0f));
    test_f16_to_u32_vec(float2(1.0f, 2.0f));
    test_f16_to_i64_vec(float2(1.0f, 2.0f));
    test_f16_to_u64_vec(float2(1.0f, 2.0f));
    test_f32_to_i32_vec(float2(1.0f, 2.0f));
    test_f32_to_u32_vec(float2(1.0f, 2.0f));
    test_f32_to_i64_vec(float2(1.0f, 2.0f));
    test_f32_to_u64_vec(float2(1.0f, 2.0f));
    test_f64_to_i32_vec(float2(1.0f, 2.0f));
    test_f64_to_u32_vec(float2(1.0f, 2.0f));
    test_f64_to_i64_vec(float2(1.0f, 2.0f));
    test_f64_to_u64_vec(float2(1.0f, 2.0f));
}
