// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

coop_mat8x8<f32, A> global_0;
coop_mat8x8<f32, B> global_1;
float global_2[] : register(u0);

[numthreads(8, 8, 1)]
void main() {
    coop_mat8x8<f32, C> local_0 = coopLoad(&global_2[4]);
    coop_mat8x8<f32, C> local_1 = coopMultiplyAdd(global_0, global_1, local_0);
    coopStore(local_1, &global_2[0]);
    local_0 = local_1;
}

coop_mat8x8<f32, C> coopLoad(void arg_0) {
}

coop_mat8x8<f32, C> coopMultiplyAdd(coop_mat8x8<f32, A> arg_0, coop_mat8x8<f32, B> arg_1, coop_mat8x8<f32, C> arg_2) {
}

void coopStore(coop_mat8x8<f32, C> arg_0, void arg_1) {
}
