// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t4);
sampler_comparison global_1 : register(t5);

struct fragment_Output {
    float4 color : SV_Target;
};
fragment_Output fragment() {
    fragment_Output stage_out;
    float3 local_0 = float4(1.0f, 1.0f, 2.0f, 1.0f).xyz;
    float local_1 = textureSampleCompare(global_0, global_1, local_0, int(1), 1.0f);
    return float4(local_1, 1.0f, 1.0f, 1.0f);
    return stage_out;
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float3 arg_2, int arg_3, float arg_4) {
}
