// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint draw_index;
};

struct vertex_Output {
    float4 position : SV_Position;
};
vertex_Output vertex() {
    vertex_Output stage_out;
    return float4(float(input.draw_index), 1.0f, 1.0f, 1.0f);
    return stage_out;
}
