// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct main_Input {
    float4 pos : SV_Position;
};
struct main_Output {
    float color : SV_Target;
};
main_Output main(main_Input stage_in) {
    main_Output stage_out;
    float4 pos = stage_in.pos;
    return (pos[2] - 0.1f);
    return stage_out;
}
