// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return float4(0.4f, 0.3f, 0.2f, 0.1f);
    return stage_out;
}
