// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


[numthreads(1, 1, 1)]
void comp(uint3 id : SV_DispatchThreadID) {
    if ((id[0] == 0)) {
    }
    (1 + 1);
    return;
}
