// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_8 {
    half scalar_f16;
    float scalar_f32;
    half2 vec2_f16;
    float2 vec2_f32;
    half3 vec3_f16;
    float3 vec3_f32;
    half4 vec4_f16;
    float4 vec4_f32;
};

struct test_direct_Input {
    half scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    half2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    half3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    half4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
struct test_direct_Output {
    half scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    half2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    half3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    half4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_direct_Output test_direct(test_direct_Input stage_in) {
    test_direct_Output stage_out;
    half scalar_f16 = stage_in.scalar_f16;
    float scalar_f32 = stage_in.scalar_f32;
    half2 vec2_f16 = stage_in.vec2_f16;
    float2 vec2_f32 = stage_in.vec2_f32;
    half3 vec3_f16 = stage_in.vec3_f16;
    float3 vec3_f32 = stage_in.vec3_f32;
    half4 vec4_f16 = stage_in.vec4_f16;
    float4 vec4_f32 = stage_in.vec4_f32;
    Struct_8 local_0;
    local_0.scalar_f16 = (scalar_f16 + 1.0h);
    local_0.scalar_f32 = (scalar_f32 + 1.0f);
    local_0.vec2_f16 = (vec2_f16 + float2(1.0h));
    local_0.vec2_f32 = (vec2_f32 + float2(1.0f));
    local_0.vec3_f16 = (vec3_f16 + float3(1.0h));
    local_0.vec3_f32 = (vec3_f32 + float3(1.0f));
    local_0.vec4_f16 = (vec4_f16 + float4(1.0h));
    local_0.vec4_f32 = (vec4_f32 + float4(1.0f));
    return local_0;
    return stage_out;
}

struct test_struct_Output {
    half scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    half2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    half3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    half4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_struct_Output test_struct() {
    test_struct_Output stage_out;
    Struct_8 local_0;
    local_0.scalar_f16 = (input.scalar_f16 + 1.0h);
    local_0.scalar_f32 = (input.scalar_f32 + 1.0f);
    local_0.vec2_f16 = (input.vec2_f16 + float2(1.0h));
    local_0.vec2_f32 = (input.vec2_f32 + float2(1.0f));
    local_0.vec3_f16 = (input.vec3_f16 + float3(1.0h));
    local_0.vec3_f32 = (input.vec3_f32 + float3(1.0f));
    local_0.vec4_f16 = (input.vec4_f16 + float4(1.0h));
    local_0.vec4_f32 = (input.vec4_f32 + float4(1.0f));
    return local_0;
    return stage_out;
}

struct test_copy_input_Output {
    half scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    half2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    half3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    half4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_copy_input_Output test_copy_input() {
    test_copy_input_Output stage_out;
    Struct_8 local_0 = input_original;
    Struct_8 local_1;
    local_1.scalar_f16 = (local_0.scalar_f16 + 1.0h);
    local_1.scalar_f32 = (local_0.scalar_f32 + 1.0f);
    local_1.vec2_f16 = (local_0.vec2_f16 + float2(1.0h));
    local_1.vec2_f32 = (local_0.vec2_f32 + float2(1.0f));
    local_1.vec3_f16 = (local_0.vec3_f16 + float3(1.0h));
    local_1.vec3_f32 = (local_0.vec3_f32 + float3(1.0f));
    local_1.vec4_f16 = (local_0.vec4_f16 + float4(1.0h));
    local_1.vec4_f32 = (local_0.vec4_f32 + float4(1.0f));
    return local_1;
    return stage_out;
}

struct test_return_partial_Output {
    half color : SV_Target;
};
test_return_partial_Output test_return_partial() {
    test_return_partial_Output stage_out;
    Struct_8 local_0 = input_original;
    local_0.scalar_f16 = 0.0h;
    return local_0.scalar_f16;
    return stage_out;
}

struct test_component_access_Output {
    half scalar_f16 : TEXCOORD0;
    float scalar_f32 : TEXCOORD1;
    half2 vec2_f16 : TEXCOORD2;
    float2 vec2_f32 : TEXCOORD3;
    half3 vec3_f16 : TEXCOORD4;
    float3 vec3_f32 : TEXCOORD5;
    half4 vec4_f16 : TEXCOORD6;
    float4 vec4_f32 : TEXCOORD7;
};
test_component_access_Output test_component_access() {
    test_component_access_Output stage_out;
    Struct_8 local_0;
    local_0.vec2_f16[0] = input.vec2_f16[1];
    local_0.vec2_f16[1] = input.vec2_f16[0];
    return local_0;
    return stage_out;
}
