// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

double global_0 = 1.0;
double global_1 = 2.0;

double f(double x) {
    global_0;
    double local_0 = (30.0 + 400.0);
    double local_1 = (local_0 + double(5));
    double local_2 = -(1.0);
    return (((x + local_0) + global_1) + 5.0);
}

[numthreads(1, 1, 1)]
void main() {
    f(6.0);
}
