// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct vs_main_Input {
    uint in_vertex_index : SV_VertexID;
};
struct vs_main_Output {
    float4 position : SV_Position;
};
vs_main_Output vs_main(vs_main_Input stage_in) {
    vs_main_Output stage_out;
    uint in_vertex_index = stage_in.in_vertex_index;
    float local_0 = float((int(in_vertex_index) - 1));
    float local_1 = float(((int((in_vertex_index & 1u)) * 2) - 1));
    return float4(local_0, local_1, 0.0f, 1.0f);
    return stage_out;
}

struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return float4(1.0f, 0.0f, 0.0f, 1.0f);
    return stage_out;
}
