// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_9 {
    float4 vec4f;
    int4 vec4i;
    uint4 vec4u;
    float3 vec3f;
    int3 vec3i;
    uint3 vec3u;
};
struct Struct_13 {
    float2 vec2f;
    int2 vec2i;
    uint2 vec2u;
    float scalarf;
    int scalari;
    uint scalaru;
};

struct main_vec4vec3_Output {
    float4 vec4f : TEXCOORD0;
    int4 vec4i : TEXCOORD1;
    uint4 vec4u : TEXCOORD2;
    float3 vec3f : TEXCOORD3;
    int3 vec3i : TEXCOORD4;
    uint3 vec3u : TEXCOORD5;
};
main_vec4vec3_Output main_vec4vec3() {
    main_vec4vec3_Output stage_out;
    Struct_9 local_0;
    local_0.vec4f = float4(0.0f);
    local_0.vec4i = int4(0);
    local_0.vec4u = uint4(0u);
    local_0.vec3f = float3(0.0f);
    local_0.vec3i = int3(0);
    local_0.vec3u = uint3(0u);
    return local_0;
    return stage_out;
}

struct main_vec2scalar_Output {
    float2 vec2f : TEXCOORD0;
    int2 vec2i : TEXCOORD1;
    uint2 vec2u : TEXCOORD2;
    float scalarf : TEXCOORD3;
    int scalari : TEXCOORD4;
    uint scalaru : TEXCOORD5;
};
main_vec2scalar_Output main_vec2scalar() {
    main_vec2scalar_Output stage_out;
    Struct_13 local_0;
    local_0.vec2f = float2(0.0f);
    local_0.vec2i = int2(0);
    local_0.vec2u = uint2(0u);
    local_0.scalarf = 0.0f;
    local_0.scalari = 0;
    local_0.scalaru = 0u;
    return local_0;
    return stage_out;
}
