// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float3 v3;
    float v1;
};
bool global_0 = true;
float global_1[10];
uint global_2;
float2 global_3[] : register(u2);
float4 global_4[20] : register(b3);
float3 global_5 : register(b4);
float3x2 global_6 : register(b5);
float2x4 global_7[2][2] : register(b6);
float4x2 global_8[2][2] : register(b7);
Struct_2 global_9 : register(u1);

void test_msl_packed_vec3_as_arg(float3 arg) {
}

void test_msl_packed_vec3() {
    global_9.v3 = float3(1.0f);
    int local_0 = 1;
    global_9.v3[0] = 1.0f;
    global_9.v3[0] = 2.0f;
    global_9.v3[local_0] = 3.0f;
    Struct_2 local_1 = global_9;
    float3 local_2 = local_1.v3;
    float2 local_3 = local_1.v3.zx;
    test_msl_packed_vec3_as_arg(local_1.v3);
    float3 local_4 = (local_1.v3 * float3x3());
    float3 local_5 = (float3x3() * local_1.v3);
    float3 local_6 = (local_1.v3 * 2.0f);
    float3 local_7 = (2.0f * local_1.v3);
}

[numthreads(1, 1, 1)]
void main() {
    test_msl_packed_vec3();
    global_1[7] = (global_8[0][0] * global_7[0][0][0])[0];
    global_1[6] = (global_6 * global_5)[0];
    global_1[5] = global_3[1][1];
    global_1[4] = global_4[0][3];
    global_1[3] = global_9.v1;
    global_1[2] = global_9.v3[0];
    global_9.v1 = 4.0f;
    global_1[1] = float(arrayLength(&global_3));
    atomicStore(&global_2, 2u);
    float local_0 = 1.0f;
    bool local_1 = true;
}

void arrayLength(void arg_0) {
}

void atomicStore(void arg_0, uint arg_1) {
}
