// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_2d<u32> global_0 : register(t0);
texture_multisampled_2d<u32> global_1 : register(t3);
Texture2D<float> global_2 : register(t4);
texture_storage_2d<rgba8uint, read> global_3 : register(t1);
texture_2d_array<u32> global_4 : register(t5);
texture_storage_1d<r32uint, read> global_5 : register(t6);
texture_1d<u32> global_6 : register(t7);
texture_storage_1d<r32uint, write> global_7 : register(t2);
Texture1D<float4> global_8 : register(t0);
Texture2D<float4> global_9 : register(t1);
texture_2d<u32> global_10 : register(t2);
texture_2d<i32> global_11 : register(t3);
Texture2DArray<float4> global_12 : register(t4);
TextureCube<float4> global_13 : register(t5);
TextureCubeArray<float4> global_14 : register(t6);
Texture3D<float4> global_15 : register(t7);
Texture2DMS<float4> global_16 : register(t8);
SamplerState global_17 : register(t0);
sampler_comparison global_18 : register(t1);
Texture2D<float> global_19 : register(t2);
Texture2D<float> global_20 : register(t3);
Texture2D<float> global_21 : register(t4);

[numthreads(16, 1, 1)]
void main(uint3 local_id : SV_GroupThreadID) {
    uint2 local_0 = textureDimensions(global_3);
    int2 local_1 = (int2((local_0 * local_id.xy)) % int2(10, 20));
    texture_2d<u32> local_2 = textureLoad(global_0, local_1, int(local_id[2]));
    texture_2d<u32> local_3 = textureLoad(global_0, local_1, uint(local_id[2]));
    texture_multisampled_2d<u32> local_4 = textureLoad(global_1, local_1, int(local_id[2]));
    texture_multisampled_2d<u32> local_5 = textureLoad(global_1, local_1, uint(local_id[2]));
    texture_storage_2d<rgba8uint, read> local_6 = textureLoad(global_3, local_1);
    texture_2d_array<u32> local_7 = textureLoad(global_4, local_1, local_id[2], (int(local_id[2]) + 1));
    texture_2d_array<u32> local_8 = textureLoad(global_4, local_1, int(local_id[2]), (int(local_id[2]) + 1));
    texture_1d<u32> local_9 = textureLoad(global_6, int(local_id[0]), int(local_id[2]));
    texture_storage_1d<r32uint, read> local_10 = textureLoad(global_5, int(local_id[0]));
    texture_2d<u32> local_11 = textureLoad(global_0, uint2(local_1), int(local_id[2]));
    texture_multisampled_2d<u32> local_12 = textureLoad(global_1, uint2(local_1), int(local_id[2]));
    texture_multisampled_2d<u32> local_13 = textureLoad(global_1, uint2(local_1), uint(local_id[2]));
    texture_storage_2d<rgba8uint, read> local_14 = textureLoad(global_3, uint2(local_1));
    texture_2d_array<u32> local_15 = textureLoad(global_4, uint2(local_1), local_id[2], (int(local_id[2]) + 1));
    texture_2d_array<u32> local_16 = textureLoad(global_4, uint2(local_1), int(local_id[2]), (int(local_id[2]) + 1));
    texture_1d<u32> local_17 = textureLoad(global_6, uint(local_id[0]), int(local_id[2]));
    textureStore(global_7, local_1[0], ((((local_2 + local_4) + local_6) + local_7) + local_8));
    textureStore(global_7, uint(local_1[0]), ((((local_11 + local_12) + local_14) + local_15) + local_16));
}

uint2 textureDimensions(texture_storage_2d<rgba8uint, read> arg_0) {
}

texture_2d<u32> textureLoad(texture_2d<u32> arg_0, int2 arg_1, int arg_2) {
}

texture_2d<u32> textureLoad(texture_2d<u32> arg_0, int2 arg_1, uint arg_2) {
}

texture_multisampled_2d<u32> textureLoad(texture_multisampled_2d<u32> arg_0, int2 arg_1, int arg_2) {
}

texture_multisampled_2d<u32> textureLoad(texture_multisampled_2d<u32> arg_0, int2 arg_1, uint arg_2) {
}

texture_storage_2d<rgba8uint, read> textureLoad(texture_storage_2d<rgba8uint, read> arg_0, int2 arg_1) {
}

texture_2d_array<u32> textureLoad(texture_2d_array<u32> arg_0, int2 arg_1, uint arg_2, int arg_3) {
}

texture_2d_array<u32> textureLoad(texture_2d_array<u32> arg_0, int2 arg_1, int arg_2, int arg_3) {
}

texture_1d<u32> textureLoad(texture_1d<u32> arg_0, int arg_1, int arg_2) {
}

texture_storage_1d<r32uint, read> textureLoad(texture_storage_1d<r32uint, read> arg_0, int arg_1) {
}

texture_2d<u32> textureLoad(texture_2d<u32> arg_0, uint2 arg_1, int arg_2) {
}

texture_multisampled_2d<u32> textureLoad(texture_multisampled_2d<u32> arg_0, uint2 arg_1, int arg_2) {
}

texture_multisampled_2d<u32> textureLoad(texture_multisampled_2d<u32> arg_0, uint2 arg_1, uint arg_2) {
}

texture_storage_2d<rgba8uint, read> textureLoad(texture_storage_2d<rgba8uint, read> arg_0, uint2 arg_1) {
}

texture_2d_array<u32> textureLoad(texture_2d_array<u32> arg_0, uint2 arg_1, uint arg_2, int arg_3) {
}

texture_2d_array<u32> textureLoad(texture_2d_array<u32> arg_0, uint2 arg_1, int arg_2, int arg_3) {
}

texture_1d<u32> textureLoad(texture_1d<u32> arg_0, uint arg_1, int arg_2) {
}

texture_storage_1d<r32uint, write> textureStore(texture_storage_1d<r32uint, write> arg_0, int arg_1, texture_2d<u32> arg_2) {
}

texture_storage_1d<r32uint, write> textureStore(texture_storage_1d<r32uint, write> arg_0, uint arg_1, texture_2d<u32> arg_2) {
}

[numthreads(16, 1, 1)]
void depth_load(uint3 local_id : SV_GroupThreadID) {
    uint2 local_0 = textureDimensions(global_3);
    int2 local_1 = (int2((local_0 * local_id.xy)) % int2(10, 20));
    float local_2 = textureLoad(global_2, local_1, int(local_id[2]));
    textureStore(global_7, local_1[0], uint4(uint(local_2)));
    return;
}

uint2 textureDimensions(texture_storage_2d<rgba8uint, read> arg_0) {
}

Texture2D<float> textureLoad(Texture2D<float> arg_0, int2 arg_1, int arg_2) {
}

texture_storage_1d<r32uint, write> textureStore(texture_storage_1d<r32uint, write> arg_0, int arg_1, uint4 arg_2) {
}

struct queries_Output {
    float4 position : SV_Position;
};
queries_Output queries() {
    queries_Output stage_out;
    uint local_0 = textureDimensions(global_8);
    uint local_1 = textureDimensions(global_8, int(local_0));
    uint2 local_2 = textureDimensions(global_9);
    uint2 local_3 = textureDimensions(global_9, 1);
    uint2 local_4 = textureDimensions(global_12);
    uint2 local_5 = textureDimensions(global_12, 1);
    uint2 local_6 = textureDimensions(global_13);
    uint2 local_7 = textureDimensions(global_13, 1);
    uint2 local_8 = textureDimensions(global_14);
    uint2 local_9 = textureDimensions(global_14, 1);
    uint3 local_10 = textureDimensions(global_15);
    uint3 local_11 = textureDimensions(global_15, 1);
    uint2 local_12 = textureDimensions(global_16);
    uint local_13 = ((((((((((local_0 + local_2[1]) + local_3[1]) + local_4[1]) + local_5[1]) + local_6[1]) + local_7[1]) + local_8[1]) + local_9[1]) + local_10[2]) + local_11[2]);
    return float4(float(local_13));
    return stage_out;
}

uint textureDimensions(Texture1D<float4> arg_0) {
}

uint textureDimensions(Texture1D<float4> arg_0, int arg_1) {
}

uint2 textureDimensions(Texture2D<float4> arg_0) {
}

uint2 textureDimensions(Texture2D<float4> arg_0, int arg_1) {
}

uint2 textureDimensions(Texture2DArray<float4> arg_0) {
}

uint2 textureDimensions(Texture2DArray<float4> arg_0, int arg_1) {
}

uint2 textureDimensions(TextureCube<float4> arg_0) {
}

uint2 textureDimensions(TextureCube<float4> arg_0, int arg_1) {
}

uint2 textureDimensions(TextureCubeArray<float4> arg_0) {
}

uint2 textureDimensions(TextureCubeArray<float4> arg_0, int arg_1) {
}

uint3 textureDimensions(Texture3D<float4> arg_0) {
}

uint3 textureDimensions(Texture3D<float4> arg_0, int arg_1) {
}

uint2 textureDimensions(Texture2DMS<float4> arg_0) {
}

struct levels_queries_Output {
    float4 position : SV_Position;
};
levels_queries_Output levels_queries() {
    levels_queries_Output stage_out;
    uint local_0 = textureNumLevels(global_9);
    uint local_1 = textureNumLayers(global_12);
    uint local_2 = textureNumLevels(global_12);
    uint local_3 = textureNumLayers(global_12);
    uint local_4 = textureNumLevels(global_13);
    uint local_5 = textureNumLevels(global_14);
    uint local_6 = textureNumLayers(global_14);
    uint local_7 = textureNumLevels(global_15);
    uint local_8 = textureNumSamples(global_16);
    uint local_9 = (((((((local_1 + local_6) + local_8) + local_0) + local_2) + local_7) + local_4) + local_5);
    return float4(float(local_9));
    return stage_out;
}

uint textureNumLevels(Texture2D<float4> arg_0) {
}

uint textureNumLayers(Texture2DArray<float4> arg_0) {
}

uint textureNumLevels(Texture2DArray<float4> arg_0) {
}

uint textureNumLayers(Texture2DArray<float4> arg_0) {
}

uint textureNumLevels(TextureCube<float4> arg_0) {
}

uint textureNumLevels(TextureCubeArray<float4> arg_0) {
}

uint textureNumLayers(TextureCubeArray<float4> arg_0) {
}

uint textureNumLevels(Texture3D<float4> arg_0) {
}

uint textureNumSamples(Texture2DMS<float4> arg_0) {
}

struct texture_sample_Output {
    float4 color : SV_Target;
};
texture_sample_Output texture_sample() {
    texture_sample_Output stage_out;
    float2 local_0 = float2(0.5f);
    float3 local_1 = float3(0.5f);
    int2 local_2 = int2(3, 1);
    float local_3 = 2.3f;
    float4 local_4;
    local_4 = textureSample(global_8, global_17, local_0[0]);
    local_4 = textureSample(global_9, global_17, local_0);
    local_4 = textureSample(global_9, global_17, local_0, int2(3, 1));
    local_4 = textureSampleLevel(global_9, global_17, local_0, local_3);
    local_4 = textureSampleLevel(global_9, global_17, local_0, local_3, local_2);
    local_4 = textureSampleBias(global_9, global_17, local_0, 2.0f, local_2);
    local_4 = textureSampleBaseClampToEdge(global_9, global_17, local_0);
    local_4 = textureSample(global_12, global_17, local_0, 0u);
    local_4 = textureSample(global_12, global_17, local_0, 0u, local_2);
    local_4 = textureSampleLevel(global_12, global_17, local_0, 0u, local_3);
    local_4 = textureSampleLevel(global_12, global_17, local_0, 0u, local_3, local_2);
    local_4 = textureSampleBias(global_12, global_17, local_0, 0u, 2.0f, local_2);
    local_4 = textureSample(global_12, global_17, local_0, 0);
    local_4 = textureSample(global_12, global_17, local_0, 0, local_2);
    local_4 = textureSampleLevel(global_12, global_17, local_0, 0, local_3);
    local_4 = textureSampleLevel(global_12, global_17, local_0, 0, local_3, local_2);
    local_4 = textureSampleBias(global_12, global_17, local_0, 0, 2.0f, local_2);
    local_4 = textureSample(global_14, global_17, local_1, 0u);
    local_4 = textureSampleLevel(global_14, global_17, local_1, 0u, local_3);
    local_4 = textureSampleBias(global_14, global_17, local_1, 0u, 2.0f);
    local_4 = textureSample(global_14, global_17, local_1, 0);
    local_4 = textureSampleLevel(global_14, global_17, local_1, 0, local_3);
    local_4 = textureSampleBias(global_14, global_17, local_1, 0, 2.0f);
    return local_4;
    return stage_out;
}

float4 textureSample(Texture1D<float4> arg_0, SamplerState arg_1, float arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, int2 arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3) {
}

float4 textureSampleLevel(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3, int2 arg_4) {
}

float4 textureSampleBias(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2, float arg_3, int2 arg_4) {
}

float4 textureSampleBaseClampToEdge(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, uint arg_3) {
}

float4 textureSample(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, uint arg_3, int2 arg_4) {
}

float4 textureSampleLevel(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, uint arg_3, float arg_4) {
}

float4 textureSampleLevel(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, uint arg_3, float arg_4, int2 arg_5) {
}

float4 textureSampleBias(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, uint arg_3, float arg_4, int2 arg_5) {
}

float4 textureSample(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3) {
}

float4 textureSample(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3, int2 arg_4) {
}

float4 textureSampleLevel(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3, float arg_4) {
}

float4 textureSampleLevel(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3, float arg_4, int2 arg_5) {
}

float4 textureSampleBias(Texture2DArray<float4> arg_0, SamplerState arg_1, float2 arg_2, int arg_3, float arg_4, int2 arg_5) {
}

float4 textureSample(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, uint arg_3) {
}

float4 textureSampleLevel(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, uint arg_3, float arg_4) {
}

float4 textureSampleBias(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, uint arg_3, float arg_4) {
}

float4 textureSample(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, int arg_3) {
}

float4 textureSampleLevel(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, int arg_3, float arg_4) {
}

float4 textureSampleBias(TextureCubeArray<float4> arg_0, SamplerState arg_1, float3 arg_2, int arg_3, float arg_4) {
}

struct gather_Output {
    float4 color : SV_Target;
};
gather_Output gather() {
    gather_Output stage_out;
    float2 local_0 = float2(0.5f);
    float local_1 = 0.5f;
    int local_2 = textureGather(1, global_9, global_17, local_0);
    int local_3 = textureGather(3, global_9, global_17, local_0, int2(3, 1));
    Texture2D<float> local_4 = textureGatherCompare(global_19, global_18, local_0, local_1);
    Texture2D<float> local_5 = textureGatherCompare(global_19, global_18, local_0, local_1, int2(3, 1));
    int local_6 = textureGather(0, global_10, global_17, local_0);
    int local_7 = textureGather(0, global_11, global_17, local_0);
    float4 local_8 = (float4(local_6) + float4(local_7));
    return ((((local_2 + local_3) + local_4) + local_5) + local_8);
    return stage_out;
}

int textureGather(int arg_0, Texture2D<float4> arg_1, SamplerState arg_2, float2 arg_3) {
}

int textureGather(int arg_0, Texture2D<float4> arg_1, SamplerState arg_2, float2 arg_3, int2 arg_4) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

Texture2D<float> textureGatherCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3, int2 arg_4) {
}

int textureGather(int arg_0, texture_2d<u32> arg_1, SamplerState arg_2, float2 arg_3) {
}

int textureGather(int arg_0, texture_2d<i32> arg_1, SamplerState arg_2, float2 arg_3) {
}

struct depth_no_comparison_Output {
    float4 color : SV_Target;
};
depth_no_comparison_Output depth_no_comparison() {
    depth_no_comparison_Output stage_out;
    float2 local_0 = float2(0.5f);
    int local_1 = 1;
    float4 local_2 = textureSample(global_19, global_17, local_0);
    Texture2D<float> local_3 = textureGather(global_19, global_17, local_0);
    float4 local_4 = textureSampleLevel(global_19, global_17, local_0, local_1);
    return ((local_2 + local_3) + local_4);
    return stage_out;
}

float4 textureSample(Texture2D<float> arg_0, SamplerState arg_1, float2 arg_2) {
}

Texture2D<float> textureGather(Texture2D<float> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSampleLevel(Texture2D<float> arg_0, SamplerState arg_1, float2 arg_2, int arg_3) {
}

struct texture_sample_comparison_Output {
    float color : SV_Target;
};
texture_sample_comparison_Output texture_sample_comparison() {
    texture_sample_comparison_Output stage_out;
    float2 local_0 = float2(0.5f);
    float3 local_1 = float3(0.5f);
    float local_2 = 0.5f;
    float local_3;
    local_3 = textureSampleCompare(global_19, global_18, local_0, local_2);
    local_3 = textureSampleCompare(global_20, global_18, local_0, 0u, local_2);
    local_3 = textureSampleCompare(global_20, global_18, local_0, 0, local_2);
    local_3 = textureSampleCompare(global_21, global_18, local_1, local_2);
    local_3 = textureSampleCompareLevel(global_19, global_18, local_0, local_2);
    local_3 = textureSampleCompareLevel(global_20, global_18, local_0, 0u, local_2);
    local_3 = textureSampleCompareLevel(global_20, global_18, local_0, 0, local_2);
    local_3 = textureSampleCompareLevel(global_21, global_18, local_1, local_2);
    return local_3;
    return stage_out;
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, uint arg_3, float arg_4) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, int arg_3, float arg_4) {
}

float textureSampleCompare(Texture2D<float> arg_0, sampler_comparison arg_1, float3 arg_2, float arg_3) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, float arg_3) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, uint arg_3, float arg_4) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, int arg_3, float arg_4) {
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float3 arg_2, float arg_3) {
}
