// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


int index_arg_array(int a[5], int i) {
    return a[i];
}

int index_let_array(int i, int j) {
    int local_0[2][2] = int[2][2](int[2](1, 2), int[2](3, 4));
    return local_0[i][j];
}

float index_let_matrix(int i, int j) {
    float2x2 local_0 = float2x2(1, 2, 3, 4);
    return local_0[i][j];
}

float4 index_let_array_1d(uint vi) {
    int local_0[5] = int[5](1, 2, 3, 4, 5);
    int local_1 = local_0[vi];
    return float4(int4(local_1));
}

struct main_Input {
    uint vi : SV_VertexID;
};
struct main_Output {
    float4 position : SV_Position;
};
main_Output main(main_Input stage_in) {
    main_Output stage_out;
    uint vi = stage_in.vi;
    index_arg_array(int[5](1, 2, 3, 4, 5), 6);
    index_let_array(1, 2);
    index_let_matrix(1, 2);
    return index_let_array_1d(vi);
    return stage_out;
}
