// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_11 {
    uint val_u32;
    int val_i32;
    float val_f32;
    uint64_t val_u64;
    uint64_t2 val_u64_2;
    uint64_t3 val_u64_3;
    uint64_t4 val_u64_4;
    int64_t val_i64;
    int64_t2 val_i64_2;
    int64_t3 val_i64_3;
    int64_t4 val_i64_4;
    uint64_t final_value;
};
struct Struct_14 {
    uint64_t val_u64_array_2[2];
    int64_t val_i64_array_2[2];
};
int64_t global_0 = 1;
uint64_t global_1 = 20u;
Struct_11 global_2 : register(b0);
Struct_11 global_3 : register(u1);
Struct_11 global_4 : register(u3);
Struct_14 global_5 : register(u2);
Struct_14 global_6 : register(u4);

int64_t int64_function(int64_t x) {
    global_0;
    int64_t local_0 = int64_t(global_1);
    local_0 = ((31 - 1002003004005006) + -(7));
    local_0 = (local_0 + int64_t(5));
    local_0 = int64_t((global_2.val_u32 + uint(local_0)));
    local_0 = int64_t((global_2.val_i32 + int(local_0)));
    local_0 = int64_t((global_2.val_f32 + float(local_0)));
    local_0 = int64_t3(global_2.val_i64)[2];
    local_0 = asint(global_2.val_u64);
    local_0 = asint(global_2.val_u64_2)[1];
    local_0 = asint(global_2.val_u64_3)[2];
    local_0 = asint(global_2.val_u64_4)[3];
    local_0 = int64_t((-(-1) - 1));
    global_4.val_i64 = (global_2.val_i64 + global_3.val_i64);
    global_4.val_i64_2 = (global_2.val_i64_2 + global_3.val_i64_2);
    global_4.val_i64_3 = (global_2.val_i64_3 + global_3.val_i64_3);
    global_4.val_i64_4 = (global_2.val_i64_4 + global_3.val_i64_4);
    global_6.val_i64_array_2 = global_5.val_i64_array_2;
    local_0 = abs(local_0);
    local_0 = clamp(local_0, local_0, local_0);
    local_0 = dot(float2(local_0), float2(local_0));
    local_0 = max(local_0, local_0);
    local_0 = min(local_0, local_0);
    local_0 = sign(local_0);
    return local_0;
}

int64_t abs(int64_t arg_0) {
}

int64_t clamp(int64_t arg_0, int64_t arg_1, int64_t arg_2) {
}

float2 dot(float2 arg_0, float2 arg_1) {
}

int64_t max(int64_t arg_0, int64_t arg_1) {
}

int64_t min(int64_t arg_0, int64_t arg_1) {
}

int64_t sign(int64_t arg_0) {
}

uint64_t uint64_function(uint64_t x) {
    uint64_t local_0 = uint64_t(global_1);
    local_0 = ((31u + 0u) - 0);
    local_0 = (local_0 + uint64_t(5));
    local_0 = uint64_t((global_2.val_u32 + uint(local_0)));
    local_0 = uint64_t((global_2.val_i32 + int(local_0)));
    local_0 = uint64_t((global_2.val_f32 + float(local_0)));
    local_0 = uint64_t3(global_2.val_u64)[2];
    local_0 = asuint(global_2.val_i64);
    local_0 = asuint(global_2.val_i64_2)[1];
    local_0 = asuint(global_2.val_i64_3)[2];
    local_0 = asuint(global_2.val_i64_4)[3];
    global_4.val_u64 = (global_2.val_u64 + global_3.val_u64);
    global_4.val_u64_2 = (global_2.val_u64_2 + global_3.val_u64_2);
    global_4.val_u64_3 = (global_2.val_u64_3 + global_3.val_u64_3);
    global_4.val_u64_4 = (global_2.val_u64_4 + global_3.val_u64_4);
    global_6.val_u64_array_2 = global_5.val_u64_array_2;
    local_0 = abs(local_0);
    local_0 = clamp(local_0, local_0, local_0);
    local_0 = dot(float2(local_0), float2(local_0));
    local_0 = max(local_0, local_0);
    local_0 = min(local_0, local_0);
    return local_0;
}

uint64_t abs(uint64_t arg_0) {
}

uint64_t clamp(uint64_t arg_0, uint64_t arg_1, uint64_t arg_2) {
}

float2 dot(float2 arg_0, float2 arg_1) {
}

uint64_t max(uint64_t arg_0, uint64_t arg_1) {
}

uint64_t min(uint64_t arg_0, uint64_t arg_1) {
}

[numthreads(1, 1, 1)]
void main() {
    global_4.final_value = (uint64_function(67u) + asuint(int64_function(60)));
}
