// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float4 position;
    float _varying;
};
struct Struct_4 {
    float depth;
    uint sample_mask;
    float color;
};
struct Struct_5 {
    uint index;
};
struct Struct_6 {
    uint index;
};
uint global_0[1];

struct vertex_Input {
    uint vertex_index : SV_VertexID;
    uint instance_index : SV_InstanceID;
    uint color : TEXCOORD10;
};
struct vertex_Output {
    float4 position : SV_Position;
    float _varying : TEXCOORD1;
};
vertex_Output vertex(vertex_Input stage_in) {
    vertex_Output stage_out;
    uint vertex_index = stage_in.vertex_index;
    uint instance_index = stage_in.instance_index;
    uint color = stage_in.color;
    uint local_0 = ((vertex_index + instance_index) + color);
    return Struct_2(float4(1.0f), float(local_0));
    return stage_out;
}

struct fragment_Input {
    bool front_facing : SV_IsFrontFace;
    uint sample_index : SV_SampleIndex;
    uint sample_mask : SV_Coverage;
};
struct fragment_Output {
    float depth : SV_Target;
    uint sample_mask : SV_Target;
    float color : TEXCOORD0;
};
fragment_Output fragment(fragment_Input stage_in) {
    fragment_Output stage_out;
    bool front_facing = stage_in.front_facing;
    uint sample_index = stage_in.sample_index;
    uint sample_mask = stage_in.sample_mask;
    uint local_0 = (sample_mask & (1u << sample_index));
    float local_1 = select(0.0f, 1.0f, front_facing);
    return Struct_4(in._varying, local_0, local_1);
    return stage_out;
}

float select(float arg_0, float arg_1, bool arg_2) {
}

[numthreads(1, 1, 1)]
void compute(uint3 global_id : SV_DispatchThreadID, uint3 local_id : SV_GroupThreadID, uint local_index : SV_GroupIndex, uint3 wg_id : SV_GroupID, uint num_wgs : NUMWORKGROUPS) {
    global_0[0] = ((((global_id[0] + local_id[0]) + local_index) + wg_id[0]) + num_wgs[0]);
}

struct vertex_two_structs_Output {
    float4 position : SV_Position;
};
vertex_two_structs_Output vertex_two_structs() {
    vertex_two_structs_Output stage_out;
    uint local_0 = 2u;
    return float4(float(in1.index), float(in2.index), float(local_0), 0.0f);
    return stage_out;
}
