// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct vs_Output {
    float4 position : SV_Position;
};
vs_Output vs() {
    vs_Output stage_out;
    return float4(0.0f);
    return stage_out;
}

struct fs_Input {
    float4 position : SV_Position;
};
void fs(fs_Input stage_in) {
    float4 position = stage_in.position;
}
