// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    int a;
    float2x2 b;
};
Struct_3 global_0 : register(b0);

[numthreads(1, 1, 1)]
void main() {
    Struct_3 local_0 = global_0;
}
