// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_6 {
    float fract;
    float whole;
};
struct Struct_7 {
    float2 fract;
    float2 whole;
};
struct Struct_8 {
    float4 fract;
    float4 whole;
};
struct Struct_9 {
    float fract;
    int exp;
};
struct Struct_11 {
    float4 fract;
    int4 exp;
};

void main() {
    float local_0 = 1.0f;
    float4 local_1 = float4(0.0f);
    float local_2 = degrees(local_0);
    float local_3 = radians(local_0);
    float4 local_4 = degrees(local_1);
    float4 local_5 = radians(local_1);
    float4 local_6 = saturate(local_1);
    float4 local_7 = refract(local_1, local_1, local_0);
    int local_8 = sign(-(1));
    float4 local_9 = sign(float4(-(1)));
    float local_10 = sign(-(1.0f));
    float4 local_11 = sign(float4(-(1.0f)));
    float4 local_12 = sign(float4(0.0f));
    int2 local_13 = dot(int2(), int2());
    uint local_14 = firstLeadingBit(abs(0u));
    int local_15 = firstLeadingBit(-(1));
    float2 local_16 = firstLeadingBit(float2(-(1)));
    float2 local_17 = firstLeadingBit(float2(1u));
    int local_18 = firstTrailingBit(-(1));
    uint local_19 = firstTrailingBit(1u);
    float2 local_20 = firstTrailingBit(float2(-(1)));
    float2 local_21 = firstTrailingBit(float2(1u));
    uint local_22 = countTrailingZeros(0u);
    int local_23 = countTrailingZeros(0);
    int local_24 = countTrailingZeros(0);
    int local_25 = countTrailingZeros(-(1));
    float2 local_26 = countTrailingZeros(float2(0u));
    float2 local_27 = countTrailingZeros(float2(0));
    float2 local_28 = countTrailingZeros(float2(1u));
    float2 local_29 = countTrailingZeros(float2(1));
    int local_30 = countLeadingZeros(-(1));
    uint local_31 = countLeadingZeros(1u);
    float2 local_32 = countLeadingZeros(float2(-(1)));
    float2 local_33 = countLeadingZeros(float2(1u));
    float local_34 = ldexp(1.0f, 2);
    float2 local_35 = ldexp(float2(1.0f, 2.0f), float2(3, 4));
    Struct_6 local_36 = modf(1.5f);
    float local_37 = modf(1.5f)[0];
    float local_38 = modf(1.5f)[1];
    Struct_7 local_39 = modf(float2(1.5f, 1.5f));
    float local_40 = modf(float4(1.5f, 1.5f, 1.5f, 1.5f))[1][0];
    float local_41 = modf(float2(1.5f, 1.5f))[0][1];
    Struct_9 local_42 = frexp(1.5f);
    float local_43 = frexp(1.5f)[0];
    int local_44 = frexp(1.5f)[1];
    int local_45 = frexp(float4(1.5f, 1.5f, 1.5f, 1.5f))[1][0];
    float local_46 = quantizeToF16(1.0f);
    float2 local_47 = quantizeToF16(float2(1.0f, 1.0f));
    float3 local_48 = quantizeToF16(float3(1.0f, 1.0f, 1.0f));
    float4 local_49 = quantizeToF16(float4(1.0f, 1.0f, 1.0f, 1.0f));
}

float degrees(float arg_0) {
}

float radians(float arg_0) {
}

float4 degrees(float4 arg_0) {
}

float4 radians(float4 arg_0) {
}

float4 saturate(float4 arg_0) {
}

float4 refract(float4 arg_0, float4 arg_1, float arg_2) {
}

int sign(int arg_0) {
}

float4 sign(float4 arg_0) {
}

float sign(float arg_0) {
}

float4 sign(float4 arg_0) {
}

float4 sign(float4 arg_0) {
}

int2 dot(int2 arg_0, int2 arg_1) {
}

uint abs(uint arg_0) {
}

uint firstLeadingBit(uint arg_0) {
}

int firstLeadingBit(int arg_0) {
}

float2 firstLeadingBit(float2 arg_0) {
}

float2 firstLeadingBit(float2 arg_0) {
}

int firstTrailingBit(int arg_0) {
}

uint firstTrailingBit(uint arg_0) {
}

float2 firstTrailingBit(float2 arg_0) {
}

float2 firstTrailingBit(float2 arg_0) {
}

uint countTrailingZeros(uint arg_0) {
}

int countTrailingZeros(int arg_0) {
}

int countTrailingZeros(int arg_0) {
}

int countTrailingZeros(int arg_0) {
}

float2 countTrailingZeros(float2 arg_0) {
}

float2 countTrailingZeros(float2 arg_0) {
}

float2 countTrailingZeros(float2 arg_0) {
}

float2 countTrailingZeros(float2 arg_0) {
}

int countLeadingZeros(int arg_0) {
}

uint countLeadingZeros(uint arg_0) {
}

float2 countLeadingZeros(float2 arg_0) {
}

float2 countLeadingZeros(float2 arg_0) {
}

float ldexp(float arg_0, int arg_1) {
}

float2 ldexp(float2 arg_0, float2 arg_1) {
}

Struct_6 modf(float arg_0) {
}

Struct_6 modf(float arg_0) {
}

Struct_6 modf(float arg_0) {
}

Struct_7 modf(float2 arg_0) {
}

Struct_8 modf(float4 arg_0) {
}

Struct_7 modf(float2 arg_0) {
}

Struct_9 frexp(float arg_0) {
}

Struct_9 frexp(float arg_0) {
}

Struct_9 frexp(float arg_0) {
}

Struct_11 frexp(float4 arg_0) {
}

float quantizeToF16(float arg_0) {
}

float2 quantizeToF16(float2 arg_0) {
}

float3 quantizeToF16(float3 arg_0) {
}

float4 quantizeToF16(float4 arg_0) {
}
