// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint dummy;
};
struct Struct_4 {
    float4 position;
};
struct Struct_5 {
    uint indices;
};
struct Struct_8 {
    Struct_4 vertices[1];
    Struct_5 primitives[1];
    uint vertex_count;
    uint primitive_count;
};
Struct_1 global_0;
Struct_8 global_1;

uint3 ts_main() {
    return float3(1, 1, 1);
}

void ms_main() {
}
