// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    float4 color;
    float2 texcoord;
};
struct Struct_5 {
    float4 position;
    float3 normal;
    float2 texcoord;
};
float4x4 global_0 : register(b0);

float4 do_lighting(float4 position, float3 normal) {
    return float4(0);
}

struct render_vertex_Input {
    uint v_existing_id : SV_VertexID;
};
struct render_vertex_Output {
    float4 position : SV_Position;
    float4 color : TEXCOORD0;
    float2 texcoord : TEXCOORD1;
};
render_vertex_Output render_vertex(render_vertex_Input stage_in) {
    render_vertex_Output stage_out;
    uint v_existing_id = stage_in.v_existing_id;
    Struct_3 local_0;
    local_0.position = (v_in.position * global_0);
    local_0.color = do_lighting(v_in.position, v_in.normal);
    local_0.texcoord = v_in.texcoord;
    return local_0;
    return stage_out;
}
