// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float4 position;
};
struct Struct_10 {
    uint2 v_uint8;
    uint2 v_uint8x2;
    uint2 v_uint8x4;
    int2 v_sint8;
    int2 v_sint8x2;
    int2 v_sint8x4;
    float2 v_unorm8;
    float2 v_unorm8x2;
    float2 v_unorm8x4;
    float2 v_snorm8;
    float2 v_snorm8x2;
    float2 v_snorm8x4;
    uint2 v_uint16;
    uint2 v_uint16x2;
    uint2 v_uint16x4;
    int2 v_sint16;
    int2 v_sint16x2;
    int2 v_sint16x4;
    float2 v_unorm16;
    float2 v_unorm16x2;
    float2 v_unorm16x4;
    float2 v_snorm16;
    float2 v_snorm16x2;
    float2 v_snorm16x4;
    float2 v_float16;
    float2 v_float16x2;
    float2 v_float16x4;
    float2 v_float32;
    float2 v_float32x2;
    float2 v_float32x3;
    float2 v_float32x4;
    uint2 v_uint32;
    uint2 v_uint32x2;
    uint2 v_uint32x3;
    uint2 v_uint32x4;
    int2 v_sint32;
    int2 v_sint32x2;
    int2 v_sint32x3;
    int2 v_sint32x4;
    float2 v_unorm10_10_10_2;
    float2 v_unorm8x4_bgra;
    half2 v_float16_as_f16;
    half2 v_float16x2_as_f16;
    half2 v_float16x4_as_f16;
};

struct render_vertex_Output {
    float4 position : SV_Position;
};
render_vertex_Output render_vertex() {
    render_vertex_Output stage_out;
    return Struct_2(float4(v_in.v_float32[0]));
    return stage_out;
}
