// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct main_Input {
    uint view_index : VIEWINDEX;
};
void main(main_Input stage_in) {
    uint view_index = stage_in.view_index;
}
