// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


int use_me() {
    return 10;
}

int use_return() {
    return use_me();
}

int use_assign_var() {
    int local_0 = use_me();
    return local_0;
}

int use_assign_let() {
    int local_0 = use_me();
    return local_0;
}

void use_phony_assign() {
    use_me();
}

[numthreads(1, 1, 1)]
void main() {
    use_return();
    use_assign_var();
    use_assign_let();
    use_phony_assign();
}
