// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float4 global_0 = float4(1.0f, 1.0f, 1.0f, 1.0f);
float4 global_1 = float4(0.0f, 0.0f, 0.0f, 0.0f);
float4 global_2 = float4(0.5f, 0.5f, 0.5f, 0.5f);
int4 global_3 = int4(1, 1, 1, 1);
bool global_4 = false;
bool global_5 = true;
bool global_6 = (false && (sqrt(-(1)) != 0));
bool global_7 = (false && ((0u + 1.0f) > 0));
float3 global_8 = !((global_4 || any(float3(false, false, false))));
bool global_9 = (global_4 || global_5);

int sqrt(int arg_0) {
}

float3 any(float3 arg_0) {
}

float4 splat(float m, int n) {
    float2 local_0 = (((2.0f + float2(m)) - 4.0f) / 8.0f);
    int4 local_1 = (int4(n) % 2);
    return (local_0.xyxy + float4(local_1));
}

float2 splat_assignment() {
    float2 local_0 = float2(2.0f);
    local_0 = 1.0f;
    local_0 = 3.0f;
    local_0 = 4.0f;
    return local_0;
}

float3 bool_cast(float3 x) {
    bool3 local_0 = bool3(x);
    return float3(local_0);
}

bool p() {
    return true;
}

bool q() {
    return false;
}

bool r() {
    return true;
}

bool s() {
    return false;
}

void arithmetic() {
    int local_0 = 1;
    uint local_1 = 1u;
    float local_2 = 1.0f;
    int local_3 = 2;
    uint local_4 = 2u;
    float local_5 = 2.0f;
    float local_6 = -(local_2);
    float2 local_7 = -(float2(local_0));
    float2 local_8 = -(float2(local_2));
    int local_9 = (local_3 + local_0);
    uint local_10 = (local_4 + local_1);
    float local_11 = (local_5 + local_2);
    float2 local_12 = (float2(local_3) + float2(local_0));
    float3 local_13 = (float3(local_4) + float3(local_1));
    float4 local_14 = (float4(local_5) + float4(local_2));
    int local_15 = (local_3 - local_0);
    uint local_16 = (local_4 - local_1);
    float local_17 = (local_5 - local_2);
    float2 local_18 = (float2(local_3) - float2(local_0));
    float3 local_19 = (float3(local_4) - float3(local_1));
    float4 local_20 = (float4(local_5) - float4(local_2));
    int local_21 = (local_3 * local_0);
    uint local_22 = (local_4 * local_1);
    float local_23 = (local_5 * local_2);
    float2 local_24 = (float2(local_3) * float2(local_0));
    float3 local_25 = (float3(local_4) * float3(local_1));
    float4 local_26 = (float4(local_5) * float4(local_2));
    int local_27 = (local_3 / local_0);
    uint local_28 = (local_4 / local_1);
    float local_29 = (local_5 / local_2);
    float2 local_30 = (float2(local_3) / float2(local_0));
    float3 local_31 = (float3(local_4) / float3(local_1));
    float4 local_32 = (float4(local_5) / float4(local_2));
    int local_33 = (local_3 % local_0);
    uint local_34 = (local_4 % local_1);
    float local_35 = (local_5 % local_2);
    float2 local_36 = (float2(local_3) % float2(local_0));
    float3 local_37 = (float3(local_4) % float3(local_1));
    float4 local_38 = (float4(local_5) % float4(local_2));
    {
        float2 local_39 = (float2(local_3) + local_0);
        float2 local_40 = (local_3 + float2(local_0));
        float2 local_41 = (float2(local_4) + local_1);
        float2 local_42 = (local_4 + float2(local_1));
        float2 local_43 = (float2(local_5) + local_2);
        float2 local_44 = (local_5 + float2(local_2));
        float2 local_45 = (float2(local_3) - local_0);
        float2 local_46 = (local_3 - float2(local_0));
        float2 local_47 = (float2(local_4) - local_1);
        float2 local_48 = (local_4 - float2(local_1));
        float2 local_49 = (float2(local_5) - local_2);
        float2 local_50 = (local_5 - float2(local_2));
        float2 local_51 = (float2(local_3) * local_0);
        float2 local_52 = (local_3 * float2(local_0));
        float2 local_53 = (float2(local_4) * local_1);
        float2 local_54 = (local_4 * float2(local_1));
        float2 local_55 = (float2(local_5) * local_2);
        float2 local_56 = (local_5 * float2(local_2));
        float2 local_57 = (float2(local_3) / local_0);
        float2 local_58 = (local_3 / float2(local_0));
        float2 local_59 = (float2(local_4) / local_1);
        float2 local_60 = (local_4 / float2(local_1));
        float2 local_61 = (float2(local_5) / local_2);
        float2 local_62 = (local_5 / float2(local_2));
        float2 local_63 = (float2(local_3) % local_0);
        float2 local_64 = (local_3 % float2(local_0));
        float2 local_65 = (float2(local_4) % local_1);
        float2 local_66 = (local_4 % float2(local_1));
        float2 local_67 = (float2(local_5) % local_2);
        float2 local_68 = (local_5 % float2(local_2));
    }
    float3x3 local_69 = (float3x3() + float3x3());
    float3x3 local_70 = (float3x3() - float3x3());
    float3x3 local_71 = (float3x3() * local_2);
    float3x3 local_72 = (local_5 * float3x3());
    float4 local_73 = (float4x3() * float4(local_2));
    float3 local_74 = (float3(local_5) * float4x3());
    float4x3 local_75 = (float4x3() * float3x4());
    int local_76;
    int local_77 = (local_76 + -(-2147483648));
}

void bit() {
    int local_0 = 1;
    uint local_1 = 1u;
    int local_2 = 2;
    uint local_3 = 2u;
    int local_4 = ~(local_0);
    uint local_5 = ~(local_1);
    float2 local_6 = ~(float2(local_0));
    float3 local_7 = ~(float3(local_1));
    int local_8 = (local_2 | local_0);
    uint local_9 = (local_3 | local_1);
    float2 local_10 = (float2(local_2) | float2(local_0));
    float3 local_11 = (float3(local_3) | float3(local_1));
    int local_12 = (local_2 & local_0);
    uint local_13 = (local_3 & local_1);
    float2 local_14 = (float2(local_2) & float2(local_0));
    float3 local_15 = (float3(local_3) & float3(local_1));
    int local_16 = (local_2 ^ local_0);
    uint local_17 = (local_3 ^ local_1);
    float2 local_18 = (float2(local_2) ^ float2(local_0));
    float3 local_19 = (float3(local_3) ^ float3(local_1));
    int local_20 = (local_2 << local_1);
    uint local_21 = (local_3 << local_1);
    float2 local_22 = (float2(local_2) << float2(local_1));
    float3 local_23 = (float3(local_3) << float3(local_1));
    int local_24 = (local_2 >> local_1);
    uint local_25 = (local_3 >> local_1);
    float2 local_26 = (float2(local_2) >> float2(local_1));
    float3 local_27 = (float3(local_3) >> float3(local_1));
}

void comparison() {
    int local_0 = 1;
    uint local_1 = 1u;
    float local_2 = 1.0f;
    int local_3 = 2;
    uint local_4 = 2u;
    float local_5 = 2.0f;
    bool local_6 = (local_3 == local_0);
    bool local_7 = (local_4 == local_1);
    bool local_8 = (local_5 == local_2);
    bool2 local_9 = (float2(local_3) == float2(local_0));
    bool3 local_10 = (float3(local_4) == float3(local_1));
    bool4 local_11 = (float4(local_5) == float4(local_2));
    bool local_12 = (local_3 != local_0);
    bool local_13 = (local_4 != local_1);
    bool local_14 = (local_5 != local_2);
    bool2 local_15 = (float2(local_3) != float2(local_0));
    bool3 local_16 = (float3(local_4) != float3(local_1));
    bool4 local_17 = (float4(local_5) != float4(local_2));
    bool local_18 = (local_3 < local_0);
    bool local_19 = (local_4 < local_1);
    bool local_20 = (local_5 < local_2);
    bool2 local_21 = (float2(local_3) < float2(local_0));
    bool3 local_22 = (float3(local_4) < float3(local_1));
    bool4 local_23 = (float4(local_5) < float4(local_2));
    bool local_24 = (local_3 <= local_0);
    bool local_25 = (local_4 <= local_1);
    bool local_26 = (local_5 <= local_2);
    bool2 local_27 = (float2(local_3) <= float2(local_0));
    bool3 local_28 = (float3(local_4) <= float3(local_1));
    bool4 local_29 = (float4(local_5) <= float4(local_2));
    bool local_30 = (local_3 > local_0);
    bool local_31 = (local_4 > local_1);
    bool local_32 = (local_5 > local_2);
    bool2 local_33 = (float2(local_3) > float2(local_0));
    bool3 local_34 = (float3(local_4) > float3(local_1));
    bool4 local_35 = (float4(local_5) > float4(local_2));
    bool local_36 = (local_3 >= local_0);
    bool local_37 = (local_4 >= local_1);
    bool local_38 = (local_5 >= local_2);
    bool2 local_39 = (float2(local_3) >= float2(local_0));
    bool3 local_40 = (float3(local_4) >= float3(local_1));
    bool4 local_41 = (float4(local_5) >= float4(local_2));
}

void assignment() {
    int local_0 = 0;
    int local_1 = 1;
    uint local_2 = 1u;
    uint local_3 = 2u;
    int local_4 = local_1;
    local_4 = local_1;
    local_4 = local_1;
    local_4 = local_4;
    local_4 = local_4;
    local_4 = local_1;
    local_4 = local_0;
    local_4 = local_0;
    local_4 = local_0;
    local_4 = local_3;
    local_4 = local_2;
    local_4 = (local_4 + 1);
    local_4 = (local_4 - 1);
    int3 local_5 = int3();
    local_5[local_1] = (local_5[local_1] + 1);
    local_5[local_1] = (local_5[local_1] - 1);
}

void negation_avoids_prefix_decrement() {
    int local_0 = 1;
    int local_1 = -(local_0);
    int local_2 = -(-(local_0));
    int local_3 = -(-(local_0));
    int local_4 = -(-(local_0));
    int local_5 = -(-(-(local_0)));
    int local_6 = -(-(-(-(local_0))));
    int local_7 = -(-(-(-(-(local_0)))));
    int local_8 = -(-(-(-(-(local_0)))));
    float local_9 = 1.0f;
    float local_10 = -(local_9);
    float local_11 = -(-(local_9));
    float local_12 = -(-(local_9));
    float local_13 = -(-(local_9));
    float local_14 = -(-(-(local_9)));
    float local_15 = -(-(-(-(local_9))));
    float local_16 = -(-(-(-(-(local_9)))));
    float local_17 = -(-(-(-(-(local_9)))));
}

float4 builtins() {
    bool local_0 = true;
    int local_1 = select(0, 1, local_0);
    float4 local_2 = select(global_1, global_0, local_0);
    float4 local_3 = select(global_0, global_1, bool4(false, false, false, false));
    float4 local_4 = mix(global_1, global_0, global_2);
    float4 local_5 = mix(global_1, global_0, 0.1f);
    float local_6 = asfloat(global_3[0]);
    float4 local_7 = asfloat(global_3);
    int4 local_8 = int4(global_1);
    return (((((float4((int4(local_1) + local_8)) + local_2) + local_4) + local_5) + local_6) + local_7);
}

int select(int arg_0, int arg_1, bool arg_2) {
}

float4 select(float4 arg_0, float4 arg_1, bool arg_2) {
}

float4 select(float4 arg_0, float4 arg_1, bool4 arg_2) {
}

float4 mix(float4 arg_0, float4 arg_1, float4 arg_2) {
}

float4 mix(float4 arg_0, float4 arg_1, float arg_2) {
}

void logical() {
    bool local_0 = true;
    bool local_1 = false;
    bool local_2 = !(local_0);
    float2 local_3 = !(float2(local_0));
    bool local_4 = (local_0 || local_1);
    bool local_5 = (local_0 && local_1);
    bool local_6 = (local_0 | local_1);
    float3 local_7 = (float3(local_0) | float3(local_1));
    bool local_8 = (local_0 & local_1);
    float4 local_9 = (float4(local_0) & float4(local_1));
    bool local_10 = (false && (sqrt(-(1)) != 0));
    bool local_11 = (false && ((0u + 1.0f) > 0));
    bool local_12 = (global_4 || global_5);
    float3 local_13 = !((global_4 || any(float3(false, false, false))));
    float3 local_14 = !((local_1 || any(float3(false, false, false))));
    bool local_15 = ((p() || q()) && (r() || s()));
    bool local_16 = (true || q());
}

int sqrt(int arg_0) {
}

float3 any(float3 arg_0) {
}

float3 any(float3 arg_0) {
}

[numthreads(1, 1, 1)]
void main(uint3 id : SV_GroupID) {
    builtins();
    splat(float(id[0]), int(id[1]));
    splat_assignment();
    bool_cast(global_0.xyz);
    logical();
    arithmetic();
    bit();
    comparison();
    assignment();
    negation_avoids_prefix_decrement();
}
