// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_5 {
    uint old_value;
    bool exchanged;
};
int global_0;
uint global_1;

[numthreads(1, 1, 1)]
void f() {
    atomicCompareExchangeWeak(&global_1, uint(global_0), 1u);
}

Struct_5 atomicCompareExchangeWeak(void arg_0, uint arg_1, uint arg_2) {
}
