// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    int3 chunk;
    uint texture_index;
};
struct Struct_6 {
    float4 clip_position;
};

struct vs_main_Output {
    float4 clip_position : SV_Position;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    Struct_6 local_0;
    float3 local_1 = float3((in.chunk - int3(5)));
    return local_0;
    return stage_out;
}
