// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float3 a;
};
struct Struct_4 {
    float3 a[2];
    float b;
};
struct Struct_6 {
    float4x3 a;
    float b;
};
struct Struct_7 {
    Struct_2 a;
    float b;
};
Struct_4 global_0 : register(b1);
Struct_6 global_1 : register(b2);
Struct_7 global_2 : register(b0);

struct vertex_Output {
    float4 position : SV_Position;
};
vertex_Output vertex() {
    vertex_Output stage_out;
    return (((float4(1.0f) * global_2.b) * global_0.b) * global_1.b);
    return stage_out;
}
