// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct fs_main_Input {
    float v[3] : TEXCOORD0;
};
struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main(fs_main_Input stage_in) {
    fs_main_Output stage_out;
    float[3] v = stage_in.v;
    return float4(v[0], v[1], v[2], 1.0f);
    return stage_out;
}
