// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

float global_0 : register(b0);

int five() {
    return 5;
}

[numthreads(1, 1, 1)]
void main(uint3 id : SV_DispatchThreadID) {
    global_0;
    global_0;
    int local_0 = 5;
    local_0;
    five();
    int local_1 = five();
    float local_2 = global_0;
}
