// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    uint arr[];
};
Struct_2 global_0 : register(u0);

void f() {
    float2x2 local_0;
    void local_1 = &local_0[0];
    local_1 = float2(10.0f);
}

void index_unsized(int i, uint v) {
    Struct_2* local_0 = &global_0;
    uint local_1 = local_0.arr[i];
    local_0.arr[i] = (local_1 + v);
}

void index_dynamic_array(int i, uint v) {
    uint[]* local_0 = &global_0.arr;
    uint local_1 = local_0[i];
    local_0[i] = (local_1 + v);
}

[numthreads(1, 1, 1)]
void main() {
    f();
    index_unsized(1, 1);
    index_dynamic_array(1, 1);
}
