// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


struct func_Input {
    uint index : PRIMITIVEINDEX;
};
struct func_Output {
    float4 color : SV_Target;
};
func_Output func(func_Input stage_in) {
    func_Output stage_out;
    uint index = stage_in.index;
    return float4(float(index), 1.0f, 1.0f, 1.0f);
    return stage_out;
}
