// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    float multiplier;
};
struct Struct_3 {
    float4 color;
};
Struct_1 global_0;

struct vert_main_Input {
    float2 pos : TEXCOORD0;
    uint ii : SV_InstanceID;
    uint vi : SV_VertexID;
};
struct vert_main_Output {
    float4 position : SV_Position;
};
vert_main_Output vert_main(vert_main_Input stage_in) {
    vert_main_Output stage_out;
    float2 pos = stage_in.pos;
    uint ii = stage_in.ii;
    uint vi = stage_in.vi;
    return float4((((float(ii) * float(vi)) * global_0.multiplier) * pos), 0.0f, 1.0f);
    return stage_out;
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return (in.color * global_0.multiplier);
    return stage_out;
}
