// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float2 uv;
    float4 position;
};
float global_0 = 1.2f;
Texture2D<float4> global_1 : register(t0);
SamplerState global_2 : register(t1);

struct fs_extra_Output {
    float4 color : SV_Target;
};
fs_extra_Output fs_extra() {
    fs_extra_Output stage_out;
    return float4(0.0f, 0.5f, 0.0f, 0.5f);
    return stage_out;
}

struct vert_main_Input {
    float2 pos : TEXCOORD0;
    float2 uv : TEXCOORD1;
};
struct vert_main_Output {
    float2 uv : TEXCOORD0;
    float4 position : SV_Position;
};
vert_main_Output vert_main(vert_main_Input stage_in) {
    vert_main_Output stage_out;
    float2 pos = stage_in.pos;
    float2 uv = stage_in.uv;
    return Struct_3(uv, float4((global_0 * pos), 0.0f, 1.0f));
    return stage_out;
}

struct frag_main_Input {
    float2 uv : TEXCOORD0;
};
struct frag_main_Output {
    float4 color : SV_Target;
};
frag_main_Output frag_main(frag_main_Input stage_in) {
    frag_main_Output stage_out;
    float2 uv = stage_in.uv;
    float4 local_0 = textureSample(global_1, global_2, uv);
    if ((local_0[3] == 0.0f)) {
        discard;
    }
    float4 local_1 = (local_0[3] * local_0);
    return local_1;
    return stage_out;
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}
