// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    uint visible;
    float3 normal;
};
struct Struct_8 {
    uint kind;
    float t;
    uint instance_custom_data;
    uint instance_index;
    uint sbt_record_offset;
    uint geometry_index;
    uint primitive_index;
    float2 barycentrics;
    bool front_face;
    float4x3 object_to_world;
    float4x3 world_to_object;
};
RaytracingAccelerationStructure global_0 : register(t0);
Struct_3 global_1 : register(u1);

Struct_8 query_loop(float3 pos, float3 dir, RaytracingAccelerationStructure acs) {
    RayQuery local_0;
    rayQueryInitialize(&local_0, acs, RayDesc(4u, 0, 0.1f, 100.0f, pos, dir));
    while (true) {
        if (rayQueryProceed(&local_0)) {
        } else {
            break;
        }
    }
    return rayQueryGetCommittedIntersection(&local_0);
}

uint RayDesc(uint arg_0, int arg_1, float arg_2, float arg_3, float3 arg_4, float3 arg_5) {
}

void rayQueryInitialize(void arg_0, RaytracingAccelerationStructure arg_1, uint arg_2) {
}

bool rayQueryProceed(void arg_0) {
}

Struct_8 rayQueryGetCommittedIntersection(void arg_0) {
}

float3 get_torus_normal(float3 world_point, Struct_8 intersection) {
    float4 local_0 = (intersection.world_to_object * float4(world_point, 1.0f));
    float2 local_1 = (normalize(local_0.xy) * 2.4f);
    float4 local_2 = (intersection.object_to_world * float4(local_1, 0.0f, 1.0f));
    return normalize((world_point - local_2));
}

float2 normalize(float2 arg_0) {
}

float3 normalize(float3 arg_0) {
}

[numthreads(1, 1, 1)]
void main_candidate() {
    float3 local_0 = float3(0.0f);
    float3 local_1 = float3(0.0f, 1.0f, 0.0f);
    RayQuery local_2;
    rayQueryInitialize(&local_2, global_0, RayDesc(4u, 0, 0.1f, 100.0f, local_0, local_1));
    Struct_8 local_3 = rayQueryGetCandidateIntersection(&local_2);
    if ((local_3.kind == 3u)) {
        rayQueryGenerateIntersection(&local_2, 10.0f);
    } else {
        if ((local_3.kind == 1u)) {
            rayQueryConfirmIntersection(&local_2);
        } else {
            rayQueryTerminate(&local_2);
        }
    }
}

uint RayDesc(uint arg_0, int arg_1, float arg_2, float arg_3, float3 arg_4, float3 arg_5) {
}

void rayQueryInitialize(void arg_0, RaytracingAccelerationStructure arg_1, uint arg_2) {
}

Struct_8 rayQueryGetCandidateIntersection(void arg_0) {
}

void rayQueryGenerateIntersection(void arg_0, float arg_1) {
}

void rayQueryConfirmIntersection(void arg_0) {
}

void rayQueryTerminate(void arg_0) {
}

[numthreads(1, 1, 1)]
void main() {
    float3 local_0 = float3(0.0f);
    float3 local_1 = float3(0.0f, 1.0f, 0.0f);
    Struct_8 local_2 = query_loop(local_0, local_1, global_0);
    global_1.visible = uint((local_2.kind == 0u));
    global_1.normal = get_torus_normal((local_1 * local_2.t), local_2);
}
