// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint hit_num;
    uint selected_hit;
};
RaytracingAccelerationStructure global_0 : register(t0);
Struct_1 global_1;
Struct_1 global_2;

void miss(float3 origin, float3 dir, float t_min) {
}

void closest_hit_main(float3 origin, float3 dir, float4x3 obj_to_world, float4x3 world_to_obj) {
}

void ray_gen_main(uint3 id, uint3 num_invocations) {
    global_1 = Struct_1();
    float3 local_0 = (float3(id) / float3(num_invocations));
    float3 local_1 = ((float3(local_0[0], 0.0f, local_0[1]) * 2.0f) - 1.0f);
    traceRay(global_0, RayDesc(0u, 0, 0.01f, 100.0f, float3(0.0f), (float3(0.0f, 1.0f, 0.0f) + local_1)), &global_1);
}

uint RayDesc(uint arg_0, int arg_1, float arg_2, float arg_3, float3 arg_4, float3 arg_5) {
}

RaytracingAccelerationStructure traceRay(RaytracingAccelerationStructure arg_0, uint arg_1, void arg_2) {
}

void any_hit_main(uint data, uint geo_idx, float max, uint kind) {
    global_2.hit_num = (global_2.hit_num + 1);
    global_2.selected_hit = data;
}
