// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float4> global_0 : register(t0);
Texture2D<float4> global_1 : register(t1);
SamplerState global_2 : register(t2);
SamplerState global_3 : register(t3);
float2 global_4 : register(b4);
float2 global_5 : register(b0);

struct entry_point_one_Input {
    float4 pos : SV_Position;
};
struct entry_point_one_Output {
    float4 color : SV_Target;
};
entry_point_one_Output entry_point_one(entry_point_one_Input stage_in) {
    entry_point_one_Output stage_out;
    float4 pos = stage_in.pos;
    return textureSample(global_0, global_2, pos.xy);
    return stage_out;
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

struct entry_point_two_Output {
    float4 color : SV_Target;
};
entry_point_two_Output entry_point_two() {
    entry_point_two_Output stage_out;
    return textureSample(global_0, global_2, global_4);
    return stage_out;
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

struct entry_point_three_Output {
    float4 color : SV_Target;
};
entry_point_three_Output entry_point_three() {
    entry_point_three_Output stage_out;
    return (textureSample(global_0, global_2, (global_5 + global_4)) + textureSample(global_1, global_3, global_4));
    return stage_out;
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}
