// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)


void derivatives() {
    float local_0 = dpdx(0.0f);
    float local_1 = dpdy(0.0f);
    float local_2 = fwidth(0.0f);
}

float dpdx(float arg_0) {
}

float dpdy(float arg_0) {
}

float fwidth(float arg_0) {
}

void barriers() {
    storageBarrier();
    workgroupBarrier();
    textureBarrier();
}

void storageBarrier() {
}

void workgroupBarrier() {
}

void textureBarrier() {
}

struct fragment_Output {
    float4 color : SV_Target;
};
fragment_Output fragment() {
    fragment_Output stage_out;
    derivatives();
    return float4();
    return stage_out;
}

[numthreads(1, 1, 1)]
void compute() {
    barriers();
}
