// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_3 {
    float4 position;
    float3 uv;
};
struct Struct_5 {
    float4x4 proj_inv;
    float4x4 view;
};
TextureCube<float4> global_0 : register(t1);
SamplerState global_1 : register(t2);
Struct_5 global_2 : register(b0);

struct fs_main_Output {
    float4 color : SV_Target;
};
fs_main_Output fs_main() {
    fs_main_Output stage_out;
    return textureSample(global_0, global_1, in.uv);
    return stage_out;
}

float4 textureSample(TextureCube<float4> arg_0, SamplerState arg_1, float3 arg_2) {
}

struct vs_main_Input {
    uint vertex_index : SV_VertexID;
};
struct vs_main_Output {
    float4 position : SV_Position;
    float3 uv : TEXCOORD0;
};
vs_main_Output vs_main(vs_main_Input stage_in) {
    vs_main_Output stage_out;
    uint vertex_index = stage_in.vertex_index;
    int local_0 = (int(vertex_index) / 2);
    int local_1 = (int(vertex_index) & 1);
    float4 local_2 = float4(((float(local_0) * 4.0f) - 1.0f), ((float(local_1) * 4.0f) - 1.0f), 0.0f, 1.0f);
    float3x3 local_3 = transpose(float3x3(global_2.view[0].xyz, global_2.view[1].xyz, global_2.view[2].xyz));
    float4 local_4 = (global_2.proj_inv * local_2);
    return Struct_3(local_2, (local_3 * local_4.xyz));
    return stage_out;
}

float3x3 transpose(float3x3 arg_0) {
}
