// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float4> global_0 : register(t0);
SamplerState global_1 : register(t1);

struct main_Input {
    float2 uv : TEXCOORD0;
};
struct main_Output {
    float4 color : SV_Target;
};
main_Output main(main_Input stage_in) {
    main_Output stage_out;
    float2 uv = stage_in.uv;
    return textureSample(global_0, global_1, uv);
    return stage_out;
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}
