// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_storage_2d<r32float, read> global_0 : register(t0);
texture_storage_2d<rg32float, read> global_1 : register(t1);
texture_storage_2d<rgba32float, read> global_2 : register(t2);
texture_storage_2d<r32float, write> global_3 : register(t0);
texture_storage_2d<rg32float, write> global_4 : register(t1);
texture_storage_2d<rgba32float, write> global_5 : register(t2);

[numthreads(1, 1, 1)]
void csLoad() {
    textureLoad(global_0, uint2(0));
    textureLoad(global_1, uint2(0));
    textureLoad(global_2, uint2(0));
}

texture_storage_2d<r32float, read> textureLoad(texture_storage_2d<r32float, read> arg_0, uint2 arg_1) {
}

texture_storage_2d<rg32float, read> textureLoad(texture_storage_2d<rg32float, read> arg_0, uint2 arg_1) {
}

texture_storage_2d<rgba32float, read> textureLoad(texture_storage_2d<rgba32float, read> arg_0, uint2 arg_1) {
}

[numthreads(1, 1, 1)]
void csStore() {
    textureStore(global_3, uint2(0), float4(0.0f));
    textureStore(global_4, uint2(0), float4(0.0f));
    textureStore(global_5, uint2(0), float4(0.0f));
}

texture_storage_2d<r32float, write> textureStore(texture_storage_2d<r32float, write> arg_0, uint2 arg_1, float4 arg_2) {
}

texture_storage_2d<rg32float, write> textureStore(texture_storage_2d<rg32float, write> arg_0, uint2 arg_1, float4 arg_2) {
}

texture_storage_2d<rgba32float, write> textureStore(texture_storage_2d<rgba32float, write> arg_0, uint2 arg_1, float4 arg_2) {
}
