// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float3 v3;
    float f3;
};
struct Struct_3 {
    float f3_forces_padding;
    float3 v3_needs_padding;
    float f3;
};
Struct_2 global_0 : register(b0);
Struct_2 global_1 : register(u1);
Struct_3 global_2 : register(b2);
Struct_3 global_3 : register(u3);

struct no_padding_frag_Output {
    float4 color : SV_Target;
};
no_padding_frag_Output no_padding_frag() {
    no_padding_frag_Output stage_out;
    input;
    return float4(0.0f);
    return stage_out;
}

struct no_padding_vert_Output {
    float4 position : SV_Position;
};
no_padding_vert_Output no_padding_vert() {
    no_padding_vert_Output stage_out;
    input;
    return float4(0.0f);
    return stage_out;
}

struct needs_padding_frag_Output {
    float4 color : SV_Target;
};
needs_padding_frag_Output needs_padding_frag() {
    needs_padding_frag_Output stage_out;
    input;
    return float4(0.0f);
    return stage_out;
}

struct needs_padding_vert_Output {
    float4 position : SV_Position;
};
needs_padding_vert_Output needs_padding_vert() {
    needs_padding_vert_Output stage_out;
    input;
    return float4(0.0f);
    return stage_out;
}

[numthreads(16, 1, 1)]
void no_padding_comp() {
    Struct_2 local_0;
    local_0 = global_0;
    local_0 = global_1;
}

[numthreads(16, 1, 1)]
void needs_padding_comp() {
    Struct_3 local_0;
    local_0 = global_2;
    local_0 = global_3;
}
