// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

uint global_0[1];
uint global_1[1];
uint global_2[] : register(u0);
uint global_3[] : register(u1);

[numthreads(1, 1, 1)]
void main() {
    global_0[0] = global_2[0];
    global_1[0] = global_3[0];
    global_3[0] = (global_0[0] + global_1[0]);
}
