// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

int global_0[2] : register(u0);

[numthreads(1, 1, 1)]
void main() {
    int local_0[];
    {
        int local_1 = 0;
        while (true) {
            if ((local_1 < 2)) {
                {
                    global_0[local_1] = local_0[local_1];
                }
                local_1 = (local_1 + 1);
            } else {
                break;
            }
        }
    }
}
