// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

texture_external global_0 : register(t0);
SamplerState global_1 : register(t1);

float4 test(texture_external t) {
    float4 local_0 = textureSampleBaseClampToEdge(t, global_1, float2(0.0f));
    texture_external local_1 = textureLoad(t, float2(0));
    texture_external local_2 = textureLoad(t, float2(0u));
    uint2 local_3 = textureDimensions(t);
    return (((local_0 + local_1) + local_2) + float2(local_3).xyxy);
}

float4 textureSampleBaseClampToEdge(texture_external arg_0, SamplerState arg_1, float2 arg_2) {
}

texture_external textureLoad(texture_external arg_0, float2 arg_1) {
}

texture_external textureLoad(texture_external arg_0, float2 arg_1) {
}

uint2 textureDimensions(texture_external arg_0) {
}

struct fragment_main_Output {
    float4 color : SV_Target;
};
fragment_main_Output fragment_main() {
    fragment_main_Output stage_out;
    return test(global_0);
    return stage_out;
}

struct vertex_main_Output {
    float4 position : SV_Position;
};
vertex_main_Output vertex_main() {
    vertex_main_Output stage_out;
    return test(global_0);
    return stage_out;
}

[numthreads(1, 1, 1)]
void compute_main() {
    test(global_0);
}
