// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float4> global_0 : register(t0);
SamplerState global_1 : register(t1);

float4 test(Texture2D<float4> Passed_Texture, SamplerState Passed_Sampler) {
    return textureSample(Passed_Texture, Passed_Sampler, float2(0.0f, 0.0f));
}

float4 textureSample(Texture2D<float4> arg_0, SamplerState arg_1, float2 arg_2) {
}

struct main_Output {
    float4 color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    return test(global_0, global_1);
    return stage_out;
}
