// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_1 {
    uint test_m;
};
float4x4 global_0 : register(b0);
float2x2 global_1;
float2x2 global_2;
uint global_3 = 1;

void test_f() {
}

void test_g() {
}

[numthreads(1, 1, 1)]
void test_ep() {
    global_2;
    Struct_1();
    test_g();
}
