// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_2 {
    float4 position;
    float value;
    float4 unused_value2;
    float unused_value;
    float value2;
};

struct vs_main_Output {
    float4 position : SV_Position;
    float value : TEXCOORD1;
    float4 unused_value2 : TEXCOORD2;
    float unused_value : TEXCOORD0;
    float value2 : TEXCOORD3;
};
vs_main_Output vs_main() {
    vs_main_Output stage_out;
    return Struct_2(float4(1.0f), 1.0f, float4(2.0f), 1.0f, 0.5f);
    return stage_out;
}
