// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

Texture2D<float> global_0 : register(t0);
sampler_comparison global_1 : register(t1);

struct main_Output {
    float color : SV_Target;
};
main_Output main() {
    main_Output stage_out;
    float2 local_0 = float2(0.0f);
    int local_1 = 0;
    float local_2 = 0.0f;
    return textureSampleCompareLevel(global_0, global_1, local_0, local_1, local_2);
    return stage_out;
}

float textureSampleCompareLevel(Texture2D<float> arg_0, sampler_comparison arg_1, float2 arg_2, int arg_3, float arg_4) {
}
