// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

uint global_0 = 128u;
int global_1[128];

[numthreads(4, 1, 1)]
void test_workgroupUniformLoad(uint3 workgroup_id : SV_GroupID) {
    void local_0 = &global_1[workgroup_id[0]];
    void local_1 = workgroupUniformLoad(local_0);
    if ((local_1 > 10)) {
        workgroupBarrier();
    }
}

void workgroupUniformLoad(void arg_0) {
}

void workgroupBarrier() {
}
