// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_6 {
    uint arr[512];
    int atom;
    int atom_arr[8][8];
};
uint global_0[512] : register(u0);
Struct_6 global_1;

[numthreads(1, 1, 1)]
void main() {
    global_0 = global_1.arr;
}
