// Generated by WebGPU-KTypes HLSL Backend
#pragma pack_matrix(column_major)

struct Struct_5 {
    uint atomic_scalar;
    int atomic_arr[2];
};
uint global_0;
int global_1;
Struct_5 global_2;

[numthreads(64, 1, 1)]
void test_atomic_workgroup_uniform_load(uint3 workgroup_id : SV_GroupID, uint3 local_id : SV_GroupThreadID) {
    uint local_0 = (workgroup_id[0] + (workgroup_id[1] * 32768));
    atomicOr(&global_0, uint((local_0 >= 64)));
    atomicAdd(&global_1, 1);
    atomicStore(&global_2.atomic_scalar, 1u);
    atomicAdd(&global_2.atomic_arr[0], 1);
    workgroupBarrier();
    uint local_1 = workgroupUniformLoad(&global_0);
    int local_2 = workgroupUniformLoad(&global_1);
    uint local_3 = workgroupUniformLoad(&global_2.atomic_scalar);
    int local_4 = workgroupUniformLoad(&global_2.atomic_arr[0]);
    if (((((local_1 == 0u) && (local_2 > 0)) && (local_3 > 0u)) && (local_4 > 0))) {
        return;
    }
}

uint atomicOr(void arg_0, uint arg_1) {
}

int atomicAdd(void arg_0, int arg_1) {
}

void atomicStore(void arg_0, uint arg_1) {
}

int atomicAdd(void arg_0, int arg_1) {
}

void workgroupBarrier() {
}

void workgroupUniformLoad(void arg_0) {
}

void workgroupUniformLoad(void arg_0) {
}

void workgroupUniformLoad(void arg_0) {
}

void workgroupUniformLoad(void arg_0) {
}
