package org.graphiks.wgsl.wgsl

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.collections.shouldContain
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.graphiks.wgsl.arena.rangeOf
import org.graphiks.wgsl.arena.Arena
import org.graphiks.wgsl.ir.BindingAttribute
import org.graphiks.wgsl.ir.Block
import org.graphiks.wgsl.ir.BuiltinValue
import org.graphiks.wgsl.ir.Expression
import org.graphiks.wgsl.ir.ExpressionKind
import org.graphiks.wgsl.ir.Function
import org.graphiks.wgsl.ir.GlobalVariableDeclaration
import org.graphiks.wgsl.ir.LiteralValue
import org.graphiks.wgsl.ir.Module
import org.graphiks.wgsl.ir.ScalarKind
import org.graphiks.wgsl.ir.ScalarValue
import org.graphiks.wgsl.ir.Statement
import org.graphiks.wgsl.ir.StorageClass
import org.graphiks.wgsl.ir.StructMember
import org.graphiks.wgsl.ir.Type
import org.graphiks.wgsl.ir.TypeInner
import org.graphiks.wgsl.ir.UnaryOperator
import org.graphiks.wgsl.parser.Lowerer
import org.graphiks.wgsl.parser.TypeResolver
import org.graphiks.wgsl.parser.parseWgsl

class WgslWriterTest : FunSpec({

    test("testEmptyModule") {
        val module = Module()
        val code = WgslModule.writeString(module)
        code shouldContain "// Generated by WebGPU-KTypes WGSL Backend"
    }

    test("testModuleWithStructAndFunction") {
        val module = Module()

        // Add a scalar type
        val f32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.F32, 4)))

        // Add a struct
        module.types.append(
            Type(
                TypeInner.Struct(
                    listOf(
                        StructMember("a", f32Handle, null, 0)
                    )
                )
            )
        )

        // Add a function
        val expressions = Arena<Expression>()
        val blocks = Arena<Block>()
        val body = blocks.append(Block(emptyList()))

        module.functions.append(
            Function(
                name = "my_func",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "struct Struct_1"
        code shouldContain "a: f32"
        code shouldContain "fn my_func()"
    }

    test("struct member builtin bindings are written") {
        val module = Module()
        val u32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.Uint, 4)))

        module.types.append(
            Type(
                TypeInner.Struct(
                    listOf(
                        StructMember("draw_index", u32Handle, BindingAttribute.Builtin(BuiltinValue.DrawIndex), 0),
                        StructMember("sample_mask", u32Handle, BindingAttribute.Builtin(BuiltinValue.SampleMask), 4)
                    )
                )
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "@builtin(draw_index) draw_index: u32"
        code shouldContain "@builtin(sample_mask) sample_mask: u32"
    }

    test("emit non call expression writes phony assignment") {
        val module = Module()
        val expressions = Arena<Expression>()
        val expression = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(1))))
        )
        val blocks = Arena<Block>()
        val body = blocks.append(Block(listOf(Statement.Emit(rangeOf(expression)))))

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = 1;"
    }

    test("non-finite float literals do not get numeric decimal suffixes") {
        val module = Module()
        val expressions = Arena<Expression>()
        val infinity = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.POSITIVE_INFINITY))))
        )
        val negativeInfinity = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.NEGATIVE_INFINITY))))
        )
        val nan = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.F32(Float.NaN))))
        )
        val blocks = Arena<Block>()
        val body = blocks.append(
            Block(
                listOf(
                    Statement.Emit(rangeOf(infinity)),
                    Statement.Emit(rangeOf(negativeInfinity)),
                    Statement.Emit(rangeOf(nan))
                )
            )
        )

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = Infinityf;"
        code shouldContain "_ = -Infinityf;"
        code shouldContain "_ = NaNf;"
    }

    test("negated negative integer literals are written with stable roundtrip shape") {
        val module = Module()
        val expressions = Arena<Expression>()
        val minI32 = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(Int.MIN_VALUE))))
        )
        val negativeI32 = expressions.append(
            Expression(ExpressionKind.Literal(LiteralValue.Scalar(ScalarValue.I32(-5))))
        )
        val negated = expressions.append(Expression(ExpressionKind.Unary(UnaryOperator.Negate, minI32)))
        val negatedNegative = expressions.append(Expression(ExpressionKind.Unary(UnaryOperator.Negate, negativeI32)))
        val blocks = Arena<Block>()
        val body = blocks.append(Block(listOf(Statement.Emit(rangeOf(negated)), Statement.Emit(rangeOf(negatedNegative)))))

        module.functions.append(
            Function(
                name = "main",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = WgslModule.writeString(module)
        code shouldContain "_ = -(2147483648);"
        code shouldContain "_ = -(-5);"
    }

    test("empty native builtin stubs are not emitted") {
        val module = lowerWgsl(
            """
            @group(0) @binding(0)
            var<storage, read_write> counter: atomic<i32>;

            @compute @workgroup_size(1)
            fn main() {
                let value = abs(-1);
                let old = atomicLoad(&counter);
                workgroupBarrier();
            }
            """.trimIndent()
        )

        val code = WgslModule.writeString(module)

        code shouldContain "abs("
        code shouldContain "atomicLoad("
        code shouldContain "workgroupBarrier();"
        code shouldNotContain "\nfn abs("
        code shouldNotContain "\nfn atomicLoad("
        code shouldNotContain "\nfn workgroupBarrier("
    }

    test("atomic types are preserved in IR and WGSL output") {
        val module = lowerWgsl(
            """
            struct Payload {
                count: atomic<i32>,
            }

            @group(0) @binding(0)
            var<storage, read_write> scalar: atomic<u64>;

            @group(0) @binding(1)
            var<storage, read_write> values: array<atomic<i64>, 2>;

            @group(0) @binding(2)
            var<storage, read_write> payload: Payload;

            @compute @workgroup_size(1)
            fn main() {
                let previous = atomicLoad(&scalar);
                atomicStore(&scalar, previous);
                let exchanged = atomicCompareExchangeWeak(&scalar, previous, previous);
            }
            """.trimIndent()
        )

        val innerTypeNames = module.types.toList().map { it.inner::class.simpleName }
        innerTypeNames.count { it == "Atomic" } shouldBe 3

        val code = WgslModule.writeString(module)

        code shouldContain "count: atomic<i32>,"
        code shouldContain "var<storage, read_write> scalar: atomic<u64>;"
        code shouldContain "var<storage, read_write> values: array<atomic<i64>, 2>;"
        code shouldContain "old_value: u64,"
        code shouldContain "var previous: u64 = atomicLoad(&scalar);"
        code shouldContain "atomicStore(&scalar, previous);"
        code shouldContain "atomicCompareExchangeWeak(&scalar, previous, previous)"
        code shouldNotContain "\nfn atomicLoad("
        code shouldNotContain "\nfn atomicStore("
    }

    test("storage texture access modes are preserved in IR and WGSL output") {
        val module = lowerWgsl(
            """
            @group(0) @binding(0)
            var imageAtomic: texture_storage_2d<r64uint, atomic>;

            @group(0) @binding(1)
            var imageAtomic32: texture_storage_2d<r32uint, atomic>;

            @group(0) @binding(2)
            var imageReadWrite: texture_storage_2d<rgba8unorm, read_write>;

            @compute @workgroup_size(1)
            fn main() {
                textureAtomicMax(imageAtomic32, vec2<i32>(0), 1u);
                let color = textureLoad(imageReadWrite, vec2<i32>(0));
            }
            """.trimIndent()
        )

        module.globalVariables.toList().map { it.storageClass }.shouldContain(StorageClass.Handle)
        module.types.toList().mapNotNull { (it.inner as? TypeInner.Opaque)?.name }
            .shouldContain("texture_storage_2d<r64uint, atomic>")
        module.types.toList().mapNotNull { (it.inner as? TypeInner.Opaque)?.name }
            .shouldContain("texture_storage_2d<r32uint, atomic>")
        module.types.toList().mapNotNull { (it.inner as? TypeInner.Opaque)?.name }
            .shouldContain("texture_storage_2d<rgba8unorm, read_write>")

        val code = WgslModule.writeString(module)

        code shouldContain "var imageAtomic: texture_storage_2d<r64uint, atomic>;"
        code shouldContain "var imageAtomic32: texture_storage_2d<r32uint, atomic>;"
        code shouldContain "var imageReadWrite: texture_storage_2d<rgba8unorm, read_write>;"
        code shouldContain "textureAtomicMax(imageAtomic32, vec2<i32>(0), 1u)"
        code shouldContain "textureLoad(imageReadWrite, vec2<i32>(0))"
        code shouldNotContain "texture_storage_2d<r64uint>;"
        code shouldNotContain "var<private> imageAtomic"
        code shouldNotContain "\nfn textureAtomicMax("
        code shouldNotContain "\nfn textureLoad("
    }

    test("global const declarations are distinct from private globals") {
        val module = lowerWgsl(
            """
            const SIZE: u32 = 128u;
            var<private> counter: u32 = 1u;

            @compute @workgroup_size(1)
            fn main() {
                var values: array<u32, SIZE>;
                counter = SIZE;
            }
            """.trimIndent()
        )

        module.globalVariables.toList().single { it.name == "SIZE" }.declaration shouldBe GlobalVariableDeclaration.Const
        module.globalVariables.toList().single { it.name == "counter" }.declaration shouldBe GlobalVariableDeclaration.Var

        val code = WgslModule.writeString(module)

        code shouldContain "const SIZE: u32 = 128u;"
        code shouldContain "var<private> counter: u32 = 1u;"
        code shouldContain "var values: array<u32, 128>;"
        code shouldNotContain "var<private> SIZE"
    }

    test("compute entry point workgroup size and builtin parameters are preserved") {
        val module = lowerWgsl(
            """
            @compute @workgroup_size(2, 1, 1)
            fn cs_main(@builtin(local_invocation_id) id: vec3<u32>) {
                let x = id.x;
            }
            """.trimIndent()
        )

        val entryPoint = module.entryPoints.single()
        entryPoint.workgroupSize shouldBe listOf(2, 1, 1)
        val function = module.functions[entryPoint.function]
        function.parameters.single().binding shouldBe BindingAttribute.Builtin(BuiltinValue.LocalInvocationId)

        val code = WgslModule.writeString(module)

        code shouldContain "@compute"
        code shouldContain "@workgroup_size(2, 1, 1)"
        code shouldContain "fn cs_main(@builtin(local_invocation_id) id: vec3<u32>)"
    }

    test("entry point builtin parameter names use WGSL spelling") {
        val module = lowerWgsl(
            """
            @fragment
            fn fs_main(
                @builtin(front_facing) face: bool,
                @builtin(primitive_index) primitive: u32,
                @builtin(sample_index) sample: u32,
                @builtin(sample_mask) mask: u32,
            ) {
            }
            """.trimIndent()
        )

        val code = WgslModule.writeString(module)

        code shouldContain "@builtin(front_facing) face: bool"
        code shouldContain "@builtin(primitive_index) primitive: u32"
        code shouldContain "@builtin(sample_index) sample: u32"
        code shouldContain "@builtin(sample_mask) mask: u32"
        code shouldNotContain "frontfacing"
        code shouldNotContain "primitiveindex"
        code shouldNotContain "sampleindex"
        code shouldNotContain "samplemask"
    }
})

private fun lowerWgsl(source: String): Module {
    val unit = parseWgsl(source)
    val result = TypeResolver().resolve(unit)
    check(result.isSuccess) { "WGSL test fixture did not resolve: ${result.unresolvedReferences}" }
    return Lowerer().lower(result.resolvedUnit)
}
