package org.graphiks.wgsl.generator.hlsl

import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import org.graphiks.wgsl.arena.Arena
import org.graphiks.wgsl.ir.*
import org.graphiks.wgsl.ir.Function
import org.graphiks.wgsl.parser.Lowerer
import org.graphiks.wgsl.parser.TypeResolver
import org.graphiks.wgsl.parser.parseWgsl

class HlslWriterTest : FunSpec({

    test("testEmptyModule") {
        val module = Module()
        val code = HlslModule.writeString(module)
        code shouldContain "// Generated by WebGPU-KTypes HLSL Backend"
    }

    test("testModuleWithStructAndFunction") {
        val module = Module()

        // Add a scalar type
        val f32Handle = module.types.append(Type(TypeInner.Scalar(ScalarKind.F32, 4)))

        // Add a struct
        module.types.append(
            Type(TypeInner.Struct(listOf(
                StructMember("a", f32Handle, null, 0)
            )))
        )

        // Add a function
        val expressions = Arena<Expression>()
        val blocks = Arena<org.graphiks.wgsl.ir.Block>()
        val body = blocks.append(org.graphiks.wgsl.ir.Block(emptyList()))

        module.functions.append(
            Function(
                name = "my_func",
                parameters = emptyList(),
                returnType = null,
                localVariables = Arena(),
                expressions = expressions,
                blocks = blocks,
                body = body
            )
        )

        val code = HlslModule.writeString(module)
        code shouldContain "struct Struct_1"
        code shouldContain "float a;"
        code shouldContain "void my_func()"
    }

    test("array_declaration_writes_suffix_on_declarator_instead_of_void") {
        val module = lowerWgsl("""
            fn values() {
                var values: array<f32, 4>;
            }
        """.trimIndent())

        val code = HlslModule.writeString(module)

        code shouldContain "float local_0[4];"
    }
})

private fun lowerWgsl(source: String): Module {
    val unit = parseWgsl(source)
    val result = TypeResolver().resolve(unit)
    check(result.isSuccess) { "WGSL test fixture did not resolve: ${result.unresolvedReferences}" }
    return Lowerer().lower(result.resolvedUnit)
}
